real: promote 8.6.0 (#177)

diff --git a/bin/dev-profile-set b/bin/dev-profile-set
--- a/bin/dev-profile-set
+++ b/bin/dev-profile-set
@@ -15,7 +15,7 @@
 export DEV_PROFILE
 declare MY_PROFILE="${1:-}"
 # shellcheck disable=2034
-declare MY_VERSION='3.0.0'
+declare MY_VERSION='3.1.0'
 
 function my_profile() {
   [[ -d "etc/prof/${MY_PROFILE}" ]] && return 0
@@ -24,7 +24,7 @@ function my_profile() {
 
 function my_load() {
   DEV_PROFILE="$MY_PROFILE"
-    source ./bin/dev-set ||
+  source ./bin/dev-set ||
     { echo 'dev-profile-set:Error: unable to load dev environment' 2>&1 && return 1; }
 }
 
@@ -32,8 +32,11 @@ function my_initialize() {
   [[ "${BASH_SOURCE[0]}" == "${0}" ]] &&
     echo 'dev-profile-set:Error: invalid execution method. Use the following command line to run this script: source ./bin/dev-profile-set.' 2>&1 &&
     return 1
-  [[ -z "$MY_PROFILE" ]] && 
+  [[ -z "$MY_PROFILE" ]] &&
     echo 'dev-profile-set:Error: missing profile name.' 2>&1 &&
+    return 1
+  [[ "$MY_PROFILE" == 'none' ]] &&
+    echo 'dev-profile-set:Error: invalid profile name (none).' 2>&1 &&
     return 1
   return 0
 }
