real: promote 5.7.0 (#115)

diff --git a/docs/skeletons/installer-bash/install-base b/docs/skeletons/installer-bash/install-base
--- a/docs/skeletons/installer-bash/install-base
+++ b/docs/skeletons/installer-bash/install-base
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-base-2.4.0
+# Template: install-base-3.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -56,40 +56,6 @@ declare INST64_X_APP_NAME_CAPS_X_CLI_PATH=''
 # X_STAND_ALONE_FUNCTIONS_X #
 
 #######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_X_APP_NAME_X_install() {
-  bl64_dbg_app_show_function
-  # X_INSTALL_PLACEHOLDER_X
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_X_APP_NAME_X_select_packages() {
-  bl64_dbg_app_show_function
-  # X_SELECT_PKG_PLACEHOLDER_X
-  [[ -z "$INST64_X_APP_NAME_CAPS_X_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-
-#######################################
 # Prepare installation
 #
 # Arguments:
@@ -103,7 +69,45 @@ function inst64_X_APP_NAME_X_select_packages() {
 function inst64_X_APP_NAME_X_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  # X_PREPARE_PLACEHOLDER_X
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
+    : # X_PREPARE_PLACEHOLDER_X
+  fi
+}
+
+#######################################
+# Install application packages
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package installer progress and errors
+# Returns:
+#   0: package installed ok
+#   >0: unable to install package
+#######################################
+function inst64_X_APP_NAME_X_install() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
+    : # X_INSTALL_PLACEHOLDER_X
+  fi
+}
+
+#######################################
+# Perform post installation setup
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Setup progress
+# Returns:
+#   0: setup completed ok
+#   >0: unable to setup
+#######################################
+function inst64_X_APP_NAME_X_setup() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
+    : # X_SETUP_PLACEHOLDER_X
+  fi
 }
 
 #######################################
@@ -120,8 +124,51 @@ function inst64_X_APP_NAME_X_prepare() {
 function inst64_X_APP_NAME_X_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  # X_VERIFY_PLACEHOLDER_X
-  # example # "$INST64_X_APP_NAME_CAPS_X_CLI_PATH" --version
+  : # X_VERIFY_PLACEHOLDER_X
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_X_APP_NAME_X_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
+    if [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]]; then
+      : # X_PLATFORM_SELECTION_PLACEHOLDER_X
+    fi
+  fi
+  [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
+  return 0
+}
+
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_X_APP_NAME_X_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
+    : # X_SELECT_PKG_PLACEHOLDER_X
+  fi
+  [[ -z "$INST64_X_APP_NAME_CAPS_X_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  return 0
 }
 
 #######################################
@@ -143,6 +190,10 @@ function inst64_X_APP_NAME_X_initialize() {
   if [[ -z "$INST64_OPT_ROOT" ]]; then
     bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
   fi
+  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_X_APP_NAME_CAPS_X_METHOD' \
+    "$INST64_X_APP_NAME_CAPS_X_METHOD" \
+    'X_METHOD_X' ||
+    return $?
   # X_INIT_PLACEHOLDER_X
   # X_PRE_REQ_PLACEHOLDER_X
   # X_SELECTORS_PLACEHOLDER_X
@@ -162,6 +213,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_X_APP_NAME_X_initialize &&
   inst64_X_APP_NAME_X_prepare &&
   inst64_X_APP_NAME_X_install &&
+  inst64_X_APP_NAME_X_setup &&
   inst64_X_APP_NAME_X_verify
-  # X_MAIN_POST_VERIFY_PLACEHOLDER_X
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
diff --git a/src/install-nodejs b/src/install-nodejs
--- a/src/install-nodejs
+++ b/src/install-nodejs
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-custom-2.5.0
+# Template: install-custom-3.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -79,8 +79,6 @@ function inst64_nodejs_install_custom_package() {
   local app_target_mode='0755'
   local app_target_owner="$BL64_IAM_SYSTEM_USER"
   local app_target_group="$BL64_IAM_SYSTEM_GROUP"
-  local app_cli_source="${INST64_NODEJS_PACKAGES%.tar.gz}/bin"
-  local app_component=''
 
   if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
     app_target_owner="$BL64_VAR_DEFAULT"
@@ -101,24 +99,6 @@ function inst64_nodejs_install_custom_package() {
     bl64_arc_open_tar "${work_path}/${INST64_NODEJS_PACKAGES}" "${INST64_NODEJS_TARGET}" ||
     return $?
 
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_msg_show_task "publish application to searchable path (${INST64_NODEJS_CLI_PATH})"
-    for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
-      bl64_fs_symlink_create \
-        "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
-        return $?
-    done
-  else
-    bl64_msg_show_task "publish generic application name (${INST64_NODEJS_CLI_PATH})"
-    bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_NODEJS_CLI_PATH" ||
-      return $?
-    for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
-      bl64_fs_symlink_create \
-        "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
-        return $?
-    done
-  fi
-
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
   return 0
@@ -131,6 +111,98 @@ function inst64_nodejs_select_packages_version() {
     bl64_txt_run_sed 's|/||g' |
     bl64_txt_run_sort -V |
     tail -n 1
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_nodejs_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+}
+
+#######################################
+# Install application packages
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package installer progress and errors
+# Returns:
+#   0: package installed ok
+#   >0: unable to install package
+#######################################
+function inst64_nodejs_install() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
+    inst64_nodejs_install_custom_package
+  fi
+}
+
+#######################################
+# Perform post installation setup
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Setup progress
+# Returns:
+#   0: setup completed ok
+#   >0: unable to setup
+#######################################
+function inst64_nodejs_setup() {
+  bl64_dbg_app_show_function
+  local app_cli_source=''
+  local app_component=''
+
+  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
+    app_cli_source="${INST64_NODEJS_TARGET}/${INST64_NODEJS_PACKAGES%.tar.gz}/bin"
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      bl64_msg_show_task "publish application to searchable path (${INST64_NODEJS_CLI_PATH})"
+      for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
+        bl64_fs_symlink_create \
+          "${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
+          return $?
+      done
+    else
+      bl64_msg_show_task "publish generic application name (${INST64_NODEJS_CLI_PATH})"
+      bl64_fs_dir_create "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$INST64_NODEJS_CLI_PATH" ||
+        return $?
+      for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
+        bl64_fs_symlink_create \
+          "${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
+          return $?
+      done
+    fi
+  fi
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_nodejs_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  export PATH="${PATH}:${INST64_NODEJS_CLI_PATH}"
+  "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NODE}" --version &&
+    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPM}" --version &&
+    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPX}" --version
 }
 
 #######################################
@@ -162,24 +234,6 @@ function inst64_nodejs_select_platform() {
   fi
   [[ -z "$INST64_NODEJS_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_nodejs_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
-    inst64_nodejs_install_custom_package
-  fi
 }
 
 #######################################
@@ -215,41 +269,6 @@ function inst64_nodejs_select_packages() {
   fi
   [[ -z "$INST64_NODEJS_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_nodejs_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_nodejs_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NODE}" --version &&
-    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPM}" --version &&
-    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPX}" --version
 }
 
 #######################################
@@ -307,7 +326,7 @@ function inst64_nodejs_initialize() {
 # Main
 #
 
-bl64_lib_script_version_set '1.3.1'
+bl64_lib_script_version_set '1.3.2'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -315,5 +334,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_nodejs_initialize &&
   inst64_nodejs_prepare &&
   inst64_nodejs_install &&
+  inst64_nodejs_setup &&
   inst64_nodejs_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
