doc: update

diff --git a/docs/skeletons/installer-bash/install-nodejs b/docs/skeletons/installer-bash/install-nodejs
--- a/docs/skeletons/installer-bash/install-nodejs
+++ b/docs/skeletons/installer-bash/install-nodejs
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# Template: install-nodejs-2.4.0
-#   Skeleton: installer-base-2.4.0
+# Template: install-nodejs-3.0.0
+#   Skeleton: installer-base-3.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -86,6 +86,22 @@ function inst64_X_APP_NAME_X_install_with_npm() {
 }
 
 #######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_X_APP_NAME_X_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+}
+
+#######################################
 # Install application packages
 #
 # Arguments:
@@ -101,6 +117,38 @@ function inst64_X_APP_NAME_X_install() {
   if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NPM' ]]; then
     inst64_X_APP_NAME_X_install_with_npm
   fi
+}
+
+#######################################
+# Perform post installation setup
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Setup progress
+# Returns:
+#   0: setup completed ok
+#   >0: unable to setup
+#######################################
+function inst64_X_APP_NAME_X_setup() {
+  bl64_dbg_app_show_function
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_X_APP_NAME_X_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "$INST64_X_APP_NAME_CAPS_X_CLI_PATH" --version
 }
 
 #######################################
@@ -134,42 +182,6 @@ function inst64_X_APP_NAME_X_select_packages() {
 }
 
 #######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_X_APP_NAME_X_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NPM' ]]; then
-    :
-  fi
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_X_APP_NAME_X_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_X_APP_NAME_CAPS_X_CLI_PATH" --version
-}
-
-#######################################
 # Initialize environment
 #
 # Arguments:
@@ -194,17 +206,13 @@ function inst64_X_APP_NAME_X_initialize() {
     return $?
 
   if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NPM' ]]; then
+    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && bl64_msg_show_error 'system-wide installation not supported' &&
+      return $BL64_LIB_ERROR_PARAMETER_INVALID
     bl64_check_command_search_path "$INST64_X_APP_NAME_CAPS_X_NPM_BIN" &&
-      bl64_check_privilege_not_root &&
-      bl64_os_check_compatibility \
-        "${BL64_OS_ALP}" \
-        "${BL64_OS_OL}" \
-        "${BL64_OS_FD}" \
-        "${BL64_OS_UB}" ||
+      bl64_check_privilege_not_root ||
       return $?
   fi
-  inst64_X_APP_NAME_X_select_platform &&
-    inst64_X_APP_NAME_X_select_packages ||
+  inst64_X_APP_NAME_X_select_packages ||
     return $?
   bl64_msg_show_setup 'Install application: X_APP_FULL_NAME_X' \
     'INST64_SYSTEM_WIDE' 'INST64_X_APP_NAME_CAPS_X_METHOD' \
@@ -224,5 +232,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_X_APP_NAME_X_initialize &&
   inst64_X_APP_NAME_X_prepare &&
   inst64_X_APP_NAME_X_install &&
+  inst64_X_APP_NAME_X_setup &&
   inst64_X_APP_NAME_X_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
