doc: update

diff --git a/docs/skeletons/installer-bash/install-base b/docs/skeletons/installer-bash/install-base
--- a/docs/skeletons/installer-bash/install-base
+++ b/docs/skeletons/installer-bash/install-base
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-base-4.0.0
+# Template: install-base-5.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,41 +17,39 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
+# shellcheck source-path=lib/bl64 disable=SC2015
 # X_IMPORTS_PLACEHOLDER_X
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-inst64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-# Install progress status
-declare INST64_STATUS_FLAG='CONTINUE'
+# Installation method
+declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-BINARY}"
+# Installation destination
+declare INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-}"
+# Hardware architecture
+declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
+# Application version
+declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
 
-# X_GLOBALS_PLACEHOLDER_X
-declare INST64_PKG_MAIN=''
-# optional # declare INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE=''
-# optional # declare INST64_X_APP_NAME_CAPS_X_PACKAGES_POST=''
-declare INST64_CLI_NAME='X_CLI_NAME_X'
-declare INST64_CLI_PATH=''
+# App information
+INST64_APP_NAME='X_APP_NAME_X'
+INST64_APP_ID='X_APP_NAME_CAPS_X'
+INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
+# CLI information
+INST64_CLI_NAME='X_CLI_NAME_X'
+INST64_CLI_PATH='X_CLI_CUSTOM_PATH_X'
+
+# X_GLOBALS_METHOD_PLACEHOLDER_X
 
 #
 # Functions
@@ -192,21 +190,21 @@ function inst64_X_APP_NAME_X_select_packages() {
 #######################################
 function inst64_X_APP_NAME_X_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_X_APP_NAME_CAPS_X_METHOD' \
-    "$INST64_X_APP_NAME_CAPS_X_METHOD" \
-    'X_METHOD_X' ||
+  inst64_lib_check_method \
+    'X_INIT_METHOD_PLACEHOLDER_X' &&
+    inst64_lib_base_set_system_wide &&
+    inst64_lib_base_set_path &&
+    inst64_lib_target_set_owner &&
+    inst64_lib_target_set_path &&
+    inst64_lib_cli_set_path ||
     return $?
   # X_INIT_PLACEHOLDER_X
   # X_PRE_REQ_PLACEHOLDER_X
-  # X_SELECTORS_PLACEHOLDER_X
-  bl64_msg_show_setup 'Install application: X_APP_FULL_NAME_X' \
-    'INST64_SYSTEM_WIDE' 'INST64_X_APP_NAME_CAPS_X_METHOD' 
+  inst64_X_APP_NAME_X_select_platform &&
+    inst64_X_APP_NAME_X_select_packages ||
+    return $?
+  inst64_lib_check_installed && return 0
+  inst64_lib_show_parameters
 }
 
 #
