real: promote 6.0.0 (#121)

diff --git a/docs/skeletons/installer-bash/install-custom b/docs/skeletons/installer-bash/install-custom
--- a/docs/skeletons/installer-bash/install-custom
+++ b/docs/skeletons/installer-bash/install-custom
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-custom-3.0.0
-#   Template: install-base-3.0.0
+# Template: install-bash-custom-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,296 +17,102 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
-# BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
-# shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+declare INST64_LIB_PATH="${INST64_LIB_PATH:-/opt/inst64}"
+[[ ! -d "$INST64_LIB_PATH" && -d "${HOME}/at64/inst64" ]] && INST64_LIB_PATH="${HOME}/at64/inst64"
+# shellcheck source-path=src disable=SC2015
+source "${INST64_LIB_PATH}/lib-bash" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
-declare INST64_X_APP_NAME_CAPS_X_SOURCE="${INST64_X_APP_NAME_CAPS_X_SOURCE:-X_APP_REPO_X}"
-declare INST64_X_APP_NAME_CAPS_X_TARGET=''
-declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
 # Installation method
 declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-}"
+# Hardware architecture
+declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
+# Application version
+declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
 
-declare INST64_X_APP_NAME_CAPS_X_PACKAGE_URL=''
-declare INST64_X_APP_NAME_CAPS_X_INSTALLER='X_INSTALLER_X'
-declare INST64_X_APP_NAME_CAPS_X_PACKAGES=''
-declare INST64_X_APP_NAME_CAPS_X_CLI_NAME='X_CLI_NAME_X'
-declare INST64_X_APP_NAME_CAPS_X_CLI_PATH=''
+# App information
+INST64_APP_NAME='X_APP_NAME_X'
+INST64_APP_ID='X_APP_NAME_CAPS_X'
+INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
+# shellcheck disable=SC2034
+INST64_SCRIPT_VERSION='1.0.0'
+# CLI information
+INST64_CLI_NAME='X_CLI_NAME_X'
+INST64_CLI_PATH='X_CLI_CUSTOM_PATH_X'
 
 #
 # Functions
 #
 
-function inst64_X_APP_NAME_X_install_custom_package() {
-  bl64_dbg_app_show_function
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner="$BL64_IAM_SYSTEM_USER"
-  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
-
-  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    app_target_owner="$BL64_VAR_DEFAULT"
-    app_target_group="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" &&
-    bl64_rxtx_web_get_file \
-      "${INST64_X_APP_NAME_CAPS_X_PACKAGE_URL}/${INST64_X_APP_NAME_CAPS_X_PACKAGES}" \
-      "${work_path}/${INST64_X_APP_NAME_CAPS_X_PACKAGES}" \
-      'YES' \
-      "$app_target_mode" &&
-    bl64_arc_open_tar "${work_path}/${INST64_X_APP_NAME_CAPS_X_PACKAGES}" "${work_path}" ||
-    return $?
-
-  bl64_msg_show_task 'deploy application'
-  # X_INSTALL_DEPLOYMENT_PLACEHOLDER_X
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
-}
-
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_X_APP_NAME_X_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
+    : # X_PREPARE_PLACEHOLDER_X
+  fi
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
 function inst64_X_APP_NAME_X_install() {
-  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
   if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
-    inst64_X_APP_NAME_X_install_custom_package
+    : # X_INSTALL_PLACEHOLDER_X
   fi
 }
 
-#######################################
-# Perform post installation setup
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Setup progress
-# Returns:
-#   0: setup completed ok
-#   >0: unable to setup
-#######################################
 function inst64_X_APP_NAME_X_setup() {
-  bl64_dbg_app_show_function
-  local app_cli_source=''
+  inst64_lib_step_setup || return 0
   if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      app_cli_source="${INST64_X_APP_NAME_CAPS_X_TARGET}/${INST64_X_APP_NAME_CAPS_X_CLI_NAME}"
-      bl64_msg_show_task "publish application to searchable path (${INST64_X_APP_NAME_CAPS_X_CLI_PATH})"
-      # shellcheck disable=SC2086
-      bl64_fs_symlink_create "${app_cli_source}" "$INST64_X_APP_NAME_CAPS_X_CLI_PATH" "$BL64_VAR_ON" ||
-        return $?
-    fi
+    : # X_SETUP_PLACEHOLDER_X
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
 function inst64_X_APP_NAME_X_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_X_APP_NAME_CAPS_X_CLI_PATH" --version
+  inst64_lib_step_verify || return 0
+  # X_VERIFY_PLACEHOLDER_X
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
 function inst64_X_APP_NAME_X_select_platform() {
-  bl64_dbg_app_show_function
   if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
-    if [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]]; then
-      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
-        INST64_X_APP_NAME_CAPS_X_PLATFORM='X_PLATFORM_TAG_X'
-      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
-        INST64_X_APP_NAME_CAPS_X_PLATFORM='X_PLATFORM_TAG_X'
-      else
-        bl64_msg_show_error "unsupported OS and Machine combination (OS_TYPE:${BL64_OS_TYPE} / MACHINE: ${BL64_OS_MACHINE})"
-        return $BL64_LIB_ERROR_OS_INCOMPATIBLE
-      fi
-    fi
+    : # X_PLATFORM_SELECTION_PLACEHOLDER_X
   fi
-  [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_X_APP_NAME_X_select_packages() {
-  bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
   if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
-    if [[ "$INST64_X_APP_NAME_CAPS_X_VERSION" == 'latest' ]]; then
-      INST64_X_APP_NAME_CAPS_X_VERSION="X_DETECT_LASTEST_VERSION_X"
-    fi
-    package_prefix='X_PACKAGE_PREFIX_X'
-    package_suffix='X_PACKAGE_SUFIX_X'
-    INST64_X_APP_NAME_CAPS_X_PACKAGES='X_PACKAGE_NAME_PLACEHOLDER_X'
-    INST64_X_APP_NAME_CAPS_X_PACKAGE_URL='X_PACKAGE_URL_PLACEHOLDER_X'
-    [[ -z "$INST64_X_APP_NAME_CAPS_X_PACKAGE_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_X_APP_NAME_CAPS_X_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_X_APP_NAME_CAPS_X_CLI_NAME}"
-    else
-      INST64_X_APP_NAME_CAPS_X_CLI_PATH="${INST64_X_APP_NAME_CAPS_X_TARGET}/${INST64_X_APP_NAME_CAPS_X_CLI_NAME}"
-    fi
+    : # X_SELECT_PKG_PLACEHOLDER_X
   fi
-  [[ -z "$INST64_X_APP_NAME_CAPS_X_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_X_APP_NAME_X_initialize() {
-  bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-${INST64_OPT_ROOT}/X_APP_NAME_X}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_X_APP_NAME_CAPS_X_METHOD' \
-    "$INST64_X_APP_NAME_CAPS_X_METHOD" \
-    'CUSTOM' ||
+  inst64_lib_base_initialize &&
+    inst64_lib_app_check_method 'CUSTOM' ||
     return $?
 
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'CUSTOM' ]]; then
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      bl64_check_privilege_root ||
-        return $?
-    fi
-    bl64_os_check_compatibility \
-      "${BL64_OS_UB}" \
-      "${BL64_OS_OL}" \
-      "${BL64_OS_FD}" &&
-      bl64_arc_setup ||
-      return $?
-  fi
+  # X_INIT_PLACEHOLDER_X
+  # X_PRE_REQ_PLACEHOLDER_X
+
   inst64_X_APP_NAME_X_select_platform &&
     inst64_X_APP_NAME_X_select_packages ||
     return $?
 
-  bl64_msg_show_setup 'Install application: X_APP_FULL_NAME_X' \
-    'INST64_SYSTEM_WIDE' 'INST64_X_APP_NAME_CAPS_X_METHOD' \
-    'INST64_X_APP_NAME_CAPS_X_PLATFORM' \
-    'INST64_X_APP_NAME_CAPS_X_SOURCE' \
-    'INST64_X_APP_NAME_CAPS_X_TARGET' \
-    'INST64_X_APP_NAME_CAPS_X_VERSION' \
-    'INST64_X_APP_NAME_CAPS_X_CLI_PATH'
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.0.0'
-bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
-
-[[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
-inst64_X_APP_NAME_X_initialize &&
+inst64_lib_task_process_start &&
+  inst64_X_APP_NAME_X_initialize &&
   inst64_X_APP_NAME_X_prepare &&
   inst64_X_APP_NAME_X_install &&
   inst64_X_APP_NAME_X_setup &&
   inst64_X_APP_NAME_X_verify
-bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
+inst64_lib_task_process_finish $?
diff --git a/docs/skeletons/installer-bl64/install-nodejs b/docs/skeletons/installer-bl64/install-nodejs
--- a/docs/skeletons/installer-bl64/install-nodejs
+++ b/docs/skeletons/installer-bl64/install-nodejs
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# Template: install-python-2.4.0
-#   Skeleton: installer-base-2.4.0
+# Template: install-nodejs-3.0.0
+#   Skeleton: installer-base-3.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -24,8 +24,7 @@ declare INST64_HOME="${HOME}/at64"
 declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
 [[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-py.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
@@ -54,113 +53,37 @@ declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
 
 declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
 # Installation method
-declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-PIP}"
+declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-NPM}"
 
-declare INST64_X_APP_NAME_CAPS_X_PIPX_BIN="${INST64_X_APP_NAME_CAPS_X_PIPX_BIN:-pipx}"
-declare INST64_X_APP_NAME_CAPS_X_PACKAGES=''
+declare INST64_X_APP_NAME_CAPS_X_NPM_BIN="${INST64_X_APP_NAME_CAPS_X_NPM_BIN:-npm}"
+declare INST64_PKG_MAIN=''
 declare INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE=''
 declare INST64_X_APP_NAME_CAPS_X_PACKAGES_POST=''
-declare INST64_X_APP_NAME_CAPS_X_CLI_NAME='X_CLI_NAME_X'
-declare INST64_X_APP_NAME_CAPS_X_CLI_PATH=''
+declare INST64_CLI_NAME='X_CLI_NAME_X'
+declare INST64_CLI_PATH=''
 
 #
 # Functions
 #
 
-function inst64_X_APP_NAME_X_install_with_pip() {
+function inst64_X_APP_NAME_X_install_with_npm() {
   bl64_dbg_app_show_function
 
   bl64_msg_show_task 'deploy application'
   if [[ -n "$INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE" ]]; then
     # shellcheck disable=SC2086
-    bl64_py_pip_usr_install $INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE ||
-      return $?
-  fi
-  # shellcheck disable=SC2086
-  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
-    bl64_py_pip_usr_deploy $INST64_X_APP_NAME_CAPS_X_PACKAGES ||
-    return $?
-  if [[ -n "$INST64_X_APP_NAME_CAPS_X_PACKAGES_POST" ]]; then
-    # shellcheck disable=SC2086
-    bl64_py_pip_usr_install $INST64_X_APP_NAME_CAPS_X_PACKAGES_POST ||
-      return $?
-  fi
-  return 0
-}
-
-function inst64_X_APP_NAME_X_install_with_pipx() {
-  bl64_dbg_app_show_function
-
-  bl64_msg_show_task 'deploy application'
-  if [[ -n "$INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE" ]]; then
-    # shellcheck disable=SC2086
-    "$INST64_X_APP_NAME_CAPS_X_PIPX_BIN" install --preinstall $INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE $INST64_X_APP_NAME_CAPS_X_PACKAGES ||
+    "$INST64_X_APP_NAME_CAPS_X_NPM_BIN" install $INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE $INST64_PKG_MAIN ||
       return $?
   else
     # shellcheck disable=SC2086
-    "$INST64_X_APP_NAME_CAPS_X_PIPX_BIN" install $INST64_X_APP_NAME_CAPS_X_PACKAGES $INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE ||
+    "$INST64_X_APP_NAME_CAPS_X_NPM_BIN" install $INST64_PKG_MAIN $INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE ||
       return $?
   fi
   if [[ -n "$INST64_X_APP_NAME_CAPS_X_PACKAGES_POST" ]]; then
     # shellcheck disable=SC2086
-    "$INST64_X_APP_NAME_CAPS_X_PIPX_BIN" inject $INST64_X_APP_NAME_CAPS_X_PACKAGES $INST64_X_APP_NAME_CAPS_X_PACKAGES_POST ||
+    "$INST64_X_APP_NAME_CAPS_X_NPM_BIN" install $INST64_PKG_MAIN $INST64_X_APP_NAME_CAPS_X_PACKAGES_POST ||
       return $?
   fi
-  return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_X_APP_NAME_X_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' ]]; then
-    inst64_X_APP_NAME_X_install_with_pipx
-  elif [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
-    inst64_X_APP_NAME_X_install_with_pip
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_X_APP_NAME_X_select_packages() {
-  bl64_dbg_app_show_function
-  local version_target=''
-
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' || "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
-    if [[ "$INST64_X_APP_NAME_CAPS_X_VERSION" == 'latest' ]]; then
-      version_target=''
-    else
-      version_target="==${INST64_X_APP_NAME_CAPS_X_VERSION}.*"
-    fi
-    INST64_X_APP_NAME_CAPS_X_PACKAGES="X_PYTHON_MODULE_X${version_target}"
-    INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE='X_PACKAGES_PRE_X'
-    INST64_X_APP_NAME_CAPS_X_PACKAGES_POST='X_PACKAGES_POST_X'
-
-    if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
-      INST64_X_APP_NAME_CAPS_X_CLI_PATH="${BL64_PY_PATH_PIP_USR_BIN}/${INST64_X_APP_NAME_CAPS_X_CLI_NAME}"
-    elif [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' ]]; then
-      INST64_X_APP_NAME_CAPS_X_CLI_PATH="${INST64_X_APP_NAME_CAPS_X_CLI_NAME}"
-    fi
-  fi
-  [[ -z "$INST64_X_APP_NAME_CAPS_X_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
 }
 
@@ -181,6 +104,39 @@ function inst64_X_APP_NAME_X_prepare() {
 }
 
 #######################################
+# Install application packages
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package installer progress and errors
+# Returns:
+#   0: package installed ok
+#   >0: unable to install package
+#######################################
+function inst64_X_APP_NAME_X_install() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NPM' ]]; then
+    inst64_X_APP_NAME_X_install_with_npm
+  fi
+}
+
+#######################################
+# Perform post installation setup
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Setup progress
+# Returns:
+#   0: setup completed ok
+#   >0: unable to setup
+#######################################
+function inst64_X_APP_NAME_X_setup() {
+  bl64_dbg_app_show_function
+}
+
+#######################################
 # Verify installation
 #
 # Arguments:
@@ -194,7 +150,37 @@ function inst64_X_APP_NAME_X_prepare() {
 function inst64_X_APP_NAME_X_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  "$INST64_X_APP_NAME_CAPS_X_CLI_PATH" --version
+  "$INST64_CLI_PATH" --version
+}
+
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_X_APP_NAME_X_select_packages() {
+  bl64_dbg_app_show_function
+  local version_target=''
+
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NPM' ]]; then
+    if [[ "$INST64_X_APP_NAME_CAPS_X_VERSION" == 'latest' ]]; then
+      version_target=''
+    else
+      version_target="@${INST64_X_APP_NAME_CAPS_X_VERSION}"
+    fi
+    INST64_PKG_MAIN="X_NODE_MODULE_X${version_target}"
+    INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE='X_PACKAGES_PRE_X'
+    INST64_X_APP_NAME_CAPS_X_PACKAGES_POST='X_PACKAGES_POST_X'
+    INST64_CLI_PATH="${INST64_CLI_NAME}"
+  fi
+  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  return 0
 }
 
 #######################################
@@ -218,16 +204,14 @@ function inst64_X_APP_NAME_X_initialize() {
   fi
   bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_X_APP_NAME_CAPS_X_METHOD' \
     "$INST64_X_APP_NAME_CAPS_X_METHOD" \
-    'PIP' 'PIPX' ||
+    'NPM' ||
     return $?
 
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' || "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
-    if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' ]]; then
-      bl64_check_command_search_path "$INST64_X_APP_NAME_CAPS_X_PIPX_BIN" ||
-        return $?
-    fi
-    bl64_check_privilege_not_root &&
-      bl64_py_setup ||
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NPM' ]]; then
+    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && bl64_msg_show_error 'system-wide installation not supported' &&
+      return $BL64_LIB_ERROR_PARAMETER_INVALID
+    bl64_check_command_search_path "$INST64_X_APP_NAME_CAPS_X_NPM_BIN" &&
+      bl64_check_privilege_not_root ||
       return $?
   fi
   inst64_X_APP_NAME_X_select_packages ||
@@ -235,7 +219,7 @@ function inst64_X_APP_NAME_X_initialize() {
   bl64_msg_show_setup 'Install application: X_APP_FULL_NAME_X' \
     'INST64_SYSTEM_WIDE' 'INST64_X_APP_NAME_CAPS_X_METHOD' \
     'INST64_X_APP_NAME_CAPS_X_VERSION' \
-    'INST64_X_APP_NAME_CAPS_X_CLI_PATH'
+    'INST64_CLI_PATH'
 }
 
 #
@@ -250,5 +234,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_X_APP_NAME_X_initialize &&
   inst64_X_APP_NAME_X_prepare &&
   inst64_X_APP_NAME_X_install &&
+  inst64_X_APP_NAME_X_setup &&
   inst64_X_APP_NAME_X_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
diff --git a/docs/skeletons/installer-bl64/install-python b/docs/skeletons/installer-bl64/install-python
--- a/docs/skeletons/installer-bl64/install-python
+++ b/docs/skeletons/installer-bl64/install-python
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# Template: install-base-4.0.0
+# Template: install-bl64-python-1.0.0
+#   Skeleton: install-bl64-custom-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,47 +18,52 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
-# X_IMPORTS_PLACEHOLDER_X
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-py.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-# Install progress status
-declare INST64_X_APP_NAME_CAPS_X_STATUS='CONTINUE'
+# Installation method
+declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-PIPX}"
+# Installation destination
+declare INST64_X_APP_NAME_CAPS_X_TARGET="${INST64_X_APP_NAME_CAPS_X_TARGET:-}"
+# Hardware architecture
+declare INST64_X_APP_NAME_CAPS_X_PLATFORM="${INST64_X_APP_NAME_CAPS_X_PLATFORM:-}"
+# Application version
+declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
 
-# X_GLOBALS_PLACEHOLDER_X
-declare INST64_X_APP_NAME_CAPS_X_PACKAGES=''
-# optional # declare INST64_X_APP_NAME_CAPS_X_PACKAGES_PRE=''
-# optional # declare INST64_X_APP_NAME_CAPS_X_PACKAGES_POST=''
-declare INST64_X_APP_NAME_CAPS_X_CLI_NAME='X_CLI_NAME_X'
-declare INST64_X_APP_NAME_CAPS_X_CLI_PATH=''
+# App information
+INST64_APP_NAME='X_APP_NAME_X'
+INST64_APP_ID='X_APP_NAME_CAPS_X'
+INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
+# CLI information
+INST64_CLI_NAME='X_CLI_NAME_X'
+INST64_CLI_PATH='X_CLI_CUSTOM_PATH_X'
+
+INST64_PKG_MAIN=''
+INST64_PKG_PRE=''
+INST64_PKG_POST=''
 
 #
 # Functions
 #
-
-# X_STAND_ALONE_FUNCTIONS_X #
 
 #######################################
 # Prepare installation
@@ -72,11 +78,7 @@ declare INST64_X_APP_NAME_CAPS_X_CLI_PATH=''
 #######################################
 function inst64_X_APP_NAME_X_prepare() {
   bl64_dbg_app_show_function
-  [[ "$INST64_X_APP_NAME_CAPS_X_STATUS" == 'SKIP' ]] && return 0
-  bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
-    : # X_PREPARE_PLACEHOLDER_X
-  fi
+  inst64_lib_step_prepare || return 0
 }
 
 #######################################
@@ -92,9 +94,11 @@ function inst64_X_APP_NAME_X_prepare() {
 #######################################
 function inst64_X_APP_NAME_X_install() {
   bl64_dbg_app_show_function
-  [[ "$INST64_X_APP_NAME_CAPS_X_STATUS" == 'SKIP' ]] && return 0
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
-    : # X_INSTALL_PLACEHOLDER_X
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' ]]; then
+    inst64_lib_python_install_pipx
+  elif [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
+    inst64_lib_python_install_pip
   fi
 }
 
@@ -111,10 +115,7 @@ function inst64_X_APP_NAME_X_install() {
 #######################################
 function inst64_X_APP_NAME_X_setup() {
   bl64_dbg_app_show_function
-  [[ "$INST64_X_APP_NAME_CAPS_X_STATUS" == 'SKIP' ]] && return 0
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
-    : # X_SETUP_PLACEHOLDER_X
-  fi
+  inst64_lib_step_setup || return 0
 }
 
 #######################################
@@ -130,9 +131,9 @@ function inst64_X_APP_NAME_X_setup() {
 #######################################
 function inst64_X_APP_NAME_X_verify() {
   bl64_dbg_app_show_function
-  [[ "$INST64_X_APP_NAME_CAPS_X_STATUS" == 'SKIP' ]] && return 0
-  bl64_msg_show_task 'verify deployment'
-  : # X_VERIFY_PLACEHOLDER_X
+  inst64_lib_step_verify || return 0
+  # X_VERIFY_PLACEHOLDER_X
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
 }
 
 #######################################
@@ -150,12 +151,6 @@ function inst64_X_APP_NAME_X_verify() {
 #######################################
 function inst64_X_APP_NAME_X_select_platform() {
   bl64_dbg_app_show_function
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
-    if [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]]; then
-      : # X_PLATFORM_SELECTION_PLACEHOLDER_X
-    fi
-  fi
-  [[ -z "$INST64_X_APP_NAME_CAPS_X_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -172,11 +167,15 @@ function inst64_X_APP_NAME_X_select_platform() {
 #######################################
 function inst64_X_APP_NAME_X_select_packages() {
   bl64_dbg_app_show_function
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'X_METHOD_X' ]]; then
-    : # X_SELECT_PKG_PLACEHOLDER_X
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' || "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
+    if [[ "$INST64_X_APP_NAME_CAPS_X_VERSION" == 'latest' ]]; then
+      version_target=''
+    else
+      version_target="==${INST64_X_APP_NAME_CAPS_X_VERSION}.*"
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN}${version_target}"
   fi
-  [[ -z "$INST64_X_APP_NAME_CAPS_X_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
 #######################################
@@ -192,21 +191,24 @@ function inst64_X_APP_NAME_X_select_packages() {
 #######################################
 function inst64_X_APP_NAME_X_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_X_APP_NAME_CAPS_X_METHOD' \
-    "$INST64_X_APP_NAME_CAPS_X_METHOD" \
-    'X_METHOD_X' ||
+  inst64_lib_base_initialize &&
+    inst64_lib_app_check_method \
+      'PIP' 'PIPX' ||
     return $?
-  # X_INIT_PLACEHOLDER_X
-  # X_PRE_REQ_PLACEHOLDER_X
-  # X_SELECTORS_PLACEHOLDER_X
-  bl64_msg_show_setup 'Install application: X_APP_FULL_NAME_X' \
-    'INST64_SYSTEM_WIDE' 'INST64_X_APP_NAME_CAPS_X_METHOD' 
+
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIPX' || "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'PIP' ]]; then
+    bl64_check_privilege_not_root &&
+      bl64_py_setup ||
+      return $?
+  fi
+
+  inst64_X_APP_NAME_X_select_platform &&
+    inst64_X_APP_NAME_X_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
diff --git a/src/install-homebrew b/src/install-homebrew
--- a/src/install-homebrew
+++ b/src/install-homebrew
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: 1.3.0
+# Template: install-bash-custom-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -14,226 +14,127 @@
 #######################################
 
 #
+# Imports
+#
+
+declare INST64_LIB_PATH="${INST64_LIB_PATH:-/opt/inst64}"
+[[ ! -d "$INST64_LIB_PATH" && -d "${HOME}/at64/inst64" ]] && INST64_LIB_PATH="${HOME}/at64/inst64"
+# shellcheck source-path=src disable=SC2015
+source "${INST64_LIB_PATH}/lib-bash" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
+
+#
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-
-declare INST64_HOMEBREW_PLATFORM=''
-declare INST64_HOMEBREW_SOURCE="${INST64_HOMEBREW_SOURCE:-https://raw.githubusercontent.com/Homebrew/install}"
-
-# shellcheck disable=SC2034
-declare INST64_HOMEBREW_SCRIPT_VERSION='1.0.0'
 # Installation method
 declare INST64_HOMEBREW_METHOD="${INST64_HOMEBREW_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_HOMEBREW_TARGET="${INST64_HOMEBREW_TARGET:-}"
+# Hardware architecture
+declare INST64_HOMEBREW_PLATFORM="${INST64_HOMEBREW_PLATFORM:-}"
+# Application version
+declare INST64_HOMEBREW_VERSION="${INST64_HOMEBREW_VERSION:-latest}"
 
-declare INST64_HOMEBREW_PACKAGES='install.sh'
-declare INST64_HOMEBREW_PACKAGE_URL=''
-declare INST64_HOMEBREW_INSTALLER='install.sh'
-declare INST64_HOMEBREW_CLI_NAME='brew'
-declare INST64_HOMEBREW_CLI_PATH=''
+# App information
+INST64_APP_NAME='homebrew'
+INST64_APP_ID='HOMEBREW'
+INST64_APP_FULL_NAME='Homebrew'
+# CLI information
+INST64_CLI_NAME='brew'
+INST64_CLI_PATH=''
+# shellcheck disable=SC2034
+INST64_SCRIPT_VERSION='2.0.0'
 
-declare INST64_HOMEBREW_DOWNLOAD_TOOL='none'
-declare INST64_HOMEBREW_OS=''
+INST64_SYSTEM_WIDE='YES'
+
+INST64_GH_REPO_OWNER='Homebrew'
+INST64_GH_REPO_NAME='install'
+INST64_APP_INSTALLER='install.sh'
 
 #
 # Functions
 #
 
-function inst64_homebrew_os_detect() {
-  if [[ -f '/etc/alpine-release' ]]; then
-    INST64_HOMEBREW_OS='ALP'
-  fi
-}
+function inst64_homebrew_install_custom() {
+  local installer_path=''
+  inst64_lib_github_asset_download "$INST64_APP_INSTALLER" || return $?
 
-function inst64_homebrew_download_custom_package() {
-  echo "Task: download application (${INST64_HOMEBREW_PACKAGES})"
-  # shellcheck disable=SC2249
-  case "$INST64_HOMEBREW_DOWNLOAD_TOOL" in
-  'curl')
-    "$INST64_HOMEBREW_DOWNLOAD_TOOL" \
-      -s \
-      -L \
-      -o "$INST64_HOMEBREW_INSTALLER" \
-      "$INST64_HOMEBREW_PACKAGE_URL"
-    ;;
-  'wget')
-    "$INST64_HOMEBREW_DOWNLOAD_TOOL" \
-      -q \
-      -O "$INST64_HOMEBREW_INSTALLER" \
-      "$INST64_HOMEBREW_PACKAGE_URL"
-    ;;
-  esac
-  [[ -f "$INST64_HOMEBREW_INSTALLER" ]] &&
-    chmod 755 "$INST64_HOMEBREW_INSTALLER"
-}
+  inst64_lib_task_deploy
+  installer_path="${INST64_TMP}/${INST64_APP_INSTALLER}"
+  [[ -f "$installer_path" ]] &&
+    chmod 755 "$installer_path" &&
+    NONINTERACTIVE='YES' "$installer_path" ||
+    return $?
 
-function inst64_homebrew_install_custom_package() {
-  echo 'Task: install packages'
-  if [[ "$INST64_HOMEBREW_PLATFORM" == 'Darwin' ]]; then
-    INST64_HOMEBREW_CLI_PATH="/opt/homebrew/bin/${INST64_HOMEBREW_CLI_NAME}"
-  elif [[ "$INST64_HOMEBREW_PLATFORM" == 'Linux' ]]; then
-    INST64_HOMEBREW_CLI_PATH="/home/linuxbrew/.linuxbrew/bin/${INST64_HOMEBREW_CLI_NAME}"
-  else
-    "Error: unsupported platform (${INST64_HOMEBREW_PLATFORM})"
-    return 1
+  if [[ "$INST64_CPU_CURRENT" == 'Darwin' ]]; then
+    INST64_CLI_PATH="/opt/homebrew/bin"
+  elif [[ "$INST64_CPU_CURRENT" == 'Linux' ]]; then
+    INST64_CLI_PATH="/home/linuxbrew/.linuxbrew/bin"
   fi
-  inst64_homebrew_download_custom_package &&
-    NONINTERACTIVE='YES' "$INST64_HOMEBREW_INSTALLER"
-}
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
-function inst64_homebrew_select_platform() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_HOMEBREW_METHOD" == 'CUSTOM' ]]; then
-    INST64_HOMEBREW_PLATFORM="$(uname -s)"
-  fi
-  [[ -z "$INST64_HOMEBREW_PLATFORM" ]] && echo 'Error: unable to determine platform id' && return 1
+  rm -f "$installer_path"
   return 0
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_homebrew_install() {
-  if [[ "$INST64_HOMEBREW_METHOD" == 'CUSTOM' ]]; then
-    inst64_homebrew_install_custom_package
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_homebrew_select_packages() {
-  if [[ "$INST64_HOMEBREW_METHOD" == 'CUSTOM' ]]; then
-    INST64_HOMEBREW_PACKAGE_URL="${INST64_HOMEBREW_SOURCE}/HEAD/${INST64_HOMEBREW_PACKAGES}"
-    INST64_HOMEBREW_INSTALLER="${INST64_TMP}/${INST64_HOMEBREW_INSTALLER}"
-  fi
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_homebrew_prepare() {
-  echo 'Task: prepare deployment'
+  inst64_lib_step_prepare || return 0
   if [[ "$INST64_HOMEBREW_METHOD" == 'CUSTOM' ]]; then
-    INST64_TMP="${INST64_TMP}/inst64-homebrew-installer"
-    [[ -d "$INST64_TMP" ]] && rm -Rf "$INST64_TMP"
-    mkdir "$INST64_TMP" ||
+    :
+  fi
+}
+
+function inst64_homebrew_install() {
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_HOMEBREW_METHOD" == 'CUSTOM' ]]; then
+    inst64_homebrew_install_custom
+  fi
+}
+
+function inst64_homebrew_setup() {
+  inst64_lib_step_setup || return 0
+}
+
+function inst64_homebrew_verify() {
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
+}
+
+function inst64_homebrew_select_platform() {
+  return 0
+}
+
+function inst64_homebrew_select_packages() {
+  return 0
+}
+
+function inst64_homebrew_initialize() {
+  inst64_lib_base_initialize &&
+    inst64_lib_app_check_method 'CUSTOM' ||
+    return $?
+
+  if [[ "$INST64_HOMEBREW_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_check_privilege_not_root &&
+      inst64_lib_check_os_incompatibility 'ALPINE' ||
       return $?
   fi
+
   inst64_homebrew_select_platform &&
-    inst64_homebrew_select_packages
-}
+    inst64_homebrew_select_packages ||
+    return $?
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_homebrew_verify() {
-  echo 'Task: verify deployment'
-  "$INST64_HOMEBREW_CLI_PATH" --version
-}
-
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: failed to initialize
-#######################################
-function inst64_homebrew_initialize() {
-  inst64_homebrew_os_detect
-  [[ "$INST64_HOMEBREW_OS" == 'ALP' ]] &&
-    echo "Error: unsupported OS (${INST64_HOMEBREW_OS})" &&
-    return 1
-
-  [[ "$INST64_HOMEBREW_METHOD" != 'CUSTOM' ]] &&
-    echo 'Error: unsupported installation method' &&
-    return 1
-
-  if command -v 'curl' >/dev/null 2>&1; then
-    INST64_HOMEBREW_DOWNLOAD_TOOL='curl'
-  elif command -v 'wget' >/dev/null 2>&1; then
-    INST64_HOMEBREW_DOWNLOAD_TOOL='wget'
-  else
-    echo 'Error: no download tool found (curl, wget)'
-    return 1
-  fi
-  if [[ "$(id -u)" != 0 ]]; then
-    echo 'Error: installer must be run with root privilege'
-    return 1
-  fi
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-declare inst64_homebrew_task_description='Install application: Homebrew'
-declare -i inst64_homebrew_status=0
-
-echo "Process: [${inst64_homebrew_task_description}] started"
-
-[[ -n "$INST64_DEBUG" ]] && set -x
-inst64_homebrew_initialize &&
+inst64_lib_task_process_start &&
+  inst64_homebrew_initialize &&
   inst64_homebrew_prepare &&
   inst64_homebrew_install &&
+  inst64_homebrew_setup &&
   inst64_homebrew_verify
-inst64_homebrew_status=$?
-
-((inst64_homebrew_status == 0)) &&
-  echo "Process: [${inst64_homebrew_task_description}] finished successfully" ||
-  echo "Process: [${inst64_homebrew_task_description}] finished with errors: exit-status-${inst64_homebrew_status}"
-# shellcheck disable=SC2086
-exit $inst64_homebrew_status
+inst64_lib_task_process_finish $?
diff --git a/src/install-sysop64 b/src/install-sysop64
--- a/src/install-sysop64
+++ b/src/install-sysop64
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-custom-3.0.0
+# Template: install-bl64-binary-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -13,229 +13,128 @@
 # limitations under the License.
 #######################################
 
-#
-# Imports
-#
-
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
-#
-# Globals
-#
-
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_SYSOP64_PLATFORM="${INST64_SYSOP64_PLATFORM:-}"
-declare INST64_SYSOP64_TARGET="${INST64_SYSOP64_TARGET:-}"
-declare INST64_SYSOP64_VERSION="${INST64_SYSOP64_VERSION:-latest}"
 # Installation method
-declare INST64_SYSOP64_METHOD="${INST64_SYSOP64_METHOD:-CUSTOM}"
+declare INST64_SYSOP64_METHOD="${INST64_SYSOP64_METHOD:-BINARY}"
+# Installation destination
+declare INST64_SYSOP64_TARGET="${INST64_SYSOP64_TARGET:-}"
+# Hardware architecture
+declare INST64_SYSOP64_PLATFORM="${INST64_SYSOP64_PLATFORM:-}"
+# Application version
+declare INST64_SYSOP64_VERSION="${INST64_SYSOP64_VERSION:-latest}"
 
-declare INST64_SYSOP64_REPO_NAME='sysop64'
-declare INST64_SYSOP64_REPO_OWNER='automation64'
+INST64_APP_NAME='sysop64'
+INST64_APP_ID='SYSOP64'
+INST64_APP_FULL_NAME='SysOp64'
+INST64_CLI_NAME='so64'
 
-declare INST64_SYSOP64_PACKAGES=''
-declare INST64_SYSOP64_CLI_NAME='so64'
-declare INST64_SYSOP64_CLI_PATH=''
+INST64_GH_REPO_NAME='sysop64'
+INST64_GH_REPO_OWNER='automation64'
+INST64_PKG_MAIN_PREFIX='sysop64-scripts'
+INST64_PKG_MAIN_SUFFIX='.tar.gz'
 
-#
-# Functions
-#
-
-function inst64_sysop64_install_custom_package() {
+function inst64_sysop64_install_binary() {
   bl64_dbg_app_show_function
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner="$BL64_IAM_SYSTEM_USER"
-  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
 
-  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    app_target_owner="$BL64_VAR_DEFAULT"
-    app_target_group="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" &&
+  inst64_lib_task_binary_download &&
     bl64_rxtx_github_get_asset \
-      "$INST64_SYSOP64_REPO_OWNER" \
-      "$INST64_SYSOP64_REPO_NAME" \
-      "$INST64_SYSOP64_VERSION" \
-      "$INST64_SYSOP64_PACKAGES" \
-      "${work_path}/${INST64_SYSOP64_PACKAGES}" ||
+      "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_SYSOP64_VERSION" "$INST64_PKG_MAIN" "${INST64_WORK_PATH}/${INST64_PKG_MAIN}" ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  [[ -d "$INST64_SYSOP64_TARGET" ]] &&
-    bl64_fs_path_remove "$INST64_SYSOP64_TARGET"
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_SYSOP64_TARGET" &&
-    bl64_arc_open_tar "${work_path}/${INST64_SYSOP64_PACKAGES}" "$INST64_SYSOP64_TARGET" ||
+  inst64_lib_task_deploy
+  bl64_fs_path_remove "$INST64_SYSOP64_TARGET"
+  bl64_fs_dir_create "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$INST64_SYSOP64_TARGET" &&
+    bl64_arc_open_tar "${INST64_WORK_PATH}/${INST64_PKG_MAIN}" "$INST64_SYSOP64_TARGET" &&
+    bl64_fs_path_permission_set "$INST64_TARGET_MODE" "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$BL64_VAR_ON" \
+      "$INST64_SYSOP64_TARGET" ||
     return $?
 
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_sysop64_prepare() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_sysop64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_SYSOP64_METHOD" == 'CUSTOM' ]]; then
-    inst64_sysop64_install_custom_package
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_SYSOP64_METHOD" == 'BINARY' ]]; then
+    inst64_lib_base_create_path
   fi
 }
 
-#######################################
-# Perform post installation setup
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Setup progress
-# Returns:
-#   0: setup completed ok
-#   >0: unable to setup
-#######################################
+function inst64_sysop64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_SYSOP64_METHOD" == 'BINARY' ]]; then
+    inst64_sysop64_install_binary
+  fi
+}
+
 function inst64_sysop64_setup() {
   bl64_dbg_app_show_function
   local app_cli_source=''
-  if [[ "$INST64_SYSOP64_METHOD" == 'CUSTOM' ]]; then
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_SYSOP64_METHOD" == 'BINARY' ]]; then
     app_cli_source="${INST64_SYSOP64_TARGET}/sysop64/sysop64"
-    bl64_msg_show_task "publish application to searchable path (${INST64_SYSOP64_CLI_PATH})"
+    inst64_lib_task_publish
     # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${app_cli_source}" "$INST64_SYSOP64_CLI_PATH" "$BL64_VAR_ON"
+    bl64_fs_symlink_create "${app_cli_source}" "${INST64_CLI_PATH}/${INST64_CLI_NAME}" "$BL64_VAR_ON"
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
 function inst64_sysop64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
+  inst64_lib_step_verify || return 0
   [[ -d "$INST64_SYSOP64_TARGET" ]] &&
-    "$INST64_SYSOP64_CLI_PATH"
+    "${INST64_CLI_PATH}/${INST64_CLI_NAME}" || return $?
+  if [[ "$INST64_SYSOP64_METHOD" == 'BINARY' ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_sysop64_select_packages() {
+function inst64_sysop64_select_platform() {
   bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
-  if [[ "$INST64_SYSOP64_METHOD" == 'CUSTOM' ]]; then
-    package_prefix='sysop64-scripts'
-    package_suffix='.tar.gz'
-    INST64_SYSOP64_PACKAGES="${package_prefix}${package_suffix}"
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_SYSOP64_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_SYSOP64_CLI_NAME}"
-    else
-      INST64_SYSOP64_CLI_PATH="${INST64_SYSOP64_TARGET}/${INST64_SYSOP64_CLI_NAME}"
-    fi
-  fi
-  [[ -z "$INST64_SYSOP64_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
+function inst64_sysop64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_SYSOP64_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_SYSOP64_VERSION" == 'latest' ]]; then
+      INST64_SYSOP64_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
+        return $?
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_PKG_MAIN_SUFFIX}"
+  fi
+  inst64_lib_package_check_definition
+}
+
 function inst64_sysop64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_SYSOP64_TARGET="${INST64_SYSOP64_TARGET:-${INST64_OPT_ROOT}/sysop64}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_SYSOP64_METHOD' \
-    "$INST64_SYSOP64_METHOD" \
-    'CUSTOM' ||
+  inst64_lib_base_initialize &&
+    inst64_lib_app_check_method \
+      'BINARY' ||
     return $?
 
-  if [[ "$INST64_SYSOP64_METHOD" == 'CUSTOM' ]]; then
+  if [[ "$INST64_SYSOP64_METHOD" == 'BINARY' ]]; then
     if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
       bl64_check_privilege_root ||
         return $?
@@ -243,24 +142,21 @@ function inst64_sysop64_initialize() {
     bl64_arc_setup ||
       return $?
   fi
-  inst64_sysop64_select_packages ||
+
+  inst64_sysop64_select_platform &&
+    inst64_sysop64_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
 
-  bl64_msg_show_setup 'Install application: SysOp64' \
-    'INST64_SYSTEM_WIDE' 'INST64_SYSOP64_METHOD' \
-    'INST64_SYSOP64_PLATFORM' \
-    'INST64_SYSOP64_REPO_OWNER' \
-    'INST64_SYSOP64_REPO_NAME' \
-    'INST64_SYSOP64_TARGET' \
-    'INST64_SYSOP64_VERSION' \
-    'INST64_SYSOP64_CLI_PATH'
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.3.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
diff --git a/src/install-volta b/src/install-volta
--- a/src/install-volta
+++ b/src/install-volta
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# Template: install-github-4.0.0
+# Template: install-bl64-binary-1.0.0
+#   Skeleton: installer-base-5.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,11 +18,9 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
 source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
@@ -35,256 +34,140 @@ source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-# Install progress status
-declare INST64_VOLTA_STATUS='CONTINUE'
-
-declare INST64_VOLTA_PLATFORM="${INST64_VOLTA_PLATFORM:-}"
-declare INST64_VOLTA_TARGET=''
-declare INST64_VOLTA_VERSION="${INST64_VOLTA_VERSION:-latest}"
-declare INST64_VOLTA_INSTALLED=''
 # Installation method
 declare INST64_VOLTA_METHOD="${INST64_VOLTA_METHOD:-BINARY}"
+# Installation destination
+declare INST64_VOLTA_TARGET="${INST64_VOLTA_TARGET:-}"
+# Hardware architecture
+declare INST64_VOLTA_PLATFORM="${INST64_VOLTA_PLATFORM:-}"
+# Application version
+declare INST64_VOLTA_VERSION="${INST64_VOLTA_VERSION:-latest}"
 
-declare INST64_VOLTA_REPO_NAME='volta'
-declare INST64_VOLTA_REPO_OWNER='volta-cli'
-declare INST64_VOLTA_PACKAGES=''
-declare INST64_VOLTA_CLI_NAME='volta'
-declare INST64_VOLTA_CLI_PATH=''
+INST64_APP_NAME='volta'
+INST64_APP_ID='VOLTA'
+INST64_APP_FULL_NAME='Volta'
+INST64_CLI_NAME='volta'
+
+INST64_GH_REPO_NAME='volta'
+INST64_GH_REPO_OWNER='volta-cli'
+INST64_PKG_MAIN_PREFIX='volta-'
+INST64_PKG_MAIN_SUFFIX='.tar.gz'
+INST64_CPU_DARWIN_ARM64='macos'
+INST64_CPU_LINUX_AMD64='linux'
 
 #
 # Functions
 #
 
-function inst64_volta_install_binary_release() {
+function inst64_volta_install_binary() {
   bl64_dbg_app_show_function
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner="$BL64_IAM_SYSTEM_USER"
-  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
-  local app_cli_mode='0755'
-  local app_work_path="${INST64_VOLTA_CLI_NAME}"
+  local app_work_path="${INST64_CLI_NAME}"
 
-  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    app_target_owner="$BL64_VAR_DEFAULT"
-    app_target_group="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  bl64_rxtx_github_get_asset \
-    "$INST64_VOLTA_REPO_OWNER" "$INST64_VOLTA_REPO_NAME" "$INST64_VOLTA_VERSION" "$INST64_VOLTA_PACKAGES" "${work_path}/${INST64_VOLTA_PACKAGES}" &&
-    bl64_arc_open_tar "${work_path}/${INST64_VOLTA_PACKAGES}" "${work_path}" ||
+  inst64_lib_task_binary_download &&
+    bl64_rxtx_github_get_asset \
+      "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_VOLTA_VERSION" "$INST64_PKG_MAIN" "${INST64_WORK_PATH}/${INST64_PKG_MAIN}" &&
+    bl64_arc_open_tar "${INST64_WORK_PATH}/${INST64_PKG_MAIN}" "${INST64_WORK_PATH}" ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_VOLTA_TARGET" &&
-    bl64_fs_path_copy "$app_cli_mode" "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_VOLTA_TARGET" \
-      "${work_path}/${app_work_path}" \
-      "${work_path}/${app_work_path}-migrate" \
-      "${work_path}/${app_work_path}-shim" &&
-    echo "$INST64_VOLTA_VERSION" >"$INST64_VOLTA_INSTALLED" ||
+  inst64_lib_task_deploy
+  bl64_fs_dir_create "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$INST64_VOLTA_TARGET" &&
+    bl64_fs_path_copy "$INST64_CLI_MODE" "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$INST64_VOLTA_TARGET" \
+      "${INST64_WORK_PATH}/${app_work_path}" \
+      "${INST64_WORK_PATH}/${app_work_path}-migrate" \
+      "${INST64_WORK_PATH}/${app_work_path}-shim" ||
     return $?
 
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_volta_prepare() {
   bl64_dbg_app_show_function
-  [[ "$INST64_VOLTA_STATUS" == 'SKIP' ]] && return 0
-  bl64_msg_show_task 'prepare deployment'
+  inst64_lib_step_prepare || return 0
   if [[ "$INST64_VOLTA_METHOD" == 'BINARY' ]]; then
-    if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      bl64_bsh_xdg_create "$HOME"
-    fi
+    inst64_lib_base_create_path
   fi
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
 function inst64_volta_install() {
   bl64_dbg_app_show_function
-  [[ "$INST64_VOLTA_STATUS" == 'SKIP' ]] && return 0
+  inst64_lib_step_install || return 0
   if [[ "$INST64_VOLTA_METHOD" == 'BINARY' ]]; then
-    inst64_volta_install_binary_release
+    inst64_volta_install_binary
   fi
 }
 
-#######################################
-# Perform post installation setup
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Setup progress
-# Returns:
-#   0: setup completed ok
-#   >0: unable to setup
-#######################################
 function inst64_volta_setup() {
   bl64_dbg_app_show_function
   local app_cli_source=''
-  [[ "$INST64_VOLTA_STATUS" == 'SKIP' ]] && return 0
+  inst64_lib_step_setup || return 0
   if [[ "$INST64_VOLTA_METHOD" == 'BINARY' ]]; then
-    app_cli_source="${INST64_VOLTA_TARGET}/${INST64_VOLTA_CLI_NAME}"
-    bl64_msg_show_task "publish application to searchable path (${INST64_VOLTA_CLI_PATH})"
+    app_cli_source="${INST64_VOLTA_TARGET}/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
     # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${app_cli_source}" "$INST64_VOLTA_CLI_PATH" "$BL64_VAR_ON" &&
-      bl64_fs_symlink_create "${app_cli_source}-migrate" "${INST64_VOLTA_CLI_PATH}-migrate" "$BL64_VAR_ON"
+    bl64_fs_symlink_create "${app_cli_source}" "${INST64_CLI_PATH}/${INST64_CLI_NAME}" "$BL64_VAR_ON" &&
+      bl64_fs_symlink_create "${app_cli_source}-migrate" "${INST64_CLI_PATH}-migrate" "$BL64_VAR_ON" &&
+      bl64_fs_symlink_create "${app_cli_source}-shim" "${INST64_CLI_PATH}-shim" "$BL64_VAR_ON"
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
 function inst64_volta_verify() {
   bl64_dbg_app_show_function
-  [[ "$INST64_VOLTA_STATUS" == 'SKIP' ]] && return 0
-  bl64_msg_show_task 'verify deployment'
+  inst64_lib_step_verify || return 0
   cd "$HOME" &&
-    "$INST64_VOLTA_CLI_PATH" --version
+    "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version &&
+    inst64_lib_app_register_version
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
 function inst64_volta_select_platform() {
   bl64_dbg_app_show_function
   if [[ "$INST64_VOLTA_METHOD" == 'BINARY' ]]; then
     if [[ -z "$INST64_VOLTA_PLATFORM" ]]; then
       if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
-        INST64_VOLTA_PLATFORM='macos'
+        INST64_VOLTA_PLATFORM="$INST64_CPU_DARWIN_ARM64"
       elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
-        INST64_VOLTA_PLATFORM='linux'
+        INST64_VOLTA_PLATFORM="$INST64_CPU_LINUX_AMD64"
       else
-        bl64_msg_show_error "unsupported OS and Machine combination (OS_TYPE:${BL64_OS_TYPE} / MACHINE: ${BL64_OS_MACHINE})"
-        return $BL64_LIB_ERROR_OS_INCOMPATIBLE
+        inst64_lib_alert_incompatible_platform
+        return $?
       fi
     fi
+    inst64_lib_platform_check_cpu
   fi
-  [[ -z "$INST64_VOLTA_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_volta_select_packages() {
   bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
   if [[ "$INST64_VOLTA_METHOD" == 'BINARY' ]]; then
     if [[ "$INST64_VOLTA_VERSION" == 'latest' ]]; then
-      INST64_VOLTA_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_VOLTA_REPO_OWNER" "$INST64_VOLTA_REPO_NAME")" ||
+      INST64_VOLTA_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
         return $?
     fi
-    package_prefix='volta-'
-    package_suffix='.tar.gz'
-    INST64_VOLTA_PACKAGES="${package_prefix}${INST64_VOLTA_VERSION#v}-${INST64_VOLTA_PLATFORM}${package_suffix}"
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_VOLTA_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_VOLTA_CLI_NAME}"
-    else
-      INST64_VOLTA_CLI_PATH="${INST64_USER_BIN}/${INST64_VOLTA_CLI_NAME}"
-    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_VOLTA_VERSION#v}-${INST64_VOLTA_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
   fi
-  [[ -z "$INST64_VOLTA_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_volta_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_VOLTA_TARGET="${INST64_VOLTA_TARGET:-${INST64_OPT_ROOT}/volta}"
-  INST64_VOLTA_INSTALLED="${INST64_VOLTA_TARGET}/.${BL64_SCRIPT_NAME}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_VOLTA_METHOD' \
-    "$INST64_VOLTA_METHOD" \
-    'BINARY' ||
+  inst64_lib_base_initialize &&
+    inst64_lib_app_check_method \
+      'BINARY' ||
     return $?
 
   if [[ "$INST64_VOLTA_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
     bl64_os_check_flavor \
       "$BL64_OS_FLAVOR_DEBIAN" \
       "$BL64_OS_FLAVOR_FEDORA" \
@@ -292,38 +175,24 @@ function inst64_volta_initialize() {
       "$BL64_OS_FLAVOR_REDHAT" \
       "$BL64_OS_FLAVOR_SUSE" ||
       return $?
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      bl64_check_privilege_root ||
-        return $?
-    fi
     bl64_arc_setup ||
       return $?
   fi
+
   inst64_volta_select_platform &&
-    inst64_volta_select_packages ||
+    inst64_volta_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
-  if [[ -f "$INST64_VOLTA_INSTALLED" ]]; then
-    if [[ "$INST64_VOLTA_VERSION" == "$(<"$INST64_VOLTA_INSTALLED")" ]]; then
-      bl64_msg_show_warning "application already installed. No further action taken (${INST64_VOLTA_VERSION})"
-      INST64_VOLTA_STATUS='SKIP'
-      return 0
-    fi
-  fi
-  bl64_msg_show_setup 'Install application: Volta' \
-    'INST64_SYSTEM_WIDE' 'INST64_VOLTA_METHOD' \
-    'INST64_VOLTA_PLATFORM' \
-    'INST64_VOLTA_REPO_OWNER' \
-    'INST64_VOLTA_REPO_NAME' \
-    'INST64_VOLTA_TARGET' \
-    'INST64_VOLTA_VERSION' \
-    'INST64_VOLTA_CLI_PATH'
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.0.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
