feat: add installers (#86)

diff --git a/src/install-helm b/src/install-helm
--- a/src/install-helm
+++ b/src/install-helm
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
-# Template: 2.0.1
+# Template: 2.3.0
+# Snippet: install-custom-package-4.2.0
+# Snippet: select-platform-1.0.0
 #######################################
 # Installer64 / Package installer
 #
@@ -29,6 +31,23 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -37,53 +56,58 @@ export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
 # Base path for 3rd party applications
 export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
+# Location for temporary files
+export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-export INST64_HELM_PLATFORM="${INST64_HELM_PLATFORM:-linux-amd64}"
+export INST64_HELM_PLATFORM="${INST64_HELM_PLATFORM:-}"
+export INST64_HELM_SOURCE="${INST64_HELM_SOURCE:-https://get.helm.sh}"
 export INST64_HELM_TARGET="${INST64_HELM_TARGET:-${INST64_OPT_ROOT}/helm}"
 export INST64_HELM_VERSION="${INST64_HELM_VERSION:-latest}"
 # Install system wide? Requires root privilege
 export INST64_HELM_SYSTEM_WIDE="${INST64_HELM_SYSTEM_WIDE:-YES}"
 # Installation method
-export INST64_HELM_METHOD="${INST64_HELM_METHOD:-BINARY}"
-export INST64_HELM_SOURCE="${INST64_HELM_SOURCE:-https://get.helm.sh}"
+export INST64_HELM_METHOD="${INST64_HELM_METHOD:-CUSTOM}"
+
+export INST64_HELM_PACKAGE_URL=''
+export INST64_HELM_INSTALLER=''
+export INST64_HELM_PACKAGES=''
+export INST64_HELM_CLI_NAME='helm'
+export INST64_HELM_CLI_PATH=''
 
 export INST64_HELM_REPO_NAME='helm'
 export INST64_HELM_REPO_OWNER='helm'
-export INST64_HELM_PACKAGES=''
-export INST64_HELM_CLI_NAME='helm'
-export INST64_HELM_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_HELM_CLI_NAME}"
 
 #
 # Functions
 #
 
-function inst64_helm_install_binary_release() {
+function inst64_helm_install_custom_package() {
   bl64_dbg_app_show_function
   local work_path=''
   local app_target_mode='0755'
   local app_target_owner='root'
-  local app_cli_mode='0755'
   local app_cli_source="${INST64_HELM_CLI_NAME}"
 
+  if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
+    INST64_HELM_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_HELM_CLI_NAME}"
+  else
+    INST64_HELM_CLI_PATH="${INST64_HELM_TARGET}/${INST64_HELM_CLI_NAME}"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
+
   bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  bl64_rxtx_web_get_file \
-    "${INST64_HELM_PACKAGE_URL}/${INST64_HELM_PACKAGES}" "${work_path}/${INST64_HELM_PACKAGES}" &&
+  work_path="$(bl64_fs_create_tmpdir)" &&
+    bl64_rxtx_web_get_file \
+      "${INST64_HELM_PACKAGE_URL}/${INST64_HELM_PACKAGES}" \
+      "${work_path}/${INST64_HELM_PACKAGES}" \
+      'YES' \
+      "$app_target_mode" &&
     bl64_arc_open_tar "${work_path}/${INST64_HELM_PACKAGES}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
-  bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE" || app_target_owner="$BL64_VAR_DEFAULT"
   bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" "${work_path}/${INST64_HELM_PLATFORM}/${app_cli_source}" ||
+    bl64_fs_path_copy "$BL64_VAR_DEFAULT" "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" "${work_path}/${INST64_HELM_PLATFORM}/${app_cli_source}" ||
     return $?
 
   if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
@@ -91,12 +115,32 @@ function inst64_helm_install_binary_release() {
     # shellcheck disable=SC2086
     bl64_fs_create_symlink "${INST64_HELM_TARGET}/${app_cli_source}" "$INST64_HELM_CLI_PATH" "$BL64_VAR_ON" ||
       return $?
-  else
-    INST64_HELM_CLI_PATH="${INST64_HELM_TARGET}/${INST64_HELM_CLI_NAME}"
   fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_helm_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
+    [[ -z "$INST64_HELM_PLATFORM" ]] && INST64_HELM_PLATFORM='linux-amd64'
+  fi
+  [[ -z "$INST64_HELM_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -113,9 +157,8 @@ function inst64_helm_install_binary_release() {
 #######################################
 function inst64_helm_install() {
   bl64_dbg_app_show_function
-  inst64_helm_select_packages || return $?
-  if [[ "$INST64_HELM_METHOD" == 'BINARY' ]]; then
-    inst64_helm_install_binary_release
+  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
+    inst64_helm_install_custom_package
   fi
 }
 
@@ -134,7 +177,7 @@ function inst64_helm_select_packages() {
   bl64_dbg_app_show_function
   local package_prefix=''
   local package_sufix=''
-  if [[ "$INST64_HELM_METHOD" == 'BINARY' ]]; then
+  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
     if [[ "$INST64_HELM_VERSION" == 'latest' ]]; then
       INST64_HELM_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_HELM_REPO_OWNER" "$INST64_HELM_REPO_NAME")" ||
         return $?
@@ -143,6 +186,7 @@ function inst64_helm_select_packages() {
     package_sufix='.tar.gz'
     INST64_HELM_PACKAGES="${package_prefix}${INST64_HELM_VERSION}-${INST64_HELM_PLATFORM}${package_sufix}"
     INST64_HELM_PACKAGE_URL="$INST64_HELM_SOURCE"
+    [[ -z "$INST64_HELM_PACKAGE_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
   fi
   [[ -z "$INST64_HELM_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
@@ -162,7 +206,12 @@ function inst64_helm_select_packages() {
 function inst64_helm_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_arc_setup
+  inst64_helm_select_platform &&
+    inst64_helm_select_packages ||
+    return $?
+  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
+    bl64_arc_setup
+  fi
 }
 
 #######################################
@@ -179,9 +228,7 @@ function inst64_helm_prepare() {
 function inst64_helm_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  if [[ "$INST64_HELM_METHOD" == 'BINARY' ]]; then
-    "${INST64_HELM_CLI_PATH}" version
-  fi
+  "$INST64_HELM_CLI_PATH" version
 }
 
 #######################################
@@ -197,17 +244,29 @@ function inst64_helm_verify() {
 #######################################
 function inst64_helm_initialize() {
   bl64_dbg_app_show_function
-  if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
-    bl64_check_privilege_root ||
-      return $?
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_HELM_METHOD' \
+    "$INST64_HELM_METHOD" \
+    'CUSTOM' ||
+    return $?
+
+  if [[ "$INST64_HELM_METHOD" == 'CUSTOM' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_HELM_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_ALM}" \
+      "${BL64_OS_ALP}" \
+      "${BL64_OS_AMZ}" \
+      "${BL64_OS_CNT}" \
+      "${BL64_OS_DEB}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_RCK}" \
+      "${BL64_OS_RHEL}" \
+      "${BL64_OS_SLES}" \
+      "${BL64_OS_UB}"
   fi
-  bl64_os_check_compatibility \
-    "${BL64_OS_ALP}-3" \
-    "${BL64_OS_UB}-22" \
-    "${BL64_OS_OL}-9" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_HELM_METHOD' \
-      "$INST64_HELM_METHOD" \
-      'BINARY'
 }
 
 #
