real: promote 5.3.0 (#105)

diff --git a/src/install-istioctl b/src/install-istioctl
--- a/src/install-istioctl
+++ b/src/install-istioctl
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: 1.2.0
+# Template: install-github-2.4.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -21,11 +21,28 @@
 declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
 declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-declare INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -37,15 +54,7 @@ declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
 # Install system wide? Requires root privilege
 declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-declare INST64_ISTIOCTL_PLATFORM="${INST64_ISTIOCTL_PLATFORM:-linux-amd64}"
+declare INST64_ISTIOCTL_PLATFORM="${INST64_ISTIOCTL_PLATFORM:-}"
 declare INST64_ISTIOCTL_TARGET="${INST64_ISTIOCTL_TARGET:-}"
 declare INST64_ISTIOCTL_VERSION="${INST64_ISTIOCTL_VERSION:-latest}"
 # Installation method
@@ -53,6 +62,9 @@ declare INST64_ISTIOCTL_METHOD="${INST64_ISTIOCTL_METHOD:-BINARY}"
 
 declare INST64_ISTIOCTL_REPO_NAME='istio'
 declare INST64_ISTIOCTL_REPO_OWNER='istio'
+declare INST64_ISTIOCTL_PACKAGES=''
+declare INST64_ISTIOCTL_CLI_NAME='istioctl'
+declare INST64_ISTIOCTL_CLI_PATH=''
 
 #
 # Functions
@@ -60,39 +72,68 @@ declare INST64_ISTIOCTL_REPO_OWNER='istio'
 
 function inst64_istioctl_install_binary_release() {
   bl64_dbg_app_show_function
-  local package_prefix='istioctl-'
-  local package_sufix='.tar.gz'
-  local package_name=''
   local work_path=''
   local app_target_mode='0755'
-  local app_target_owner='root'
+  local app_target_owner="$BL64_IAM_SYSTEM_USER"
+  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
   local app_cli_mode='0755'
-  local app_cli='istioctl'
+  local app_cli_source="bin/${INST64_ISTIOCTL_CLI_NAME}"
+  local app_work_path="${INST64_ISTIOCTL_REPO_NAME}-${INST64_ISTIOCTL_VERSION#v}"
+
+  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+    app_target_owner="$BL64_VAR_DEFAULT"
+    app_target_group="$BL64_VAR_DEFAULT"
+  fi
 
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
-  if [[ "$INST64_ISTIOCTL_VERSION" == 'latest' ]]; then
-    INST64_ISTIOCTL_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_ISTIOCTL_REPO_OWNER" "$INST64_ISTIOCTL_REPO_NAME")" ||
-      return $?
-  fi
-  package_name="${package_prefix}${INST64_ISTIOCTL_VERSION}-${INST64_ISTIOCTL_PLATFORM}${package_sufix}"
-
-  bl64_rxtx_github_get_asset "$INST64_ISTIOCTL_REPO_OWNER" "$INST64_ISTIOCTL_REPO_NAME" "$INST64_ISTIOCTL_VERSION" "$package_name" "${work_path}/${package_name}" &&
-    bl64_arc_open_tar "${work_path}/${package_name}" "${work_path}" ||
+  bl64_rxtx_github_get_asset \
+    "$INST64_ISTIOCTL_REPO_OWNER" "$INST64_ISTIOCTL_REPO_NAME" "$INST64_ISTIOCTL_VERSION" "$INST64_ISTIOCTL_PACKAGES" "${work_path}/${INST64_ISTIOCTL_PACKAGES}" &&
+    bl64_arc_open_tar "${work_path}/${INST64_ISTIOCTL_PACKAGES}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_ISTIOCTL_TARGET" &&
-    bl64_fs_path_copy "$app_cli_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_ISTIOCTL_TARGET" "${work_path}/${app_cli}" ||
+  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_ISTIOCTL_TARGET" &&
+    bl64_fs_path_copy "$app_cli_mode" "$app_cli_mode" "$app_target_owner" "$app_target_group" "$INST64_ISTIOCTL_TARGET" "${work_path}/${app_work_path}"/* ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_symlink_create "${INST64_ISTIOCTL_TARGET}/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_ISTIOCTL_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_symlink_create "${INST64_ISTIOCTL_TARGET}/${app_cli_source}" "$INST64_ISTIOCTL_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_istioctl_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_ISTIOCTL_METHOD" == 'BINARY' ]]; then
+    if [[ -z "$INST64_ISTIOCTL_PLATFORM" ]]; then
+      # shellcheck disable=SC2249
+      case "$BL64_OS_MACHINE" in
+      "$BL64_OS_MACHINE_ARM64") INST64_ISTIOCTL_PLATFORM='osx-arm64' ;;
+      "$BL64_OS_MACHINE_AMD64") INST64_ISTIOCTL_PLATFORM='linux-amd64' ;;
+      esac
+    fi
+  fi
+  [[ -z "$INST64_ISTIOCTL_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -115,6 +156,75 @@ function inst64_istioctl_install() {
 }
 
 #######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_istioctl_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_ISTIOCTL_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_ISTIOCTL_VERSION" == 'latest' ]]; then
+      INST64_ISTIOCTL_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_ISTIOCTL_REPO_OWNER" "$INST64_ISTIOCTL_REPO_NAME")" ||
+        return $?
+    fi
+    package_prefix='istio-'
+    package_sufix='.tar.gz'
+    INST64_ISTIOCTL_PACKAGES="${package_prefix}${INST64_ISTIOCTL_VERSION#v}-${INST64_ISTIOCTL_PLATFORM}${package_sufix}"
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      INST64_ISTIOCTL_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_ISTIOCTL_CLI_NAME}"
+    else
+      INST64_ISTIOCTL_CLI_PATH="${INST64_ISTIOCTL_TARGET}/${INST64_ISTIOCTL_CLI_NAME}"
+    fi
+  fi
+  [[ -z "$INST64_ISTIOCTL_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  return 0
+}
+#https://github.com/istio/istio/releases/download/1.25.0/istio-1.25.0-linux-armv7.tar.gz
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_istioctl_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  if [[ "$INST64_ISTIOCTL_METHOD" == 'BINARY' ]]; then
+    bl64_arc_setup
+  fi
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_istioctl_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "$INST64_ISTIOCTL_CLI_PATH" version --remote=false
+}
+
+#######################################
 # Initialize environment
 #
 # Arguments:
@@ -134,30 +244,41 @@ function inst64_istioctl_initialize() {
     bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
   fi
   INST64_ISTIOCTL_TARGET="${INST64_ISTIOCTL_TARGET:-${INST64_OPT_ROOT}/istioctl}"
-  bl64_arc_setup &&
-    bl64_os_check_compatibility \
-      "${BL64_OS_UB}-22" \
-      "${BL64_OS_OL}-9" &&
-    bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_ISTIOCTL_METHOD' \
-      "$INST64_ISTIOCTL_METHOD" \
-      'BINARY' &&
-    bl64_check_privilege_root
-  # shellcheck disable=SC2181
-  (($? =! 0)) && return $BL64_LIB_ERROR_TASK_FAILED
+  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_ISTIOCTL_METHOD' \
+    "$INST64_ISTIOCTL_METHOD" \
+    'BINARY' ||
+    return $?
+
+  if [[ "$INST64_ISTIOCTL_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+  fi
+  inst64_istioctl_select_platform &&
+    inst64_istioctl_select_packages ||
+    return $?
   bl64_msg_show_setup 'Install application: IstioCTL' \
-    'INST64_ISTIOCTL_METHOD' 'INST64_SYSTEM_WIDE' 
+    'INST64_SYSTEM_WIDE' 'INST64_ISTIOCTL_METHOD' \
+    'INST64_ISTIOCTL_PLATFORM' \
+    'INST64_ISTIOCTL_REPO_OWNER' \
+    'INST64_ISTIOCTL_REPO_NAME' \
+    'INST64_ISTIOCTL_TARGET' \
+    'INST64_ISTIOCTL_VERSION' \
+    'INST64_ISTIOCTL_CLI_PATH'
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.3.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_istioctl_initialize &&
-  inst64_istioctl_install
-
+  inst64_istioctl_prepare &&
+  inst64_istioctl_install &&
+  inst64_istioctl_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
