refact: upgrade

diff --git a/src/install-lnav b/src/install-lnav
--- a/src/install-lnav
+++ b/src/install-lnav
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
-# Template: 2.0.0
+# Template: 2.2.0
+# Snippet: install-github-release-3.2.1
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.1.0
+# Version: 1.2.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,10 +30,23 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -42,24 +56,19 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-export INST64_LNAV_PLATFORM="${INST64_LNAV_PLATFORM:-x86_64-linux-musl}"
+export INST64_LNAV_PLATFORM="${INST64_LNAV_PLATFORM:-linux-musl-x86_64}"
 export INST64_LNAV_TARGET="${INST64_LNAV_TARGET:-${INST64_OPT_ROOT}/lnav}"
 export INST64_LNAV_VERSION="${INST64_LNAV_VERSION:-latest}"
+# Install system wide? Requires root privilege
+export INST64_LNAV_SYSTEM_WIDE="${INST64_LNAV_SYSTEM_WIDE:-YES}"
 # Installation method
 export INST64_LNAV_METHOD="${INST64_LNAV_METHOD:-BINARY}"
 
-export INST64_LNAV_CLI_NAME='lnav'
 export INST64_LNAV_REPO_NAME='lnav'
 export INST64_LNAV_REPO_OWNER='tstack'
 export INST64_LNAV_PACKAGES=''
+export INST64_LNAV_CLI_NAME='lnav'
+export INST64_LNAV_CLI_PATH=''
 
 #
 # Functions
@@ -71,10 +80,17 @@ function inst64_lnav_install_binary_release() {
   local app_target_mode='0755'
   local app_target_owner='root'
   local app_cli_mode='0755'
+  local app_cli_source="${INST64_LNAV_CLI_NAME}-${INST64_LNAV_VERSION#v}/${INST64_LNAV_CLI_NAME}"
+
+  if bl64_lib_flag_is_enabled "$INST64_LNAV_SYSTEM_WIDE"; then
+    INST64_LNAV_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_LNAV_CLI_NAME}"
+  else
+    INST64_LNAV_CLI_PATH="${INST64_LNAV_TARGET}/${INST64_LNAV_CLI_NAME}"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
 
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
-
   bl64_rxtx_github_get_asset \
     "$INST64_LNAV_REPO_OWNER" "$INST64_LNAV_REPO_NAME" "$INST64_LNAV_VERSION" "$INST64_LNAV_PACKAGES" "${work_path}/${INST64_LNAV_PACKAGES}" &&
     bl64_arc_open_zip "${work_path}/${INST64_LNAV_PACKAGES}" "${work_path}" ||
@@ -82,14 +98,15 @@ function inst64_lnav_install_binary_release() {
 
   bl64_msg_show_task 'deploy application'
   bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_LNAV_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_LNAV_TARGET" \
-      "${work_path}/${INST64_LNAV_CLI_NAME}-${INST64_LNAV_VERSION#v}/${INST64_LNAV_CLI_NAME}" ||
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_LNAV_TARGET" "${work_path}/${app_cli_source}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_LNAV_TARGET}/${INST64_LNAV_CLI_NAME}" "${INST64_LOCAL_BIN}/${INST64_LNAV_CLI_NAME}" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_LNAV_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_LNAV_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_LNAV_TARGET}/${INST64_LNAV_CLI_NAME}" "$INST64_LNAV_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
@@ -113,7 +130,6 @@ function inst64_lnav_install() {
   if [[ "$INST64_LNAV_METHOD" == 'BINARY' ]]; then
     inst64_lnav_install_binary_release
   fi
-
 }
 
 #######################################
@@ -138,10 +154,8 @@ function inst64_lnav_select_packages() {
     fi
     package_prefix='lnav-'
     package_sufix='.zip'
-    # delete-me # Modify the following line to properly form the package name
     INST64_LNAV_PACKAGES="${package_prefix}${INST64_LNAV_VERSION#v}-${INST64_LNAV_PLATFORM}${package_sufix}"
   fi
-
   [[ -z "$INST64_LNAV_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
 }
@@ -160,7 +174,9 @@ function inst64_lnav_select_packages() {
 function inst64_lnav_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_arc_setup
+  if [[ "$INST64_LNAV_METHOD" == 'BINARY' ]]; then
+    bl64_arc_setup
+  fi
 }
 
 #######################################
@@ -177,7 +193,7 @@ function inst64_lnav_prepare() {
 function inst64_lnav_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  "${INST64_LOCAL_BIN}/${INST64_LNAV_CLI_NAME}" --version
+  "$INST64_LNAV_CLI_PATH" --version
 }
 
 #######################################
@@ -193,19 +209,29 @@ function inst64_lnav_verify() {
 #######################################
 function inst64_lnav_initialize() {
   bl64_dbg_app_show_function
-  bl64_os_check_compatibility \
-    "${BL64_OS_OL}-9" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_LNAV_METHOD' \
-      "$INST64_LNAV_METHOD" \
-      'BINARY' &&
-    bl64_check_privilege_root
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_LNAV_METHOD' \
+    "$INST64_LNAV_METHOD" \
+    'BINARY' ||
+    return $?
+
+  if [[ "$INST64_LNAV_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_LNAV_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_ALP}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_UB}"
+  fi
 }
 
 #
 # Main
 #
 
-declare inst64_lnav_installer_description='Install application: LNav'
+declare inst64_lnav_installer_description='Install application: LNav - The Logfile Navigator'
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_lnav_installer_description"
