refact: migrate to bl64

diff --git a/src/install-go b/src/install-go
--- a/src/install-go
+++ b/src/install-go
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.2.0
-# Snippet: install-github-release-3.2.0
+# Template: install-bl64-binary-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,195 +17,164 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_GO_PLATFORM="${INST64_GO_PLATFORM:-linux-amd64}"
-declare INST64_GO_SOURCE="${INST64_GO_SOURCE:-https://go.dev/dl}"
-declare INST64_GO_TARGET="${INST64_GO_TARGET:-}"
-declare INST64_GO_VERSION="${INST64_GO_VERSION:-1.21.2}"
 # Installation method
 declare INST64_GO_METHOD="${INST64_GO_METHOD:-BINARY}"
+# Installation destination
+declare INST64_GO_TARGET="${INST64_GO_TARGET:-}"
+# Hardware architecture
+declare INST64_GO_PLATFORM="${INST64_GO_PLATFORM:-}"
+# Application version
+declare INST64_GO_VERSION="${INST64_GO_VERSION:-latest}"
 
-declare INST64_WEB_REPO_URL=''
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='go'
-declare INST64_CLI_PATH=''
+INST64_APP_NAME='go'
+INST64_APP_ID='GO'
+INST64_APP_FULL_NAME='GO - Go Programming Language'
+INST64_CLI_NAME='go'
+
+INST64_WEB_REPO_URL='https://go.dev'
+INST64_WEB_REPO_PATH='dl'
+INST64_PKG_MAIN_PREFIX='go'
+INST64_PKG_MAIN_SUFFIX='tar.gz'
+INST64_CPU_DARWIN_ARM64='darwin-arm64'
+INST64_CPU_LINUX_AMD64='linux-amd64'
 
 #
 # Functions
 #
 
-function inst64_install_binary() {
+function inst64_select_packages_version() {
   bl64_dbg_app_show_function
-  local work_path=''
-  local app_cli_source="${INST64_CLI_NAME}"
-
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    INST64_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_CLI_NAME}"
+  local package_version=''
+  package_version="$(
+    bl64_api_call \
+      "$INST64_WEB_REPO_URL" \
+      '/VERSION?m=text' \
+      "$BL64_API_METHOD_GET" |
+      bl64_txt_run_grep 'go'
+  )"
+  if [[ -n "$package_version" ]]; then
+    echo "${package_version#go}"
   else
-    INST64_CLI_PATH="${INST64_GO_TARGET}/${INST64_CLI_NAME}"
+    bl64_msg_show_error "Unable to detect package version (${INST64_WEB_REPO_URL})"
+    return $BL64_LIB_ERROR_TASK_FAILED
   fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  bl64_rxtx_web_get_file \
-    "${INST64_WEB_REPO_URL}/${INST64_PKG_MAIN}" "${work_path}/${INST64_PKG_MAIN}" ||
-    return $?
-
-  bl64_msg_show_task 'deploy application'
-  bl64_arc_open_tar "${work_path}/${INST64_PKG_MAIN}" "${INST64_OPT_ROOT}" ||
-    return $?
-
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_msg_show_task "publish application to searchable path (${INST64_CLI_PATH})"
-    # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${INST64_GO_TARGET}/bin/${app_cli_source}" "$INST64_CLI_PATH" "$BL64_VAR_ON" ||
-      return $?
-  fi
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
+function inst64_install_binary() {
+  bl64_dbg_app_show_function
+
+  inst64_lib_task_binary_download &&
+    inst64_lib_web_get_file ||
+    return $?
+
+  inst64_lib_task_deploy
+  inst64_lib_target_open_tar ||
+    return $?
+
+  inst64_lib_task_binary_cleanup
+}
+
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
+    inst64_lib_base_create_path
+  fi
+}
+
 function inst64_install() {
   bl64_dbg_app_show_function
-  inst64_select_packages || return $?
+  inst64_lib_step_install || return 0
   if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
     inst64_install_binary
   fi
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
+function inst64_setup() {
   bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
+  inst64_lib_step_setup || return 0
   if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
-    package_prefix='go'
-    package_suffix='tar.gz'
-    INST64_PKG_MAIN="${package_prefix}${INST64_GO_VERSION}.${INST64_GO_PLATFORM}.${package_suffix}"
-    INST64_WEB_REPO_URL="${INST64_GO_SOURCE}"
-  fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
-    bl64_arc_setup
+    INST64_WORK_PATH_CLI="${INST64_GO_TARGET}/bin/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
 function inst64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_CLI_PATH" version
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" version || return $?
+  if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'BINARY' ||
+    return $?
+  if [[ "$INST64_GO_METHOD" == 'AUTO' ]]; then
+    INST64_GO_METHOD='BINARY'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
+    if [[ -z "$INST64_GO_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_GO_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_GO_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      fi
+    fi
+    inst64_lib_platform_check_cpu
+  fi
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_GO_VERSION" == 'latest' ]]; then
+      INST64_GO_VERSION="$(inst64_select_packages_version)" ||
+        return $?
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_GO_VERSION}.${INST64_GO_PLATFORM}.${INST64_PKG_MAIN_SUFFIX}"
+  fi
+  inst64_lib_package_check_definition
+}
+
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_GO_TARGET="${INST64_GO_TARGET:-${INST64_OPT_ROOT}/go}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_GO_METHOD' \
-    "$INST64_GO_METHOD" \
-    'BINARY' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
   if [[ "$INST64_GO_METHOD" == 'BINARY' ]]; then
@@ -214,30 +182,24 @@ function inst64_initialize() {
       bl64_check_privilege_root ||
         return $?
     fi
-    bl64_os_check_compatibility \
-      "${BL64_OS_ALM}" \
-      "${BL64_OS_ALP}" \
-      "${BL64_OS_CNT}" \
-      "${BL64_OS_DEB}" \
-      "${BL64_OS_FD}" \
-      "${BL64_OS_KL}" \
-      "${BL64_OS_OL}" \
-      "${BL64_OS_RCK}" \
-      "${BL64_OS_RHEL}" \
-      "${BL64_OS_SLES}" \
-      "${BL64_OS_UB}"
+    bl64_arc_setup ||
+      return $?
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: GoLang' \
-    'INST64_GO_METHOD' 'INST64_SYSTEM_WIDE' 
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.4.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -245,5 +207,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
