refactor: upgrade

diff --git a/src/install-installer64 b/src/install-installer64
--- a/src/install-installer64
+++ b/src/install-installer64
@@ -27,9 +27,11 @@ declare INST64_TMP="${INST64_TMP:-/tmp}"
 declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
 # Install system wide? Requires root privilege
 declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
+# Replace if already installed?
+declare INST64_REPLACE_INSTALLED="${INST64_REPLACE_INSTALLED:-NO}"
 
 # shellcheck disable=SC2034
-declare INST64_INSTALLER64_SCRIPT_VERSION='1.1.3'
+declare INST64_INSTALLER64_SCRIPT_VERSION='1.2.0'
 # Installation method
 declare INST64_INSTALLER64_METHOD="${INST64_INSTALLER64_METHOD:-BINARY}"
 # Source repository
@@ -40,15 +42,15 @@ declare INST64_INSTALLER64_TARGET="${INST64_INSTALLER64_TARGET:-}"
 declare INST64_INSTALLER64_VERSION="${INST64_INSTALLER64_VERSION:-latest}"
 
 declare INST64_INSTALLER64_PLATFORM=''
-declare INST64_INSTALLER64_SYSTEM_USER=''
-declare INST64_INSTALLER64_SYSTEM_GROUP=''
-declare INST64_INSTALLER64_DOWNLOAD_TOOL='none'
-declare INST64_INSTALLER64_GH_API='https://api.github.com/repos/automation64/installer64/releases/latest'
+declare INST64_TARGET_SYSTEM_USER=''
+declare INST64_TARGET_SYSTEM_GROUP=''
+declare INST64_WEB_CMD_GET='none'
+declare INST64_GH_API='https://api.github.com/repos/automation64/installer64/releases/latest'
 declare INST64_PKG_MAIN=''
-declare INST64_INSTALLER64_TARGET_MODE_DIR='0755'
-declare INST64_INSTALLER64_TARGET_MODE_FILE='0755'
-
-declare INST64_INSTALLER64_VERSION_FILE=''
+declare INST64_TARGET_MODE_DIR='0755'
+declare INST64_TARGET_MODE_FILE='0755'
+declare INST64_STATUS_FLAG='CONTINUE'
+declare INST64_STATUS_PATH=''
 
 #
 # Functions
@@ -74,17 +76,17 @@ function inst64_installer64_retry() {
 
 function inst64_installer64_fetch_latest_version() {
   # shellcheck disable=SC2249
-  case "$INST64_INSTALLER64_DOWNLOAD_TOOL" in
+  case "$INST64_WEB_CMD_GET" in
   'curl')
-    "$INST64_INSTALLER64_DOWNLOAD_TOOL" \
+    "$INST64_WEB_CMD_GET" \
       -s \
-      "$INST64_INSTALLER64_GH_API" |
+      "$INST64_GH_API" |
       grep '"tag_name":'
     ;;
   'wget')
-    "$INST64_INSTALLER64_DOWNLOAD_TOOL" \
+    "$INST64_WEB_CMD_GET" \
       -q -O- \
-      "$INST64_INSTALLER64_GH_API" |
+      "$INST64_GH_API" |
       grep '"tag_name":'
     ;;
   esac
@@ -104,16 +106,16 @@ function inst64_installer64_download_binary_package() {
   package_url="${INST64_INSTALLER64_SOURCE}/releases/download/${INST64_INSTALLER64_VERSION}/${package_name}"
   echo 'Task: download application'
   # shellcheck disable=SC2249
-  case "$INST64_INSTALLER64_DOWNLOAD_TOOL" in
+  case "$INST64_WEB_CMD_GET" in
   'curl')
-    "$INST64_INSTALLER64_DOWNLOAD_TOOL" \
+    "$INST64_WEB_CMD_GET" \
       -s \
       -L \
       -o "${INST64_TMP}/${package_name}" \
       "$package_url"
     ;;
   'wget')
-    "$INST64_INSTALLER64_DOWNLOAD_TOOL" \
+    "$INST64_WEB_CMD_GET" \
       -q \
       -O "${INST64_TMP}/${package_name}" \
       "$package_url"
@@ -127,11 +129,11 @@ function inst64_installer64_open_binary_package() {
   echo "Task: deploy application (package: ${package_name})"
   [[ -f "${INST64_TMP}/${package_name}" ]] &&
     tar zx -C "$INST64_INSTALLER64_TARGET" -f "${INST64_TMP}/${package_name}" &&
-    chmod "$INST64_INSTALLER64_TARGET_MODE_FILE" "$INST64_INSTALLER64_TARGET"/* ||
+    chmod "$INST64_TARGET_MODE_FILE" "$INST64_INSTALLER64_TARGET"/* ||
     return $?
 
   if [[ "$EUID" == '0' ]]; then
-    chown -R "${INST64_INSTALLER64_SYSTEM_USER}:${INST64_INSTALLER64_SYSTEM_GROUP}" "${INST64_INSTALLER64_TARGET}" ||
+    chown -R "${INST64_TARGET_SYSTEM_USER}:${INST64_TARGET_SYSTEM_GROUP}" "${INST64_INSTALLER64_TARGET}" ||
       return $?
   fi
   rm -f "${INST64_TMP}/${package_name}"
@@ -148,19 +150,6 @@ function inst64_installer64_install_binary() {
   done
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
 inst64_installer64_select_platform() {
   INST64_INSTALLER64_PLATFORM="$(uname -s)"
   [ -z "$INST64_INSTALLER64_PLATFORM" ] && echo 'Error: unable to determine platform id' && return 1
@@ -169,43 +158,14 @@ inst64_installer64_select_platform() {
     return 1
   fi
   if [[ "$INST64_INSTALLER64_PLATFORM" == 'Linux' ]]; then
-    INST64_INSTALLER64_SYSTEM_USER='root'
-    INST64_INSTALLER64_SYSTEM_GROUP='root'
+    INST64_TARGET_SYSTEM_USER='root'
+    INST64_TARGET_SYSTEM_GROUP='root'
   elif [[ "$INST64_INSTALLER64_PLATFORM" == 'Darwin' ]]; then
-    INST64_INSTALLER64_SYSTEM_USER='root'
-    INST64_INSTALLER64_SYSTEM_GROUP='wheel'
+    INST64_TARGET_SYSTEM_USER='root'
+    INST64_TARGET_SYSTEM_GROUP='wheel'
   fi
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_installer64_install() {
-  if [[ "$INST64_INSTALLER64_METHOD" == 'BINARY' ]]; then
-    inst64_installer64_install_binary &&
-      "${INST64_INSTALLER64_TARGET}/install-bashlib64"
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_installer64_select_packages() {
   if [[ "$INST64_INSTALLER64_METHOD" == 'BINARY' ]]; then
     INST64_PKG_MAIN='installer64-scripts.tgz'
@@ -220,61 +180,37 @@ function inst64_installer64_select_packages() {
   return 0
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_installer64_prepare() {
+  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
   echo 'Task: prepare deployment'
   if [[ -n "$INST64_OPT_ROOT" && ! -d "$INST64_OPT_ROOT" ]]; then
     mkdir "$INST64_OPT_ROOT" &&
-      chmod "$INST64_INSTALLER64_TARGET_MODE_DIR" "$INST64_OPT_ROOT" ||
+      chmod "$INST64_TARGET_MODE_DIR" "$INST64_OPT_ROOT" ||
       return $?
   fi
   if [[ ! -d "$INST64_INSTALLER64_TARGET" ]]; then
     mkdir "$INST64_INSTALLER64_TARGET" &&
-      chmod "$INST64_INSTALLER64_TARGET_MODE_DIR" "$INST64_INSTALLER64_TARGET"
+      chmod "$INST64_TARGET_MODE_DIR" "$INST64_INSTALLER64_TARGET"
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_installer64_verify() {
-  echo 'Task: verify deployment'
-  [[ -x "${INST64_INSTALLER64_TARGET}/install-installer64" ]] &&
-    [[ -x "${INST64_INSTALLER64_TARGET}/install-bashlib64" ]] &&
-    echo "$INST64_INSTALLER64_VERSION" >"$INST64_INSTALLER64_VERSION_FILE"
+function inst64_installer64_install() {
+  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
+  if [[ "$INST64_INSTALLER64_METHOD" == 'BINARY' ]]; then
+    inst64_installer64_install_binary &&
+      "${INST64_INSTALLER64_TARGET}/install-bashlib64"
+  fi
 }
 
-#######################################
-# Initialize environment
-# * INST64_SYSTEM_WIDE defaults to YES if there is a previous installation
-# * INST64_INSTALLER64_TARGET defaults to /opt/inst64 if INST64_SYSTEM_WIDE is YES, or to $INST64_HOME otherwise
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: failed to initialize
-#######################################
+function inst64_installer64_verify() {
+  [[ "$INST64_STATUS_FLAG" == 'SKIP' ]] && return 0
+  echo 'Task: verify deployment'
+  [[ -d "${INST64_INSTALLER64_TARGET}" ]] &&
+    [[ -x "${INST64_INSTALLER64_TARGET}/install-installer64" ]] &&
+    [[ -x "${INST64_INSTALLER64_TARGET}/install-bashlib64" ]] &&
+    echo "$INST64_INSTALLER64_VERSION" >"$INST64_STATUS_PATH"
+}
+
 function inst64_installer64_initialize() {
   if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
     if [[ -d '/opt/inst64' ]]; then
@@ -302,9 +238,9 @@ function inst64_installer64_initialize() {
     return 1
 
   if command -v 'curl' >/dev/null 2>&1; then
-    INST64_INSTALLER64_DOWNLOAD_TOOL='curl'
+    INST64_WEB_CMD_GET='curl'
   elif command -v 'wget' >/dev/null 2>&1; then
-    INST64_INSTALLER64_DOWNLOAD_TOOL='wget'
+    INST64_WEB_CMD_GET='wget'
   else
     echo 'Error: no download tool found (curl, wget)'
     return 1
@@ -314,10 +250,19 @@ function inst64_installer64_initialize() {
     echo 'Error: no archive tool found (tar)'
     return 1
   fi
-  INST64_INSTALLER64_VERSION_FILE="${INST64_INSTALLER64_TARGET}/version"
+  INST64_STATUS_PATH="${INST64_INSTALLER64_TARGET}/version"
   inst64_installer64_select_platform &&
     inst64_installer64_select_packages ||
     return $?
+  if [[ -f "$INST64_STATUS_PATH" ]]; then
+    if [[ "${INST64_INSTALLER64_VERSION}" == "$(<"$INST64_STATUS_PATH")" ]]; then
+      if [[ "$INST64_REPLACE_INSTALLED" != 'YES' ]]; then
+        echo "Warning: application already installed. No further action taken. Set INST64_REPLACE_INSTALLED='YES' if replacement is required (current-version: ${INST64_INSTALLER64_VERSION})"
+        INST64_STATUS_FLAG='SKIP'
+        return 0
+      fi
+    fi
+  fi
   echo 'Install application: Installer64'
   echo "  INST64_SYSTEM_WIDE: ${INST64_SYSTEM_WIDE}"
   echo "  INST64_INSTALLER64_METHOD: ${INST64_INSTALLER64_METHOD}"
