refact: migrate to bl64

diff --git a/src/install-docker b/src/install-docker
--- a/src/install-docker
+++ b/src/install-docker
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.3.0
-# Snippet: install-external-package-3.4.1
+# Template: install-bl64-native-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,243 +17,174 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_DOCKER_PLATFORM="${INST64_DOCKER_PLATFORM:-}"
 # Installation method
-declare INST64_DOCKER_METHOD="${INST64_DOCKER_METHOD:-EXTERNAL}"
+declare INST64_DOCKER_METHOD="${INST64_DOCKER_METHOD:-NATIVE}"
+# Installation destination
+declare INST64_DOCKER_TARGET=''
+# Hardware architecture
+declare INST64_DOCKER_PLATFORM=''
+# Application version
+declare INST64_DOCKER_VERSION="${INST64_DOCKER_VERSION:-latest}"
 # Enable development packages?
-declare INST64_DOCKER_DEVELOPMENT="${INST64_DOCKER_DEVELOPMENT:-$BL64_VAR_OFF}"
+declare INST64_DOCKER_DEVELOPMENT="${INST64_DOCKER_DEVELOPMENT:-NO}"
 
-declare INST64_OS_REPO_NAME='docker'
-declare INST64_OS_REPO_SOURCE_APT='https://download.docker.com/linux/ubuntu'
-declare INST64_OS_REPO_KEY_APT='https://download.docker.com/linux/ubuntu/gpg'
-declare INST64_OS_REPO_SOURCE_YUM='https://download.docker.com/linux/fedora'
-declare INST64_OS_REPO_KEY_YUM='https://download.docker.com/linux/fedora/gpg'
+# App information
+INST64_APP_NAME='docker'
+INST64_APP_ID='DOCKER'
+INST64_APP_FULL_NAME='Docker - Container Engine'
+# CLI information
+INST64_CLI_NAME='docker'
 
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='docker'
-declare INST64_CLI_PATH=''
+INST64_OS_REPO_NAME='docker-ce'
+INST64_OS_SOURCE_YUM='https://download.docker.com/linux'
+INST64_OS_SOURCE_APT='https://download.docker.com/linux/ubuntu'
+INST64_OS_REPOSITORY_KEY_YUM='https://download.docker.com/linux/fedora/gpg'
+INST64_OS_REPOSITORY_KEY_APT='https://download.docker.com/linux/ubuntu/gpg'
 
 #
 # Functions
 #
 
-function inst64_add_repository() {
+function inst64_prepare_repository() {
   bl64_dbg_app_show_function
   local repository_url=''
   local repository_key=''
-  local repository_extra_1=''
-  local repository_extra_2=''
+  local repository_apt_suite='mantic'
+  local repository_apt_component='stable'
 
-  if bl64_os_is_distro "${BL64_OS_FD}"; then
-    repository_url="${INST64_OS_REPO_SOURCE_YUM}/\$releasever/\$basearch/stable"
-    repository_key="$INST64_OS_REPO_KEY_YUM"
-  elif bl64_os_is_distro "${BL64_OS_UB}"; then
-    repository_url="${INST64_OS_REPO_SOURCE_APT}"
-    repository_key="$INST64_OS_REPO_KEY_APT"
-    repository_extra_1='mantic'
-    repository_extra_2='stable'
+  if bl64_os_is_flavor "$BL64_OS_FLAVOR_DEBIAN"; then
+    repository_url="${INST64_OS_SOURCE_APT}"
+    repository_key="$INST64_OS_REPOSITORY_KEY_APT"
+  elif bl64_os_is_flavor "$BL64_OS_FLAVOR_FEDORA" ; then
+    repository_url="${INST64_OS_SOURCE_YUM}/fedora/\$releasever/\$basearch/stable"
+    repository_key="$INST64_OS_REPOSITORY_KEY_YUM"
+  elif bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
+    repository_url="${INST64_OS_SOURCE_YUM}/rhel/\$releasever/\$basearch/stable"
+    repository_key="$INST64_OS_REPOSITORY_KEY_YUM"
   fi
 
   bl64_msg_show_task 'Add external package repository'
   bl64_pkg_repository_add "$INST64_OS_REPO_NAME" \
     "$repository_url" "$repository_key" \
-    "$repository_extra_1" "$repository_extra_2"
+    "$repository_apt_suite" "$repository_apt_component"
 }
 
-function inst64_install_external_packages() {
+function inst64_install_native() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'deploy packages'
-  INST64_CLI_PATH="/usr/bin/${INST64_CLI_NAME}"
   # shellcheck disable=SC2086
   bl64_pkg_deploy $INST64_PKG_MAIN
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
-function inst64_select_platform() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_DOCKER_METHOD" == 'EXTERNAL' ]]; then
-      [[ -z "$INST64_DOCKER_PLATFORM" ]] && INST64_DOCKER_PLATFORM='AUTO'
-  fi
-  [[ -z "$INST64_DOCKER_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_DOCKER_METHOD" == 'EXTERNAL' ]]; then
-    inst64_install_external_packages
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_DOCKER_METHOD" == 'EXTERNAL' ]]; then
-    if bl64_os_is_distro "${BL64_OS_UB}"; then
-      INST64_PKG_MAIN='docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin'
-      bl64_lib_flag_is_enabled "$INST64_DOCKER_DEVELOPMENT" &&
-        INST64_PKG_MAIN="${INST64_PKG_MAIN}"
-    elif bl64_os_is_distro "${BL64_OS_FD}"; then
-      INST64_PKG_MAIN='docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin'
-      bl64_lib_flag_is_enabled "$INST64_DOCKER_DEVELOPMENT" &&
-        INST64_PKG_MAIN="${INST64_PKG_MAIN}"
-    fi
-  fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-0
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_prepare() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_DOCKER_METHOD" == 'EXTERNAL' ]]; then
-    inst64_select_platform &&
-      inst64_add_repository &&
-      inst64_select_packages &&
-      bl64_pkg_setup
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
+    inst64_prepare_repository
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
+    inst64_install_native
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+}
+
 function inst64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_CLI_PATH" --version
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'NATIVE' ||
+    return $?
+  if [[ "$INST64_DOCKER_METHOD" == 'AUTO' ]]; then
+    INST64_DOCKER_METHOD='NATIVE'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  return 0
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
+    bl64_lib_flag_is_enabled "$INST64_DOCKER_DEVELOPMENT" &&
+      INST64_PKG_DEV=''
+    INST64_PKG_MAIN='docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin'
+    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
+  fi
+  inst64_lib_package_check_definition
+}
+
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_DOCKER_METHOD' \
-    "$INST64_DOCKER_METHOD" \
-    'EXTERNAL' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
-  if [[ "$INST64_DOCKER_METHOD" == 'EXTERNAL' ]]; then
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
     bl64_check_privilege_root &&
-    bl64_os_check_compatibility \
-      "${BL64_OS_UB}-22" "${BL64_OS_UB}-23" \
-      "${BL64_OS_FD}-40" "${BL64_OS_FD}-41"
+      bl64_os_check_flavor \
+        "$BL64_OS_FLAVOR_DEBIAN" \
+        "$BL64_OS_FLAVOR_FEDORA" \
+        "$BL64_OS_FLAVOR_REDHAT" &&
+      bl64_pkg_setup ||
+      return $?
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Docker' \
-    'INST64_DOCKER_METHOD' 'INST64_SYSTEM_WIDE' 
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.1.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -262,5 +192,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
