feat: add macos (#119)

diff --git a/src/install-hwatch b/src/install-hwatch
--- a/src/install-hwatch
+++ b/src/install-hwatch
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.3.0
-# Snippet: install-github-release-3.2.4
-# Snippet: select-platform-1.0.0
+# Template: install-github-3.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -23,10 +21,12 @@
 declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
 declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 # shellcheck source-path=lib/bl64 disable=SC2015
 source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
@@ -57,7 +57,7 @@ declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
 declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
 
 declare INST64_HWATCH_PLATFORM="${INST64_HWATCH_PLATFORM:-}"
-declare INST64_HWATCH_TARGET="${INST64_HWATCH_TARGET:-}"
+declare INST64_HWATCH_TARGET=''
 declare INST64_HWATCH_VERSION="${INST64_HWATCH_VERSION:-latest}"
 # Installation method
 declare INST64_HWATCH_METHOD="${INST64_HWATCH_METHOD:-BINARY}"
@@ -76,15 +76,14 @@ function inst64_hwatch_install_binary_release() {
   bl64_dbg_app_show_function
   local work_path=''
   local app_target_mode='0755'
-  local app_target_owner='root'
+  local app_target_owner="$BL64_IAM_SYSTEM_USER"
+  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
   local app_cli_mode='0755'
-  local app_cli_source="${INST64_HWATCH_CLI_NAME}"
+  local app_work_path="bin/${INST64_HWATCH_CLI_NAME}"
 
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    INST64_HWATCH_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_HWATCH_CLI_NAME}"
-  else
-    INST64_HWATCH_CLI_PATH="${INST64_HWATCH_TARGET}/${INST64_HWATCH_CLI_NAME}"
+  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
     app_target_owner="$BL64_VAR_DEFAULT"
+    app_target_group="$BL64_VAR_DEFAULT"
   fi
 
   bl64_msg_show_task 'download application'
@@ -95,20 +94,91 @@ function inst64_hwatch_install_binary_release() {
     return $?
 
   bl64_msg_show_task 'deploy application'
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_HWATCH_TARGET" &&
-    bl64_fs_path_copy "$app_cli_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_HWATCH_TARGET" "${work_path}/bin/${app_cli_source}" ||
+  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_HWATCH_TARGET" &&
+    bl64_fs_path_copy "$app_cli_mode" "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_HWATCH_TARGET" "${work_path}/${app_work_path}" ||
     return $?
-
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_msg_show_task "publish application to searchable path (${INST64_HWATCH_CLI_PATH})"
-    # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${INST64_HWATCH_TARGET}/${app_cli_source}" "$INST64_HWATCH_CLI_PATH" "$BL64_VAR_ON" ||
-      return $?
-  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
   return 0
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_hwatch_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  if [[ "$INST64_HWATCH_METHOD" == 'BINARY' ]]; then
+    if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      bl64_bsh_xdg_create "$HOME"
+    fi
+  fi
+}
+
+#######################################
+# Install application packages
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package installer progress and errors
+# Returns:
+#   0: package installed ok
+#   >0: unable to install package
+#######################################
+function inst64_hwatch_install() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_HWATCH_METHOD" == 'BINARY' ]]; then
+    inst64_hwatch_install_binary_release
+  fi
+}
+
+#######################################
+# Perform post installation setup
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Setup progress
+# Returns:
+#   0: setup completed ok
+#   >0: unable to setup
+#######################################
+function inst64_hwatch_setup() {
+  bl64_dbg_app_show_function
+  local app_cli_source=''
+  if [[ "$INST64_HWATCH_METHOD" == 'BINARY' ]]; then
+    app_cli_source="${INST64_HWATCH_TARGET}/${INST64_HWATCH_CLI_NAME}"
+    bl64_msg_show_task "publish application to searchable path (${INST64_HWATCH_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_symlink_create "${app_cli_source}" "$INST64_HWATCH_CLI_PATH" "$BL64_VAR_ON"
+  fi
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_hwatch_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "$INST64_HWATCH_CLI_PATH" --version
 }
 
 #######################################
@@ -127,37 +197,21 @@ function inst64_hwatch_install_binary_release() {
 function inst64_hwatch_select_platform() {
   bl64_dbg_app_show_function
   if [[ "$INST64_HWATCH_METHOD" == 'BINARY' ]]; then
-      if [[ -z "$INST64_HWATCH_PLATFORM" ]]; then
-        if bl64_os_is_distro "${BL64_OS_ALP}"; then
-          INST64_HWATCH_PLATFORM='x86_64-unknown-linux-musl'
-        else
-          INST64_HWATCH_PLATFORM='x86_64-unknown-linux-gnu'
-        fi
+    if [[ -z "$INST64_HWATCH_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_HWATCH_PLATFORM='aarch64-apple-darwin' 
+      elif bl64_os_is_distro "${BL64_OS_ALP}" "${BL64_OS_DEB}" "${BL64_OS_SLES}" "${BL64_OS_UB}"; then
+        INST64_HWATCH_PLATFORM='x86_64-unknown-linux-musl'
+      elif bl64_os_is_distro "${BL64_OS_ALM}" "${BL64_OS_AMZ}" "${BL64_OS_CNT}" "${BL64_OS_FD}" "${BL64_OS_KL}" "${BL64_OS_OL}" "${BL64_OS_RCK}" "${BL64_OS_RHEL}"; then
+        INST64_HWATCH_PLATFORM='x86_64-unknown-linux-gnu'
+      else
+        bl64_msg_show_error "unsupported OS and Machine combination (OS_TYPE:${BL64_OS_TYPE} / MACHINE: ${BL64_OS_MACHINE})"
+        return $BL64_LIB_ERROR_OS_INCOMPATIBLE
       fi
+    fi
   fi
   [[ -z "$INST64_HWATCH_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_hwatch_install() {
-  bl64_dbg_app_show_function
-  inst64_hwatch_select_platform &&
-    inst64_hwatch_select_packages ||
-    return $?
-  if [[ "$INST64_HWATCH_METHOD" == 'BINARY' ]]; then
-    inst64_hwatch_install_binary_release
-  fi
 }
 
 #######################################
@@ -183,46 +237,14 @@ function inst64_hwatch_select_packages() {
     package_prefix='hwatch-'
     package_suffix='.tar.gz'
     INST64_HWATCH_PACKAGES="${package_prefix}${INST64_HWATCH_VERSION}.${INST64_HWATCH_PLATFORM}${package_suffix}"
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      INST64_HWATCH_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_HWATCH_CLI_NAME}"
+    else
+      INST64_HWATCH_CLI_PATH="${INST64_USER_BIN}/${INST64_HWATCH_CLI_NAME}"
+    fi
   fi
   [[ -z "$INST64_HWATCH_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_hwatch_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  inst64_hwatch_select_packages || return $?
-  if [[ "$INST64_HWATCH_METHOD" == 'BINARY' ]]; then
-    bl64_arc_setup
-  fi
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_hwatch_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_HWATCH_CLI_PATH" --version
 }
 
 #######################################
@@ -255,18 +277,28 @@ function inst64_hwatch_initialize() {
       bl64_check_privilege_root ||
         return $?
     fi
+    bl64_arc_setup ||
+      return $?
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
+  inst64_hwatch_select_platform &&
+    inst64_hwatch_select_packages ||
+    return $?
+
   bl64_msg_show_setup 'Install application: HWatch' \
-    'INST64_HWATCH_METHOD' 'INST64_SYSTEM_WIDE' 
+    'INST64_SYSTEM_WIDE' 'INST64_HWATCH_METHOD' \
+    'INST64_HWATCH_PLATFORM' \
+    'INST64_HWATCH_REPO_OWNER' \
+    'INST64_HWATCH_REPO_NAME' \
+    'INST64_HWATCH_TARGET' \
+    'INST64_HWATCH_VERSION' \
+    'INST64_HWATCH_CLI_PATH'
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.1.0'
+bl64_lib_script_version_set '1.2.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -274,5 +306,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_hwatch_initialize &&
   inst64_hwatch_prepare &&
   inst64_hwatch_install &&
+  inst64_hwatch_setup &&
   inst64_hwatch_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
