real: promote 8.6.0

diff --git a/src/install-dotnet b/src/install-dotnet
--- a/src/install-dotnet
+++ b/src/install-dotnet
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-bl64-python-1.2.0
+# Template: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -21,74 +21,91 @@
 declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 [[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-py.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
   { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
 source "${BL64_SCRIPT_PATH}/lib-bl64" ||
-  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
 # Installation method
-declare INST64_MKDOCS_METHOD="${INST64_MKDOCS_METHOD:-AUTO}"
+declare INST64_DOTNET_METHOD="${INST64_DOTNET_METHOD:-AUTO}"
+# Installation destination
+declare INST64_DOTNET_TARGET="${INST64_DOTNET_TARGET:-}"
+# Hardware architecture
+declare INST64_DOTNET_PLATFORM="${INST64_DOTNET_PLATFORM:-}"
 # Application version
-declare INST64_MKDOCS_VERSION="${INST64_MKDOCS_VERSION:-latest}"
+declare INST64_DOTNET_VERSION="${INST64_DOTNET_VERSION:-}"
 
-# App information
-INST64_APP_NAME='mkdocs'
-INST64_APP_ID='MKDOCS'
-INST64_APP_FULL_NAME='MKDocs - Project Documentation Tool'
+INST64_APP_NAME='dotnet'
+INST64_APP_ID='DOTNET'
+INST64_APP_FULL_NAME='DotNet - Microsoft .NET Runtime'
+INST64_APP_DOC_SETUP='https://learn.microsoft.com/en-us/dotnet/core/install/linux'
+INST64_CLI_NAME='dotnet'
 
-INST64_CLI_NAME='mkdocs'
-
-INST64_PKG_MAIN='mkdocs'
-INST64_PKG_POST='Markdown,'
-INST64_PKG_POST+='mdx-truly-sane-lists,'
-INST64_PKG_POST+='mkdocs-autorefs,'
-INST64_PKG_POST+='mkdocs-awesome-pages-plugin,'
-INST64_PKG_POST+='mkdocs-exclude,'
-INST64_PKG_POST+='mkdocs-include-markdown-plugin,'
-INST64_PKG_POST+='mkdocs-markmap,'
-INST64_PKG_POST+='mkdocs-material,'
-INST64_PKG_POST+='mkdocs-mermaid2-plugin,'
-INST64_PKG_POST+='mkdocs-minify-plugin,'
-INST64_PKG_POST+='mkdocstrings,'
-INST64_PKG_POST+='Pygments,'
-INST64_PKG_POST+='pymdown-extensions'
+INST64_WEB_REPO_URL='https://dot.net'
+INST64_WEB_REPO_PATH='v1'
+INST64_APP_INSTALLER='dotnet-install.sh'
+INST64_PKG_MAIN="$INST64_APP_INSTALLER"
 
 #
 # Functions
 #
 
+function my_install_custom() {
+  bl64_dbg_app_show_function
+
+  inst64_lib_task_download
+  inst64_lib_staging_create &&
+    inst64_lib_web_get_file ||
+    return $?
+
+  inst64_lib_task_deploy
+  inst64_lib_installer_run \
+    --install-dir "$INST64_DOTNET_TARGET" \
+    ${INST64_DOTNET_VERSION:+--version "$INST64_DOTNET_VERSION"} ||
+    return $?
+
+  inst64_lib_task_cleanup
+  inst64_lib_staging_remove
+}
+
 function my_prepare() {
   bl64_dbg_app_show_function
   inst64_lib_step_prepare || return 0
+  if [[ "$INST64_DOTNET_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
+    inst64_lib_base_create_path
+  fi
 }
 
 function my_install() {
   bl64_dbg_app_show_function
   inst64_lib_step_install || return 0
-  if [[ "$INST64_MKDOCS_METHOD" == "$INST64_METHOD_PIPX" ]]; then
-    inst64_lib_python_install_pipx
-  elif [[ "$INST64_MKDOCS_METHOD" == "$INST64_METHOD_PIP" ]]; then
-    inst64_lib_python_install_pip
-  elif [[ "$INST64_MKDOCS_METHOD" == "$INST64_METHOD_UV" ]]; then
-    inst64_lib_python_install_uv
+  if [[ "$INST64_DOTNET_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
+    my_install_custom
   fi
 }
 
 function my_setup() {
   bl64_dbg_app_show_function
   inst64_lib_step_setup || return 0
+  if [[ "$INST64_DOTNET_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
+  fi
 }
 
 function my_verify() {
@@ -101,29 +118,19 @@ function my_select_method() {
   bl64_dbg_app_show_function
   inst64_lib_method_check \
     "$INST64_METHOD_AUTO" \
-    "$INST64_METHOD_PIP" "$INST64_METHOD_PIPX" "$INST64_METHOD_UV" ||
+    "$INST64_METHOD_CUSTOM" ||
     return $?
-  if [[ "$INST64_MKDOCS_METHOD" == "$INST64_METHOD_AUTO" ]]; then
-    INST64_MKDOCS_METHOD="$INST64_METHOD_UV"
+  if [[ "$INST64_DOTNET_METHOD" == "$INST64_METHOD_AUTO" ]]; then
+    INST64_DOTNET_METHOD="$INST64_METHOD_CUSTOM"
   fi
 }
 
 function my_select_platform() {
   bl64_dbg_app_show_function
-  return 0
 }
 
 function my_select_packages() {
   bl64_dbg_app_show_function
-  if [[ "$INST64_MKDOCS_METHOD" =~ ("$INST64_METHOD_PIPX"|"$INST64_METHOD_PIP"|"$INST64_METHOD_UV") ]]; then
-    if [[ "$INST64_MKDOCS_VERSION" == 'latest' ]]; then
-      version_target=''
-    else
-      version_target="==${INST64_MKDOCS_VERSION}.*"
-    fi
-    INST64_PKG_MAIN="${INST64_PKG_MAIN}${version_target}"
-  fi
-  inst64_lib_package_check_definition
 }
 
 function my_initialize() {
@@ -143,7 +150,7 @@ function my_initialize() {
 # Main
 #
 
-bl64_lib_script_version_set '4.0.0'
+bl64_lib_script_version_set '1.0.0'
 inst64_lib_base_set_verbosity
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 my_initialize &&
