cosmetic

diff --git a/src/install-terraform b/src/install-terraform
--- a/src/install-terraform
+++ b/src/install-terraform
@@ -29,7 +29,7 @@
 #
 
 # BashLib64 location
-export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64/bashlib64.bash}"
+export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -40,7 +40,8 @@ export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
 export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 
 # shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
-source "$INST64_BASHLIB64" || { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+source "${INST64_BASHLIB64}/bashlib64.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
 
 #
 # Globals
