feat: update OS list

diff --git a/src/install-lazydocker b/src/install-lazydocker
--- a/src/install-lazydocker
+++ b/src/install-lazydocker
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
-# Template: 2.0.0
+# Template: 2.3.0
+# Snippet: install-github-release-3.2.4
+# Snippet: select-platform-1.0.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.2.0
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,10 +31,25 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -42,25 +59,19 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-export INST64_LAZYDOCKER_PLATFORM="${INST64_LAZYDOCKER_PLATFORM:-Linux_x86_64}"
+export INST64_LAZYDOCKER_PLATFORM="${INST64_LAZYDOCKER_PLATFORM:-}"
 export INST64_LAZYDOCKER_TARGET="${INST64_LAZYDOCKER_TARGET:-${INST64_OPT_ROOT}/lazydocker}"
 export INST64_LAZYDOCKER_VERSION="${INST64_LAZYDOCKER_VERSION:-latest}"
+# Install system wide? Requires root privilege
+export INST64_LAZYDOCKER_SYSTEM_WIDE="${INST64_LAZYDOCKER_SYSTEM_WIDE:-YES}"
 # Installation method
 export INST64_LAZYDOCKER_METHOD="${INST64_LAZYDOCKER_METHOD:-BINARY}"
 
 export INST64_LAZYDOCKER_REPO_NAME='lazydocker'
 export INST64_LAZYDOCKER_REPO_OWNER='jesseduffield'
-
 export INST64_LAZYDOCKER_PACKAGES=''
 export INST64_LAZYDOCKER_CLI_NAME='lazydocker'
+export INST64_LAZYDOCKER_CLI_PATH=''
 
 #
 # Functions
@@ -74,6 +85,13 @@ function inst64_lazydocker_install_binary_release() {
   local app_cli_mode='0755'
   local app_cli_source="${INST64_LAZYDOCKER_CLI_NAME}"
 
+  if bl64_lib_flag_is_enabled "$INST64_LAZYDOCKER_SYSTEM_WIDE"; then
+    INST64_LAZYDOCKER_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_LAZYDOCKER_CLI_NAME}"
+  else
+    INST64_LAZYDOCKER_CLI_PATH="${INST64_LAZYDOCKER_TARGET}/${INST64_LAZYDOCKER_CLI_NAME}"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
+
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
   bl64_rxtx_github_get_asset \
@@ -83,16 +101,40 @@ function inst64_lazydocker_install_binary_release() {
 
   bl64_msg_show_task 'deploy application'
   bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" "${work_path}/${app_cli_source}" ||
+    bl64_fs_path_copy "$app_cli_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" "${work_path}/${app_cli_source}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_LAZYDOCKER_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_LAZYDOCKER_CLI_NAME}" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_LAZYDOCKER_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_LAZYDOCKER_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_LAZYDOCKER_TARGET}/${app_cli_source}" "$INST64_LAZYDOCKER_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_lazydocker_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_LAZYDOCKER_METHOD" == 'BINARY' ]]; then
+      [[ -z "$INST64_LAZYDOCKER_PLATFORM" ]] && INST64_LAZYDOCKER_PLATFORM='Linux_x86_64'
+  fi
+  [[ -z "$INST64_LAZYDOCKER_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -109,7 +151,9 @@ function inst64_lazydocker_install_binary_release() {
 #######################################
 function inst64_lazydocker_install() {
   bl64_dbg_app_show_function
-  inst64_lazydocker_select_packages || return $?
+  inst64_lazydocker_select_platform &&
+    inst64_lazydocker_select_packages ||
+    return $?
   if [[ "$INST64_LAZYDOCKER_METHOD" == 'BINARY' ]]; then
     inst64_lazydocker_install_binary_release
   fi
@@ -135,9 +179,9 @@ function inst64_lazydocker_select_packages() {
       INST64_LAZYDOCKER_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_LAZYDOCKER_REPO_OWNER" "$INST64_LAZYDOCKER_REPO_NAME")" ||
         return $?
     fi
-    package_prefix='lazydocker'
+    package_prefix='lazydocker_'
     package_sufix='.tar.gz'
-    INST64_LAZYDOCKER_PACKAGES="${package_prefix}_${INST64_LAZYDOCKER_VERSION:1}_${INST64_LAZYDOCKER_PLATFORM}${package_sufix}"
+    INST64_LAZYDOCKER_PACKAGES="${package_prefix}${INST64_LAZYDOCKER_VERSION:1}_${INST64_LAZYDOCKER_PLATFORM}${package_sufix}"
   fi
   [[ -z "$INST64_LAZYDOCKER_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
@@ -157,7 +201,10 @@ function inst64_lazydocker_select_packages() {
 function inst64_lazydocker_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_arc_setup
+  inst64_lazydocker_select_packages || return $?
+  if [[ "$INST64_LAZYDOCKER_METHOD" == 'BINARY' ]]; then
+    bl64_arc_setup
+  fi
 }
 
 #######################################
@@ -174,7 +221,7 @@ function inst64_lazydocker_prepare() {
 function inst64_lazydocker_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  "${INST64_LOCAL_BIN}/${INST64_LAZYDOCKER_CLI_NAME}" --version
+  "$INST64_LAZYDOCKER_CLI_PATH" --version
 }
 
 #######################################
@@ -186,26 +233,40 @@ function inst64_lazydocker_verify() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_lazydocker_initialize() {
   bl64_dbg_app_show_function
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_LAZYDOCKER_METHOD' \
+    "$INST64_LAZYDOCKER_METHOD" \
+    'BINARY' ||
+    return $?
 
-  bl64_os_check_compatibility \
-      "${BL64_OS_OL}-9" \
-      "${BL64_OS_UB}-22" \
-      "${BL64_OS_ALP}-3" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_LAZYDOCKER_METHOD' \
-      "$INST64_LAZYDOCKER_METHOD" \
-      'BINARY' &&
-    bl64_check_privilege_root
+  if [[ "$INST64_LAZYDOCKER_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_LAZYDOCKER_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_ALM}" \
+      "${BL64_OS_ALP}" \
+      "${BL64_OS_AMZ}" \
+      "${BL64_OS_CNT}" \
+      "${BL64_OS_DEB}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_RCK}" \
+      "${BL64_OS_RHEL}" \
+      "${BL64_OS_SLES}" \
+      "${BL64_OS_UB}"
+  fi
 }
 
 #
 # Main
 #
 
-declare inst64_lazydocker_installer_description='Install application: Lazydocker'
+declare inst64_lazydocker_installer_description='Install application: LazyDocker'
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_lazydocker_installer_description"
