refact: update OS compat

diff --git a/src/install-lazydocker b/src/install-lazydocker
--- a/src/install-lazydocker
+++ b/src/install-lazydocker
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 1.1.0
+# Template: 2.0.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.0.0
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -53,10 +53,48 @@ source "${INST64_BASHLIB64}/bashlib64.bash" ||
 export INST64_LAZYDOCKER_PLATFORM="${INST64_LAZYDOCKER_PLATFORM:-Linux_x86_64}"
 export INST64_LAZYDOCKER_TARGET="${INST64_LAZYDOCKER_TARGET:-${INST64_OPT_ROOT}/lazydocker}"
 export INST64_LAZYDOCKER_VERSION="${INST64_LAZYDOCKER_VERSION:-latest}"
+# Installation method
+export INST64_LAZYDOCKER_METHOD="${INST64_LAZYDOCKER_METHOD:-BINARY}"
+
+export INST64_LAZYDOCKER_REPO_NAME='lazydocker'
+export INST64_LAZYDOCKER_REPO_OWNER='jesseduffield'
+
+export INST64_LAZYDOCKER_PACKAGES=''
+export INST64_LAZYDOCKER_CLI_NAME='lazydocker'
 
 #
 # Functions
 #
+
+function inst64_lazydocker_install_binary_release() {
+  bl64_dbg_app_show_function
+  local work_path=''
+  local app_target_mode='0755'
+  local app_target_owner='root'
+  local app_cli_mode='0755'
+  local app_cli_source="${INST64_LAZYDOCKER_CLI_NAME}"
+
+  bl64_msg_show_task 'download application'
+  work_path="$(bl64_fs_create_tmpdir)" || return $?
+  bl64_rxtx_github_get_asset \
+    "$INST64_LAZYDOCKER_REPO_OWNER" "$INST64_LAZYDOCKER_REPO_NAME" "$INST64_LAZYDOCKER_VERSION" "$INST64_LAZYDOCKER_PACKAGES" "${work_path}/${INST64_LAZYDOCKER_PACKAGES}" &&
+    bl64_arc_open_tar "${work_path}/${INST64_LAZYDOCKER_PACKAGES}" "${work_path}" ||
+    return $?
+
+  bl64_msg_show_task 'deploy application'
+  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" &&
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" "${work_path}/${app_cli_source}" ||
+    return $?
+
+  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
+  # shellcheck disable=SC2086
+  bl64_fs_create_symlink "${INST64_LAZYDOCKER_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_LAZYDOCKER_CLI_NAME}" "$BL64_VAR_ON" ||
+    return $?
+
+  bl64_msg_show_task 'cleanup temporary files'
+  bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
 
 #######################################
 # Install application packages
@@ -71,45 +109,72 @@ export INST64_LAZYDOCKER_VERSION="${INST64_LAZYDOCKER_VERSION:-latest}"
 #######################################
 function inst64_lazydocker_install() {
   bl64_dbg_app_show_function
-  local repo_owner='jesseduffield'
-  local repo_name='lazydocker'
-  local package_prefix='lazydocker'
-  local package_sufix='.tar.gz'
-  local package_name=''
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner='root'
-  local app_cli_mode='0755'
-  local app_cli='lazydocker'
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  if [[ "$INST64_LAZYDOCKER_VERSION" == 'latest' ]]; then
-    INST64_LAZYDOCKER_VERSION="$(bl64_vcs_github_release_get_latest "$repo_owner" "$repo_name")" ||
-      return $?
+  inst64_lazydocker_select_packages || return $?
+  if [[ "$INST64_LAZYDOCKER_METHOD" == 'BINARY' ]]; then
+    inst64_lazydocker_install_binary_release
   fi
-  # ${var:1}
-  # para no mostrar el primer caracter de la version (v0.21.1)
-  package_name="${package_prefix}_${INST64_LAZYDOCKER_VERSION:1}_${INST64_LAZYDOCKER_PLATFORM}${package_sufix}"
+}
 
-  bl64_rxtx_github_get_asset "$repo_owner" "$repo_name" "$INST64_LAZYDOCKER_VERSION" "$package_name" "${work_path}/${package_name}" &&
-    bl64_arc_open_tar "${work_path}/${package_name}" "${work_path}" ||
-    return $?
-
-  bl64_msg_show_task 'deploy application'
-  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_LAZYDOCKER_TARGET" "${work_path}/${app_cli}" ||
-    return $?
-
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_run_ln $BL64_FS_SET_LN_SYMBOLIC "${INST64_LAZYDOCKER_TARGET}/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" ||
-    return $?
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_lazydocker_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_LAZYDOCKER_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_LAZYDOCKER_VERSION" == 'latest' ]]; then
+      INST64_LAZYDOCKER_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_LAZYDOCKER_REPO_OWNER" "$INST64_LAZYDOCKER_REPO_NAME")" ||
+        return $?
+    fi
+    package_prefix='lazydocker'
+    package_sufix='.tar.gz'
+    INST64_LAZYDOCKER_PACKAGES="${package_prefix}_${INST64_LAZYDOCKER_VERSION:1}_${INST64_LAZYDOCKER_PLATFORM}${package_sufix}"
+  fi
+  [[ -z "$INST64_LAZYDOCKER_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
+}
 
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_lazydocker_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  bl64_arc_setup
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_lazydocker_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "${INST64_LOCAL_BIN}/${INST64_LAZYDOCKER_CLI_NAME}" --version
 }
 
 #######################################
@@ -125,9 +190,14 @@ function inst64_lazydocker_install() {
 #######################################
 function inst64_lazydocker_initialize() {
   bl64_dbg_app_show_function
-  bl64_arc_setup &&
-    bl64_os_check_version \
-      "${BL64_OS_OL}-9" &&
+
+  bl64_os_check_version \
+      "${BL64_OS_OL}-9" \
+      "${BL64_OS_UB}-22" \
+      "${BL64_OS_ALP}-3" &&
+    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_LAZYDOCKER_METHOD' \
+      "$INST64_LAZYDOCKER_METHOD" \
+      'BINARY' &&
     bl64_check_privilege_root
 }
 
@@ -136,15 +206,13 @@ function inst64_lazydocker_initialize() {
 #
 
 declare inst64_lazydocker_installer_description='Install application: Lazydocker'
-declare -i inst64_lazydocker_status=0
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_lazydocker_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_lazydocker_initialize &&
-  inst64_lazydocker_install
-inst64_lazydocker_status=$?
-
-bl64_msg_show_batch_finish "$inst64_lazydocker_status" "$inst64_lazydocker_installer_description"
-exit $inst64_lazydocker_status
+  inst64_lazydocker_prepare &&
+  inst64_lazydocker_install &&
+  inst64_lazydocker_verify
+bl64_msg_show_batch_finish $? "$inst64_lazydocker_installer_description"
