real: promote 7.3.0 (#163)

diff --git a/src/install-golangci b/src/install-golangci
--- a/src/install-golangci
+++ b/src/install-golangci
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-bl64-custom-1.1.0
+# Template: install-bl64-binary-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -35,64 +35,51 @@ source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
   { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
 source "${BL64_SCRIPT_PATH}/lib-bl64" ||
-  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
 # Installation method
-declare INST64_BATSCORE_METHOD="${INST64_BATSCORE_METHOD:-CUSTOM}"
+declare INST64_GOLANGCI_METHOD="${INST64_GOLANGCI_METHOD:-BINARY}"
 # Installation destination
-declare INST64_BATSCORE_TARGET="${INST64_BATSCORE_TARGET:-}"
+declare INST64_GOLANGCI_TARGET="${INST64_GOLANGCI_TARGET:-}"
 # Hardware architecture
-declare INST64_BATSCORE_PLATFORM="${INST64_BATSCORE_PLATFORM:-}"
+declare INST64_GOLANGCI_PLATFORM="${INST64_GOLANGCI_PLATFORM:-}"
 # Application version
-declare INST64_BATSCORE_VERSION="${INST64_BATSCORE_VERSION:-latest}"
+declare INST64_GOLANGCI_VERSION="${INST64_GOLANGCI_VERSION:-latest}"
 
-# App information
-INST64_APP_NAME='batscore'
-INST64_APP_ID='BATSCORE'
-INST64_APP_FULL_NAME='Bats Core - Bash Automated Testing System'
-INST64_CLI_NAME='bats'
-INST64_CLI_SUBPATH='bin'
+INST64_APP_NAME='golangci'
+INST64_APP_ID='GOLANGCI'
+INST64_APP_FULL_NAME='GolangCI-Lint - Go linters aggregator'
+INST64_CLI_NAME='golangci-lint'
 
-INST64_GIT_SERVER='https://github.com/bats-core'
-INST64_GIT_BRANCH='master'
-INST64_TARGET_PATH_DEFAULT='bats-core'
-INST64_BATSCORE_TARGET_HELPER='test_helper'
+INST64_GH_REPO_NAME='golangci-lint'
+INST64_GH_REPO_OWNER='golangci'
+INST64_PKG_MAIN_PREFIX='golangci-lint-'
+INST64_PKG_MAIN_SUFFIX='.tar.gz'
+INST64_CPU_DARWIN_ARM64='darwin-arm64'
+INST64_CPU_LINUX_AMD64='linux-amd64'
+INST64_CPU_LINUX_ARM64='linux-arm64'
 
 #
 # Functions
 #
 
-function inst64_install_custom() {
+function inst64_install_binary() {
   bl64_dbg_app_show_function
-  local original_target="$INST64_BATSCORE_TARGET"
 
+  INST64_WORK_PATH_SOURCE="${INST64_PKG_MAIN_PREFIX}${INST64_GOLANGCI_VERSION#v}-${INST64_GOLANGCI_PLATFORM}/${INST64_CLI_NAME}"
   inst64_lib_task_download
-  inst64_lib_staging_create ||
-    return $?
-
-  INST64_GIT_REPO='bats-core' &&
-    inst64_lib_git_get_dir &&
-    INST64_GIT_REPO='bats-support' &&
-    INST64_BATSCORE_TARGET="${original_target}/${INST64_BATSCORE_TARGET_HELPER}/${INST64_GIT_REPO}" &&
-    inst64_lib_target_create &&
-    inst64_lib_git_get_dir &&
-    INST64_GIT_REPO='bats-assert' &&
-    INST64_BATSCORE_TARGET="${original_target}/${INST64_BATSCORE_TARGET_HELPER}/${INST64_GIT_REPO}" &&
-    inst64_lib_target_create &&
-    inst64_lib_git_get_dir &&
-    INST64_GIT_REPO='bats-file' &&
-    INST64_BATSCORE_TARGET="${original_target}/${INST64_BATSCORE_TARGET_HELPER}/${INST64_GIT_REPO}" &&
-    inst64_lib_target_create &&
-    inst64_lib_git_get_dir &&
-    INST64_BATSCORE_TARGET="$original_target" ||
+  inst64_lib_staging_create &&
+    inst64_lib_gh_get_asset &&
+    inst64_lib_staging_open_tar ||
     return $?
 
   inst64_lib_task_deploy
-  inst64_lib_cli_normalize ||
+  inst64_lib_target_create &&
+    inst64_lib_target_populate ||
     return $?
 
   inst64_lib_task_cleanup
@@ -102,7 +89,7 @@ function inst64_install_custom() {
 function my_prepare() {
   bl64_dbg_app_show_function
   inst64_lib_step_prepare || return 0
-  if [[ "$INST64_BATSCORE_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
     inst64_lib_base_create_path
   fi
 }
@@ -110,15 +97,15 @@ function my_prepare() {
 function my_install() {
   bl64_dbg_app_show_function
   inst64_lib_step_install || return 0
-  if [[ "$INST64_BATSCORE_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
-    inst64_install_custom
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
+    inst64_install_binary
   fi
 }
 
 function my_setup() {
   bl64_dbg_app_show_function
   inst64_lib_step_setup || return 0
-  if [[ "$INST64_BATSCORE_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
     inst64_lib_task_publish
     inst64_lib_cli_promote
   fi
@@ -127,28 +114,49 @@ function my_setup() {
 function my_verify() {
   bl64_dbg_app_show_function
   inst64_lib_step_verify || return 0
-  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
 function my_select_method() {
   bl64_dbg_app_show_function
   inst64_lib_app_check_method \
     "$INST64_METHOD_AUTO" \
-    "$INST64_METHOD_CUSTOM" ||
+    "$INST64_METHOD_BINARY" ||
     return $?
-  if [[ "$INST64_BATSCORE_METHOD" == "$INST64_METHOD_AUTO" ]]; then
-    INST64_BATSCORE_METHOD="$INST64_METHOD_CUSTOM"
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_AUTO" ]]; then
+    INST64_GOLANGCI_METHOD="$INST64_METHOD_BINARY"
   fi
 }
 
 function my_select_platform() {
   bl64_dbg_app_show_function
-  return 0
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
+    if [[ -z "$INST64_GOLANGCI_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_GOLANGCI_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_GOLANGCI_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_GOLANGCI_PLATFORM="$INST64_CPU_LINUX_ARM6464"
+      fi
+    fi
+    inst64_lib_platform_check_cpu
+  fi
 }
 
 function my_select_packages() {
   bl64_dbg_app_show_function
-  return 0
+  if [[ "$INST64_GOLANGCI_METHOD" == "$INST64_METHOD_BINARY" ]]; then
+    if [[ "$INST64_GOLANGCI_VERSION" == 'latest' ]]; then
+      INST64_GOLANGCI_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
+        return $?
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_GOLANGCI_VERSION#v}-${INST64_GOLANGCI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
+  fi
+  inst64_lib_package_check_definition
 }
 
 function my_initialize() {
@@ -156,10 +164,6 @@ function my_initialize() {
   my_select_method &&
     inst64_lib_base_initialize ||
     return $?
-
-  if [[ "$INST64_BATSCORE_METHOD" == "$INST64_METHOD_CUSTOM" ]]; then
-    bl64_arc_setup
-  fi
 
   my_select_platform &&
     my_select_packages &&
@@ -174,8 +178,8 @@ function my_initialize() {
 # Main
 #
 
-bl64_lib_script_version_set '3.0.1'
-inst64_lib_base_set_verbosity
+bl64_lib_script_version_set '1.0.0'
+inst64_lib_base_set_verbosity 
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 my_initialize &&
   my_prepare &&
