refact. Upgrade to lib bl64

diff --git a/src/install-dockercli b/src/install-dockercli
--- a/src/install-dockercli
+++ b/src/install-dockercli
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: legacy
-# Template: 1.1.0
+# Template: install-bl64-native-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,119 +17,174 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
 # Installation method
 declare INST64_DOCKER_METHOD="${INST64_DOCKER_METHOD:-NATIVE}"
+# Installation destination
+declare INST64_DOCKER_TARGET='AUTO'
+# Hardware architecture
+declare INST64_DOCKER_PLATFORM='ALL'
+# Application version
+declare INST64_DOCKER_VERSION="${INST64_DOCKER_VERSION:-latest}"
+# Enable development packages?
+declare INST64_DOCKER_DEVELOPMENT="${INST64_DOCKER_DEVELOPMENT:-NO}"
+
+# App information
+INST64_APP_NAME='dockercli'
+INST64_APP_ID='DOCKER'
+INST64_APP_FULL_NAME='Docker CLI'
+INST64_CLI_NAME='docker'
+
+INST64_OS_REPO_NAME='docker'
+INST64_OS_SOURCE_YUM='https://download.docker.com/linux/centos'
+INST64_OS_REPO_KEY_YUM='https://download.docker.com/linux/centos/gpg'
 
 #
 # Functions
 #
 
-function inst64_install_centos() {
-  local repository_name='docker-ce'
-  # shellcheck disable=SC2016
-  local repository_url='https://download.docker.com/linux/centos/$releasever/$basearch/stable'
-  local repository_key='https://download.docker.com/linux/centos/gpg'
-  local packages='docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin'
+function inst64_prepare_repository() {
+  bl64_dbg_app_show_function
+  local repository_url=''
+  local repository_key=''
+  local repository_apt_suite=''
+  local repository_apt_component=''
 
-  bl64_msg_show_task 'Add YUM package repository'
-  bl64_pkg_repository_add "$repository_name" "$repository_url" "$repository_key" ||
-    return $?
+  if bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
+    repository_url="${INST64_OS_SOURCE_YUM}/\$releasever/\$basearch/stable"
+    repository_key="$INST64_OS_REPO_KEY_YUM"
+  fi
 
-  bl64_msg_show_task 'deploy packages'
-  # shellcheck disable=SC2086
-  bl64_pkg_deploy $packages
+  inst64_lib_pkg_repo_add \
+    "$repository_url" "$repository_key" \
+    "$repository_apt_suite" "$repository_apt_component"
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
+function inst64_install_native() {
+  bl64_dbg_app_show_function
+  inst64_lib_pkg_install
+}
+
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
+    inst64_prepare_repository
+  fi
+}
+
 function inst64_install() {
   bl64_dbg_app_show_function
-  if bl64_os_is_distro "${BL64_OS_OL}"; then
-    inst64_install_centos
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
+    inst64_install_native
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return 1
+}
 
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_cleanup_full
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+}
+
+function inst64_verify() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
+}
+
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'NATIVE' ||
+    return $?
+  if [[ "$INST64_DOCKER_METHOD" == 'AUTO' ]]; then
+    INST64_DOCKER_METHOD='NATIVE'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
   return 0
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: failed to initialize
-#######################################
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
+    # shellcheck disable=SC2249
+    case "$BL64_OS_FLAVOR" in
+    "$BL64_OS_FLAVOR_REDHAT")
+      bl64_lib_flag_is_enabled "$INST64_DOCKER_DEVELOPMENT" &&
+        INST64_PKG_DEV=''
+      INST64_PKG_MAIN='docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin'
+      ;;
+    esac
+    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
+  fi
+  inst64_lib_package_check_definition
+}
+
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_DOCKER_METHOD' \
-    "$INST64_DOCKER_METHOD" \
-    'NATIVE' ||
-  bl64_os_check_version "${BL64_OS_OL}-9" &&
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
+    return $?
+
+  if [[ "$INST64_DOCKER_METHOD" == 'NATIVE' ]]; then
     bl64_check_privilege_root &&
-    bl64_pkg_setup
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Docker CLI' \
-    'INST64_DOCKER_METHOD' 'INST64_SYSTEM_WIDE' 
+      bl64_os_check_flavor \
+        "$BL64_OS_FLAVOR_REDHAT" &&
+      bl64_cryp_setup &&
+      bl64_pkg_setup ||
+      return $?
+  fi
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.1.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_initialize &&
-  inst64_install
+  inst64_prepare &&
+  inst64_install &&
+  inst64_setup &&
+  inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
