real: promote 6.0.10 (#132)

diff --git a/src/install-bashit b/src/install-bashit
--- a/src/install-bashit
+++ b/src/install-bashit
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Snippet: install-git-repo-1.0.1
-# Template: 2.3.0
+# Template: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,199 +17,153 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_GIT_SERVER="${INST64_GIT_SERVER:-https://github.com/Bash-it}"
-declare INST64_GIT_REPO="${INST64_GIT_REPO:-bash-it.git}"
-declare INST64_BASHIT_TARGET="${INST64_BASHIT_TARGET:-}"
-declare INST64_GIT_BRANCH="${INST64_GIT_BRANCH:-master}"
 # Installation method
-declare INST64_BASHIT_METHOD="${INST64_BASHIT_METHOD:-GIT}"
+declare INST64_BASHIT_METHOD="${INST64_BASHIT_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_BASHIT_TARGET="${HOME}/.bashit"
+# Hardware architecture
+declare INST64_BASHIT_PLATFORM="${INST64_BASHIT_PLATFORM:-}"
+# Application version
+declare INST64_BASHIT_VERSION="${INST64_BASHIT_VERSION:-latest}"
 
-declare INST64_APP_INSTALLER=''
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='bash_it.sh'
-declare INST64_CLI_PATH=''
+INST64_APP_NAME='bashit'
+INST64_APP_ID='BASHIT'
+INST64_APP_FULL_NAME='BashIt - Bash Framework'
+INST64_CLI_NAME='install.sh'
+
+INST64_GIT_SERVER='https://github.com/Bash-it'
+INST64_GIT_REPO='bash-it.git'
+INST64_GIT_BRANCH='master'
+INST64_SYSTEM_WIDE='NO'
+INST64_APP_INSTALLER='install.sh'
 
 #
 # Functions
 #
 
-function inst64_install_git_repo() {
+function inst64_install_custom() {
   bl64_dbg_app_show_function
-  local app_target_mode='0755'
 
-  INST64_CLI_PATH="${INST64_BASHIT_TARGET}/${INST64_CLI_NAME}"
-  bl64_msg_show_task 'download application'
-  bl64_rxtx_git_get_dir \
-    "${INST64_GIT_SERVER}/${INST64_GIT_REPO}" \
-    '.' \
-    "$INST64_BASHIT_TARGET" \
-    "$BL64_VAR_ON" \
-    "$INST64_GIT_BRANCH" ||
+  inst64_lib_task_binary_download &&
+    inst64_lib_git_get_dir ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_fs_path_permission_set "$app_target_mode" "$app_target_mode" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_ON" \
-      "$INST64_BASHIT_TARGET" ||
+  inst64_lib_task_deploy
+  inst64_lib_target_normalize &&
+    inst64_lib_cli_normalize &&
+    "${INST64_BASHIT_TARGET}/${INST64_APP_INSTALLER}" \
+    --silent \
+    --overwrite-backup ||
+    return $?
+
+  inst64_lib_task_binary_cleanup
+}
+
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_base_create_path
+  fi
+}
+
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
+    inst64_install_custom
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
+    INST64_WORK_PATH_CLI="${INST64_BASHIT_TARGET}/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
+  fi
+}
+
+function inst64_verify() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_verify || return 0
+  [[ "$INST64_BASHIT_TARGET" ]]
+}
+
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'CUSTOM' ||
+    return $?
+  if [[ "$INST64_BASHIT_METHOD" == 'AUTO' ]]; then
+    INST64_BASHIT_METHOD='CUSTOM'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  return 0
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  return 0
+}
+
+function inst64_initialize() {
+  bl64_dbg_app_show_function
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
+    return $?
+
+  if [[ "$INST64_BASHIT_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_app_check_mode_user &&
+      bl64_check_privilege_not_root &&
+      bl64_arc_setup ||
       return $?
   fi
 
-  return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_BASHIT_METHOD" == 'GIT' ]]; then
-    inst64_install_git_repo
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_BASHIT_METHOD" == 'GIT' ]]; then
-    INST64_PKG_MAIN="$INST64_GIT_REPO"
-  fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  inst64_select_packages || return $?
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_CLI_PATH" --help
-}
-
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
-function inst64_initialize() {
-  bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    INST64_SYSTEM_WIDE='NO'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_BASHIT_TARGET="${INST64_BASHIT_TARGET:-${HOME}/.bash_it}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_BASHIT_METHOD' \
-    "$INST64_BASHIT_METHOD" \
-    'GIT' ||
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
 
-  bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && bl64_msg_show_error 'system-wide installation not supported' &&
-    return $BL64_LIB_ERROR_PARAMETER_INVALID
-
-  if [[ "$INST64_BASHIT_METHOD" == 'GIT' ]]; then
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      bl64_check_privilege_root ||
-        return $?
-    fi
-  fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Bash-it' \
-    'INST64_BASHIT_METHOD' 'INST64_SYSTEM_WIDE' 
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.2.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -218,5 +171,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
diff --git a/src/install-krew b/src/install-krew
--- a/src/install-krew
+++ b/src/install-krew
@@ -1,8 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.3.0
-# Snippet: install-custom-package-4.2.0
-# Snippet: select-platform-1.0.0
-# Snippet: setup-environment-2.0.0
+# Template: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -20,277 +17,173 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_KREW_PLATFORM="${INST64_KREW_PLATFORM:-}"
-declare INST64_KREW_TARGET="${INST64_KREW_TARGET:-}"
-declare INST64_KREW_VERSION="${INST64_KREW_VERSION:-latest}"
 # Installation method
 declare INST64_KREW_METHOD="${INST64_KREW_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_KREW_TARGET="${HOME}/.krew/bin"
+# Hardware architecture
+declare INST64_KREW_PLATFORM="${INST64_KREW_PLATFORM:-}"
+# Application version
+declare INST64_KREW_VERSION="${INST64_KREW_VERSION:-latest}"
 
-declare INST64_KREW_ENV='kubectl-krew.env'
-declare INST64_GH_REPO_NAME='krew'
-declare INST64_GH_REPO_OWNER='kubernetes-sigs'
-declare INST64_APP_INSTALLER=''
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='kubectl-krew'
-declare INST64_CLI_PATH=''
+INST64_APP_NAME='krew'
+INST64_APP_ID='KREW'
+INST64_APP_FULL_NAME='Krew - Kubernetes CLI Plugin Manager'
+INST64_CLI_NAME='kubectl-krew'
+
+INST64_GH_REPO_NAME='krew'
+INST64_GH_REPO_OWNER='kubernetes-sigs'
+INST64_PKG_MAIN_PREFIX='krew-'
+INST64_PKG_MAIN_SUFFIX='.tar.gz'
+INST64_CPU_DARWIN_ARM64='darwin_arm64'
+INST64_CPU_LINUX_AMD64='linux_amd64'
 
 #
 # Functions
 #
 
-#######################################
-# Perform post installation setup
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Setup progress
-# Returns:
-#   0: setup completed ok
-#   >0: unable to setup
-#######################################
+function inst64_install_custom() {
+  bl64_dbg_app_show_function
+
+  inst64_lib_task_binary_download &&
+    inst64_lib_gh_get_asset &&
+    inst64_lib_staging_open_tar ||
+    return $?
+
+  inst64_lib_task_deploy
+  "${INST64_WORK_PATH_STAGING}/${INST64_APP_INSTALLER}" \
+    install krew ||
+    return $?
+
+  inst64_lib_task_binary_cleanup
+}
+
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_base_create_path
+  fi
+}
+
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    inst64_install_custom
+  fi
+}
+
 function inst64_setup() {
   bl64_dbg_app_show_function
-  local mode='0644'
-
-  bl64_msg_show_task 'setup application environment'
-  INST64_KREW_ENV="${BL64_BSH_XDG_PATH_BIN}/${INST64_KREW_ENV}"
-  bl64_msg_show_subtask "create shell env file (${INST64_KREW_ENV})"
-  # shellcheck disable=SC2016
-  printf '#!/usr/bin/env sh
-#
-# Krew
-#
-# * Define application environment variables
-#
-
-KREW_ROOT="$HOME/.krew"
-export KREW_ROOT
-
-PATH="$PATH:$KREW_ROOT/bin"
-' >"$INST64_KREW_ENV" &&
-    bl64_fs_run_chmod "$mode" "$INST64_KREW_ENV" ||
-    return $?
-
-  if bl64_bsh_env_store_is_present; then
-    bl64_bsh_env_store_publish "$INST64_KREW_ENV" ||
-      return $?
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    INST64_WORK_PATH_CLI="${INST64_KREW_TARGET}/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
   fi
-  return 0
 }
 
-function inst64_install_custom_package() {
+function inst64_verify() {
   bl64_dbg_app_show_function
-  local work_path=''
-
-  INST64_CLI_PATH="${HOME}/.krew/bin/${INST64_CLI_NAME}"
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  bl64_rxtx_github_get_asset \
-    "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_KREW_VERSION" "$INST64_PKG_MAIN" "${work_path}/${INST64_PKG_MAIN}" &&
-    bl64_arc_open_tar "${work_path}/${INST64_PKG_MAIN}" "${work_path}" ||
-    return $?
-
-  bl64_msg_show_task 'deploy application'
-  "${work_path}/${INST64_APP_INSTALLER}" install krew ||
-    return $?
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_step_verify || return 0
+  KREW_ROOT="$HOME/.krew" "${INST64_CLI_PATH}/${INST64_CLI_NAME}" \
+    version || return $?
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'CUSTOM' ||
+    return $?
+  if [[ "$INST64_KREW_METHOD" == 'AUTO' ]]; then
+    INST64_KREW_METHOD='CUSTOM'
+  fi
+}
+
 function inst64_select_platform() {
   bl64_dbg_app_show_function
   if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
-    [[ -z "$INST64_KREW_PLATFORM" ]] && INST64_KREW_PLATFORM='linux_amd64'
-  fi
-  [[ -z "$INST64_KREW_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
-    inst64_install_custom_package
+    if [[ -z "$INST64_KREW_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_KREW_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_KREW_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      fi
+    fi
+    inst64_lib_platform_check_cpu
   fi
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_select_packages() {
   bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
   if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
     if [[ "$INST64_KREW_VERSION" == 'latest' ]]; then
       INST64_KREW_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
         return $?
     fi
-    package_prefix='krew-'
-    package_suffix='.tar.gz'
-    INST64_PKG_MAIN="${package_prefix}${INST64_KREW_PLATFORM}${package_suffix}"
-    INST64_APP_INSTALLER="${package_prefix}${INST64_KREW_PLATFORM}"
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_KREW_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
+    INST64_APP_INSTALLER="${INST64_PKG_MAIN_PREFIX}${INST64_KREW_PLATFORM}"
   fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  inst64_select_platform &&
-    inst64_select_packages ||
-    return $?
-  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
-    bl64_arc_setup
-  fi
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  # shellcheck disable=SC1090
-  source "$INST64_KREW_ENV" &&
-    "$INST64_CLI_PATH" version
-}
-
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_KREW_TARGET="${INST64_KREW_TARGET:-${INST64_OPT_ROOT}/krew}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_KREW_METHOD' \
-    "$INST64_KREW_METHOD" \
-    'CUSTOM' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
   if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
-    bl64_check_privilege_not_root &&
+    inst64_lib_app_check_mode_user &&
+      bl64_check_privilege_not_root &&
       bl64_arc_setup ||
       return $?
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Krew' \
-    'INST64_KREW_METHOD' 'INST64_SYSTEM_WIDE' 
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '2.1.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
diff --git a/src/install-ohmyzsh b/src/install-ohmyzsh
--- a/src/install-ohmyzsh
+++ b/src/install-ohmyzsh
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.3.0
-# Snippet: install-custom-package-4.2.0
+# Template: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,209 +17,150 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_OHMYZSH_PLATFORM=''
-declare INST64_OHMYZSH_SOURCE="${INST64_OHMYZSH_SOURCE:-https://raw.github.com/ohmyzsh/ohmyzsh/master/tools}"
-declare INST64_OHMYZSH_TARGET="${INST64_OHMYZSH_TARGET:-}"
-declare INST64_OHMYZSH_VERSION=''
 # Installation method
 declare INST64_OHMYZSH_METHOD="${INST64_OHMYZSH_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_OHMYZSH_TARGET="${INST64_OHMYZSH_TARGET:-}"
+# Hardware architecture
+declare INST64_OHMYZSH_PLATFORM="${INST64_OHMYZSH_PLATFORM:-}"
+# Application version
+declare INST64_OHMYZSH_VERSION="${INST64_OHMYZSH_VERSION:-latest}"
 
-declare INST64_WEB_REPO_URL=''
-declare INST64_APP_INSTALLER='install.sh'
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='oh-my-zsh.sh'
-declare INST64_CLI_PATH=''
+INST64_APP_NAME='ohmyzsh'
+INST64_APP_ID='OHMYZSH'
+INST64_APP_FULL_NAME='Oh-My-ZSH - ZSH Framework'
+INST64_CLI_NAME='oh-my-zsh.sh'
+INST64_CLI_PATH="${HOME}/.oh-my-zsh"
+
+INST64_WEB_REPO_URL='https://raw.github.com'
+INST64_WEB_REPO_PATH='ohmyzsh/ohmyzsh/master/tools'
+INST64_APP_INSTALLER='install.sh'
 
 #
 # Functions
 #
 
-function inst64_install_custom_package() {
+function inst64_install_custom() {
   bl64_dbg_app_show_function
-  local work_path=''
-  local app_target_mode='0755'
 
-  INST64_CLI_PATH="${INST64_OHMYZSH_TARGET}/${INST64_CLI_NAME}"
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" &&
-    bl64_rxtx_web_get_file \
-      "${INST64_WEB_REPO_URL}/${INST64_PKG_MAIN}" \
-      "${work_path}/${INST64_PKG_MAIN}" \
-      'YES' \
-      "$app_target_mode" ||
+  inst64_lib_task_binary_download &&
+    inst64_lib_web_get_file ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  "${work_path}/${INST64_APP_INSTALLER}" --unattended ||
+  inst64_lib_task_deploy
+  "${INST64_WORK_PATH_STAGING}/${INST64_APP_INSTALLER}" \
+    --unattended ||
     return $?
 
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_OHMYZSH_METHOD" == 'CUSTOM' ]]; then
-    inst64_install_custom_package
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
-  bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
-  if [[ "$INST64_OHMYZSH_METHOD" == 'CUSTOM' ]]; then
-    package_prefix="$INST64_APP_INSTALLER"
-    package_suffix=''
-    INST64_PKG_MAIN="${package_prefix}${package_suffix}"
-    INST64_WEB_REPO_URL="${INST64_OHMYZSH_SOURCE}"
-    [[ -z "$INST64_WEB_REPO_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
-  fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_prepare() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  inst64_select_packages ||
-    return $?
+  inst64_lib_step_prepare || return 0
   if [[ "$INST64_OHMYZSH_METHOD" == 'CUSTOM' ]]; then
-    bl64_arc_setup
+    inst64_lib_base_create_path
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_OHMYZSH_METHOD" == 'CUSTOM' ]]; then
+    inst64_install_custom
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  return 0
+}
+
 function inst64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  [[ -f "$INST64_CLI_PATH" ]]
+  inst64_lib_step_verify || return 0
+  [[ -d "${INST64_CLI_PATH}" ]] &&
+    [[ -f "${INST64_CLI_PATH}/${INST64_CLI_NAME}" ]]
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
-function inst64_initialize() {
+function inst64_select_method() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    INST64_SYSTEM_WIDE='NO'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_OHMYZSH_TARGET="${INST64_OHMYZSH_TARGET:-${HOME}/.oh-my-zsh}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_OHMYZSH_METHOD' \
-    "$INST64_OHMYZSH_METHOD" \
+  inst64_lib_app_check_method \
+    'AUTO' \
     'CUSTOM' ||
     return $?
+  if [[ "$INST64_OHMYZSH_METHOD" == 'AUTO' ]]; then
+    INST64_OHMYZSH_METHOD='CUSTOM'
+  fi
+}
 
-  bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && bl64_msg_show_error 'system-wide installation not supported' &&
-    return $BL64_LIB_ERROR_PARAMETER_INVALID
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  return 0
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_OHMYZSH_METHOD" == 'CUSTOM' ]]; then
+    INST64_PKG_MAIN="$INST64_APP_INSTALLER"
+  fi
+  inst64_lib_package_check_definition
+}
+
+function inst64_initialize() {
+  bl64_dbg_app_show_function
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
+    return $?
 
   if [[ "$INST64_OHMYZSH_METHOD" == 'CUSTOM' ]]; then
-    bl64_check_privilege_not_root &&
-      bl64_check_command_search_path 'zsh'
+    inst64_lib_app_check_mode_user &&
+      bl64_check_privilege_not_root &&
+      bl64_check_command_search_path 'zsh' &&
+      bl64_arc_setup ||
+      return $?
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Oh-My-ZSH' \
-    'INST64_OHMYZSH_METHOD' 'INST64_SYSTEM_WIDE' 
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.2.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -228,5 +168,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
diff --git a/src/install-yazi b/src/install-yazi
--- a/src/install-yazi
+++ b/src/install-yazi
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-github-3.0.0
-#   Skeleton: installer-base-2.4.0
+# Template: install-bl64-binary-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,11 +17,9 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
 source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
@@ -36,40 +33,36 @@ source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_YAZI_PLATFORM="${INST64_YAZI_PLATFORM:-}"
-declare INST64_YAZI_TARGET=''
-declare INST64_YAZI_VERSION="${INST64_YAZI_VERSION:-latest}"
 # Installation method
 declare INST64_YAZI_METHOD="${INST64_YAZI_METHOD:-BINARY}"
+# Installation destination
+declare INST64_YAZI_TARGET="${INST64_YAZI_TARGET:-}"
+# Hardware architecture
+declare INST64_YAZI_PLATFORM="${INST64_YAZI_PLATFORM:-}"
+# Application version
+declare INST64_YAZI_VERSION="${INST64_YAZI_VERSION:-latest}"
 
-declare INST64_GH_REPO_NAME='yazi'
-declare INST64_GH_REPO_OWNER='sxyazi'
-declare INST64_PKG_MAIN=''
-declare INST64_YAZI_CLI_NAME_YAZI='yazi'
-declare INST64_YAZI_CLI_NAME_YA='ya'
-declare INST64_YAZI_CLI_PATH_YAZI=''
-declare INST64_YAZI_CLI_PATH_YA=''
+INST64_APP_NAME='yazi'
+INST64_APP_ID='YAZI'
+INST64_APP_FULL_NAME='Yazi - A modern file manager'
+INST64_CLI_NAME='yazi'
+
+INST64_GH_REPO_NAME='yazi'
+INST64_GH_REPO_OWNER='sxyazi'
+INST64_PKG_MAIN_PREFIX='yazi-'
+INST64_PKG_MAIN_SUFFIX='.zip'
+INST64_CPU_DARWIN_ARM64='aarch64-apple-darwin'
+INST64_CPU_LINUX_AMD64_GNU='x86_64-unknown-linux-gnu'
+INST64_CPU_LINUX_AMD64_MUSL='x86_64-unknown-linux-musl'
 
 #
 # Functions
@@ -77,204 +70,109 @@ declare INST64_YAZI_CLI_PATH_YA=''
 
 function inst64_install_binary() {
   bl64_dbg_app_show_function
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner="$BL64_IAM_SYSTEM_USER"
-  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
-  local app_cli_mode='0755'
-  local app_work_path="${INST64_YAZI_CLI_NAME_YAZI}-${INST64_YAZI_PLATFORM}"
 
-  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    app_target_owner="$BL64_VAR_DEFAULT"
-    app_target_group="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  bl64_rxtx_github_get_asset \
-    "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_YAZI_VERSION" "$INST64_PKG_MAIN" "${work_path}/${INST64_PKG_MAIN}" &&
-    bl64_arc_open_zip "${work_path}/${INST64_PKG_MAIN}" "${work_path}" ||
+  INST64_WORK_PATH_SOURCE="${INST64_CLI_NAME}-${INST64_YAZI_PLATFORM}"
+  inst64_lib_task_binary_download &&
+    inst64_lib_gh_get_asset &&
+    inst64_lib_staging_open_zip ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_YAZI_TARGET" &&
-    bl64_fs_path_copy "$app_cli_mode" "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_YAZI_TARGET" \
-      "${work_path}/${app_work_path}/${INST64_YAZI_CLI_NAME_YAZI}" "${work_path}/${app_work_path}/${INST64_YAZI_CLI_NAME_YA}" ||
+  inst64_lib_task_deploy
+  inst64_lib_target_create &&
+    bl64_fs_path_copy "$INST64_CLI_MODE" "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" \
+      "$INST64_YAZI_TARGET" \
+      "${INST64_WORK_PATH_STAGING}/${INST64_WORK_PATH_SOURCE}/${INST64_CLI_NAME}" \
+      "${INST64_WORK_PATH_STAGING}/${INST64_WORK_PATH_SOURCE}/ya" ||
     return $?
 
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_prepare() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
+    inst64_lib_base_create_path
+  fi
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
 function inst64_install() {
   bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
   if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
     inst64_install_binary
   fi
 }
 
-#######################################
-# Perform post installation setup
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Setup progress
-# Returns:
-#   0: setup completed ok
-#   >0: unable to setup
-#######################################
 function inst64_setup() {
   bl64_dbg_app_show_function
-  local app_cli_source=''
+  inst64_lib_step_setup || return 0
   if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      app_cli_source="${INST64_YAZI_TARGET}"
-      bl64_msg_show_task "publish application to searchable path (${INST64_YAZI_CLI_PATH_YAZI})"
-      # shellcheck disable=SC2086
-      bl64_fs_symlink_create "${app_cli_source}/${INST64_YAZI_CLI_NAME_YAZI}" "$INST64_YAZI_CLI_PATH_YAZI" "$BL64_VAR_ON" &&
-        bl64_fs_symlink_create "${app_cli_source}/${INST64_YAZI_CLI_NAME_YA}" "$INST64_YAZI_CLI_PATH_YA" "$BL64_VAR_ON" ||
-        return $?
-    fi
+    INST64_WORK_PATH_CLI="${INST64_YAZI_TARGET}/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    inst64_lib_cli_promote &&
+      bl64_fs_symlink_create "${INST64_WORK_PATH_CLI}" "${INST64_CLI_PATH}/ya" "$BL64_VAR_ON"
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
 function inst64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_YAZI_CLI_PATH_YAZI" --version
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
+  if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'BINARY' ||
+    return $?
+  if [[ "$INST64_YAZI_METHOD" == 'AUTO' ]]; then
+    INST64_YAZI_METHOD='BINARY'
+  fi
+}
+
 function inst64_select_platform() {
   bl64_dbg_app_show_function
   if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
     if [[ -z "$INST64_YAZI_PLATFORM" ]]; then
       if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
-        INST64_YAZI_PLATFORM='aarch64-apple-darwin'
-      elif bl64_os_is_distro "${BL64_OS_ALP}" "${BL64_OS_DEB}" "${BL64_OS_SLES}" "${BL64_OS_UB}"; then
-        INST64_YAZI_PLATFORM='x86_64-unknown-linux-musl'
-      elif bl64_os_is_distro "${BL64_OS_ALM}" "${BL64_OS_AMZ}" "${BL64_OS_CNT}" "${BL64_OS_FD}" "${BL64_OS_KL}" "${BL64_OS_OL}" "${BL64_OS_RCK}" "${BL64_OS_RHEL}"; then
-        INST64_YAZI_PLATFORM='x86_64-unknown-linux-gnu'
-      else
-        bl64_msg_show_error "unsupported OS and Machine combination (OS_TYPE:${BL64_OS_TYPE} / MACHINE: ${BL64_OS_MACHINE})"
-        return $BL64_LIB_ERROR_OS_INCOMPATIBLE
+        INST64_YAZI_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        # shellcheck disable=SC2249
+        case "$BL64_OS_FLAVOR" in
+        "$BL64_OS_FLAVOR_ALPINE" | "$BL64_OS_FLAVOR_DEBIAN" | "$BL64_OS_FLAVOR_SUSE")
+          INST64_YAZI_PLATFORM="$INST64_CPU_LINUX_AMD64_MUSL"
+          ;;
+        "$BL64_OS_FLAVOR_FEDORA" | "$BL64_OS_FLAVOR_REDHAT")
+          INST64_YAZI_PLATFORM="$INST64_CPU_LINUX_AMD64_GNU"
+          ;;
+        esac
       fi
     fi
+    inst64_lib_platform_check_cpu
   fi
-  [[ -z "$INST64_YAZI_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_select_packages() {
   bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
   if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
     if [[ "$INST64_YAZI_VERSION" == 'latest' ]]; then
       INST64_YAZI_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
         return $?
     fi
-    package_prefix='yazi-'
-    package_suffix='.zip'
-    INST64_PKG_MAIN="${package_prefix}${INST64_YAZI_PLATFORM}${package_suffix}"
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_YAZI_CLI_PATH_YAZI="${INST64_LOCAL_BIN}/${INST64_YAZI_CLI_NAME_YAZI}"
-      INST64_YAZI_CLI_PATH_YA="${INST64_LOCAL_BIN}/${INST64_YAZI_CLI_NAME_YA}"
-    else
-      INST64_YAZI_CLI_PATH_YAZI="${INST64_YAZI_TARGET}/${INST64_YAZI_CLI_NAME_YAZI}"
-      INST64_YAZI_CLI_PATH_YA="${INST64_YAZI_TARGET}/${INST64_YAZI_CLI_NAME_YA}"
-    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_YAZI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
   fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_YAZI_TARGET="${INST64_YAZI_TARGET:-${INST64_OPT_ROOT}/yazi}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_YAZI_METHOD' \
-    "$INST64_YAZI_METHOD" \
-    'BINARY' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
   if [[ "$INST64_YAZI_METHOD" == 'BINARY' ]]; then
@@ -282,22 +180,21 @@ function inst64_initialize() {
       bl64_check_privilege_root ||
         return $?
     fi
+    bl64_os_check_not_version \
+      "${BL64_OS_ALM}-9" \
+      "${BL64_OS_RCK}-9" \
+      "${BL64_OS_OL}-9" &&
     bl64_arc_setup ||
       return $?
   fi
+
   inst64_select_platform &&
-    inst64_select_packages ||
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
 
-  bl64_msg_show_setup 'Install application: Yazi file manager' \
-    'INST64_SYSTEM_WIDE' 'INST64_YAZI_METHOD' \
-    'INST64_YAZI_PLATFORM' \
-    'INST64_GH_REPO_OWNER' \
-    'INST64_GH_REPO_NAME' \
-    'INST64_YAZI_TARGET' \
-    'INST64_YAZI_VERSION' \
-    'INST64_YAZI_CLI_PATH_YAZI' \
-    'INST64_YAZI_CLI_PATH_YA'
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
diff --git a/src/install-zoho-vault b/src/install-zoho-vault
--- a/src/install-zoho-vault
+++ b/src/install-zoho-vault
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
-# Template: 2.3.0
-# Snippet: install-custom-package-4.2.0
-# Snippet: select-platform-1.0.0
+# Template: install-bl64-binary-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -19,260 +17,174 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_ZOHOVAULT_PLATFORM="${INST64_ZOHOVAULT_PLATFORM:-}"
-declare INST64_ZOHOVAULT_SOURCE="${INST64_ZOHOVAULT_SOURCE:-https://downloads.zohocdn.com/vault-cli-desktop}"
-declare INST64_ZOHOVAULT_TARGET="${INST64_ZOHOVAULT_TARGET:-}"
-declare INST64_ZOHOVAULT_VERSION="${INST64_ZOHOVAULT_VERSION:-}"
 # Installation method
-declare INST64_ZOHOVAULT_METHOD="${INST64_ZOHOVAULT_METHOD:-CUSTOM}"
+declare INST64_ZOHOVAULT_METHOD="${INST64_ZOHOVAULT_METHOD:-BINARY}"
+# Installation destination
+declare INST64_ZOHOVAULT_TARGET="${INST64_ZOHOVAULT_TARGET:-}"
+# Hardware architecture
+declare INST64_ZOHOVAULT_PLATFORM="${INST64_ZOHOVAULT_PLATFORM:-}"
+# Application version
+declare INST64_ZOHOVAULT_VERSION="${INST64_ZOHOVAULT_VERSION:-latest}"
 
-declare INST64_WEB_REPO_URL=''
-declare INST64_APP_INSTALLER=''
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='zv'
-declare INST64_CLI_PATH=''
+INST64_APP_NAME='zohovault'
+INST64_APP_ID='ZOHOVAULT'
+INST64_APP_FULL_NAME='ZohoVault - Zoho Vault CLI'
+INST64_CLI_NAME='zv'
+
+INST64_WEB_REPO_URL='https://downloads.zohocdn.com'
+INST64_WEB_REPO_PATH='vault-cli-desktop'
+INST64_PKG_MAIN_PREFIX='zv_cli'
+INST64_PKG_MAIN_SUFFIX='.zip'
+INST64_CPU_DARWIN_ARM64='macos'
+INST64_CPU_LINUX_AMD64='linux'
 
 #
 # Functions
 #
 
-function inst64_install_custom_package() {
+function inst64_install_binary() {
   bl64_dbg_app_show_function
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner='root'
-  local app_cli_source="$INST64_CLI_NAME"
 
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    INST64_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_CLI_NAME}"
-  else
-    INST64_CLI_PATH="${INST64_ZOHOVAULT_TARGET}/${INST64_CLI_NAME}"
-    app_target_owner="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" &&
-    bl64_rxtx_web_get_file \
-      "${INST64_WEB_REPO_URL}/${INST64_PKG_MAIN}" \
-      "${work_path}/${INST64_PKG_MAIN}" \
-      'YES' \
-      "$app_target_mode" &&
-    bl64_arc_open_zip "${work_path}/${INST64_PKG_MAIN}" "${work_path}" ||
+  inst64_lib_task_binary_download &&
+    inst64_lib_web_get_file &&
+    inst64_lib_staging_open_zip ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_ZOHOVAULT_TARGET" &&
-    bl64_fs_path_copy "$app_target_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_ZOHOVAULT_TARGET" "${work_path}/${app_cli_source}" ||
+  inst64_lib_task_deploy
+  inst64_lib_target_create &&
+    inst64_lib_target_populate ||
     return $?
 
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_msg_show_task "publish application to searchable path (${INST64_CLI_PATH})"
-    # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${INST64_ZOHOVAULT_TARGET}/${INST64_CLI_NAME}" "$INST64_CLI_PATH" "$BL64_VAR_ON" ||
-      return $?
-  fi
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
-function inst64_select_platform() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_ZOHOVAULT_METHOD" == 'CUSTOM' ]]; then
-    [[ -z "$INST64_ZOHOVAULT_PLATFORM" ]] && INST64_ZOHOVAULT_PLATFORM='linux'
-  fi
-  [[ -z "$INST64_ZOHOVAULT_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_ZOHOVAULT_METHOD" == 'CUSTOM' ]]; then
-    inst64_install_custom_package
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
-  bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
-  if [[ "$INST64_ZOHOVAULT_METHOD" == 'CUSTOM' ]]; then
-    package_prefix='zv_cli'
-    package_suffix='.zip'
-    INST64_PKG_MAIN="${package_prefix}${package_suffix}"
-    INST64_WEB_REPO_URL="${INST64_ZOHOVAULT_SOURCE}/${INST64_ZOHOVAULT_PLATFORM}"
-    [[ -z "$INST64_WEB_REPO_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
-  fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_prepare() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  inst64_select_platform &&
-    inst64_select_packages ||
-    return $?
-  if [[ "$INST64_ZOHOVAULT_METHOD" == 'CUSTOM' ]]; then
-    bl64_arc_setup
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
+    inst64_lib_base_create_path
   fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
+    inst64_install_binary
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
+    INST64_WORK_PATH_CLI="${INST64_ZOHOVAULT_TARGET}/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
+  fi
+}
+
 function inst64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  cd && "$INST64_CLI_PATH" --version
+  inst64_lib_step_verify || return 0
+  cd $HOME &&
+    "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'BINARY' ||
+    return $?
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'AUTO' ]]; then
+    INST64_ZOHOVAULT_METHOD='BINARY'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
+    if [[ -z "$INST64_ZOHOVAULT_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_ZOHOVAULT_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_ZOHOVAULT_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      fi
+    fi
+    inst64_lib_platform_check_cpu
+  fi
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_PKG_MAIN_SUFFIX}"
+    INST64_WEB_REPO_PATH+="/${INST64_ZOHOVAULT_PLATFORM}"
+  fi
+  inst64_lib_package_check_definition
+}
+
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_ZOHOVAULT_TARGET="${INST64_ZOHOVAULT_TARGET:-${INST64_OPT_ROOT}/zohovault}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_ZOHOVAULT_METHOD' \
-    "$INST64_ZOHOVAULT_METHOD" \
-    'CUSTOM' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
-  if [[ "$INST64_ZOHOVAULT_METHOD" == 'CUSTOM' ]]; then
+  if [[ "$INST64_ZOHOVAULT_METHOD" == 'BINARY' ]]; then
     if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
       bl64_check_privilege_root ||
         return $?
     fi
-    bl64_os_check_compatibility \
-      "${BL64_OS_ALM}" \
-      "${BL64_OS_AMZ}" \
-      "${BL64_OS_CNT}" \
-      "${BL64_OS_DEB}" \
-      "${BL64_OS_FD}" \
-      "${BL64_OS_OL}" \
-      "${BL64_OS_RCK}" \
-      "${BL64_OS_RHEL}" \
-      "${BL64_OS_SLES}" \
-      "${BL64_OS_UB}"
-    bl64_dbg_app_show_comments 'binary is not compatible with ALP'
+    bl64_os_check_not_version \
+      "${BL64_OS_UB}-24" \
+      "${BL64_OS_UB}-25" &&
+      bl64_arc_setup ||
+      return $?
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Zoho Vault' \
-    'INST64_ZOHOVAULT_METHOD' 'INST64_SYSTEM_WIDE' 
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.1.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -280,5 +192,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
