feat: promote 3.11.0
## [3.11.0]

### Added

- Installer:
  - Act
- Cosign
  - System Wide parameter

diff --git a/src/install-act b/src/install-act
--- a/src/install-act
+++ b/src/install-act
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 2.1.0
+# Template: 2.2.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.3.0
+# Version: 1.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -31,8 +31,6 @@
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -42,62 +40,72 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
+# shellcheck source-path=lib/bl64
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
   { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
 
 #
 # Globals
 #
 
-export INST64_COSIGN_PLATFORM="${INST64_COSIGN_PLATFORM:-linux-amd64}"
-export INST64_COSIGN_TARGET="${INST64_COSIGN_TARGET:-${INST64_OPT_ROOT}/cosign}"
-export INST64_COSIGN_VERSION="${INST64_COSIGN_VERSION:-latest}"
+export INST64_ACT_PLATFORM="${INST64_ACT_PLATFORM:-Linux_x86_64}"
+export INST64_ACT_TARGET="${INST64_ACT_TARGET:-${INST64_OPT_ROOT}/act}"
+export INST64_ACT_VERSION="${INST64_ACT_VERSION:-latest}"
 # Install system wide? Requires root privilege
-export INST64_COSIGN_SYSTEM_WIDE="${INST64_COSIGN_SYSTEM_WIDE:-YES}"
+export INST64_ACT_SYSTEM_WIDE="${INST64_ACT_SYSTEM_WIDE:-YES}"
 # Installation method
-export INST64_COSIGN_METHOD="${INST64_COSIGN_METHOD:-BINARY}"
+export INST64_ACT_METHOD="${INST64_ACT_METHOD:-BINARY}"
 
-export INST64_COSIGN_REPO_NAME='cosign'
-export INST64_COSIGN_REPO_OWNER='sigstore'
-export INST64_COSIGN_PACKAGES=''
-export INST64_COSIGN_CLI_NAME='cosign'
-export INST64_COSIGN_CLI_PATH=''
+export INST64_ACT_REPO_NAME='act'
+export INST64_ACT_REPO_OWNER='nektos'
+export INST64_ACT_PACKAGES=''
+export INST64_ACT_CLI_NAME='act'
+export INST64_ACT_CLI_PATH=''
 
 #
 # Functions
 #
 
-function inst64_cosign_install_binary_release() {
+function inst64_act_install_binary_release() {
   bl64_dbg_app_show_function
   local work_path=''
   local app_target_mode='0755'
   local app_target_owner='root'
   local app_cli_mode='0755'
-  local app_cli_source="${INST64_COSIGN_CLI_NAME}-${INST64_COSIGN_PLATFORM}"
+  local app_cli_source="${INST64_ACT_CLI_NAME}"
 
-  if bl64_lib_flag_is_enabled "$INST64_COSIGN_SYSTEM_WIDE"; then
-    INST64_COSIGN_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_COSIGN_CLI_NAME}"
+  if bl64_lib_flag_is_enabled "$INST64_ACT_SYSTEM_WIDE"; then
+    INST64_ACT_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_ACT_CLI_NAME}"
   else
-    INST64_COSIGN_CLI_PATH="${INST64_COSIGN_TARGET}/${INST64_COSIGN_CLI_NAME}"
+    INST64_ACT_CLI_PATH="${INST64_ACT_TARGET}/${INST64_ACT_CLI_NAME}"
     app_target_owner="$BL64_VAR_DEFAULT"
   fi
 
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
   bl64_rxtx_github_get_asset \
-    "$INST64_COSIGN_REPO_OWNER" "$INST64_COSIGN_REPO_NAME" "$INST64_COSIGN_VERSION" "$INST64_COSIGN_PACKAGES" "${work_path}/${INST64_COSIGN_PACKAGES}" ||
+    "$INST64_ACT_REPO_OWNER" "$INST64_ACT_REPO_NAME" "$INST64_ACT_VERSION" "$INST64_ACT_PACKAGES" "${work_path}/${INST64_ACT_PACKAGES}" &&
+    bl64_arc_open_tar "${work_path}/${INST64_ACT_PACKAGES}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
-  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_COSIGN_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_COSIGN_TARGET" "${work_path}/${app_cli_source}" ||
+  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_ACT_TARGET" &&
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_ACT_TARGET" "${work_path}/${app_cli_source}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_COSIGN_TARGET}/${app_cli_source}" "$INST64_COSIGN_CLI_PATH" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_ACT_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_ACT_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_ACT_TARGET}/${app_cli_source}" "$INST64_ACT_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
@@ -115,11 +123,11 @@ function inst64_cosign_install_binary_release() {
 #   0: package installed ok
 #   >0: unable to install package
 #######################################
-function inst64_cosign_install() {
+function inst64_act_install() {
   bl64_dbg_app_show_function
-  inst64_cosign_select_packages || return $?
-  if [[ "$INST64_COSIGN_METHOD" == 'BINARY' ]]; then
-    inst64_cosign_install_binary_release
+  inst64_act_select_packages || return $?
+  if [[ "$INST64_ACT_METHOD" == 'BINARY' ]]; then
+    inst64_act_install_binary_release
   fi
 }
 
@@ -134,19 +142,20 @@ function inst64_cosign_install() {
 #   0: selection ok
 #   >0: selection failed
 #######################################
-function inst64_cosign_select_packages() {
+function inst64_act_select_packages() {
   bl64_dbg_app_show_function
   local package_prefix=''
   local package_sufix=''
-  if [[ "$INST64_COSIGN_METHOD" == 'BINARY' ]]; then
-    if [[ "$INST64_COSIGN_VERSION" == 'latest' ]]; then
-      INST64_COSIGN_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_COSIGN_REPO_OWNER" "$INST64_COSIGN_REPO_NAME")" ||
+  if [[ "$INST64_ACT_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_ACT_VERSION" == 'latest' ]]; then
+      INST64_ACT_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_ACT_REPO_OWNER" "$INST64_ACT_REPO_NAME")" ||
         return $?
     fi
-    package_prefix='cosign'
-    INST64_COSIGN_PACKAGES="${package_prefix}-${INST64_COSIGN_PLATFORM}${package_sufix}"
+    package_prefix='act_'
+    package_sufix='.tar.gz'
+    INST64_ACT_PACKAGES="${package_prefix}${INST64_ACT_PLATFORM}${package_sufix}"
   fi
-  [[ -z "$INST64_COSIGN_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  [[ -z "$INST64_ACT_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
 }
 
@@ -161,10 +170,10 @@ function inst64_cosign_select_packages() {
 #   0: preparation ok
 #   >0: preparation failed
 #######################################
-function inst64_cosign_prepare() {
+function inst64_act_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_COSIGN_METHOD" == 'BINARY' ]]; then
+  if [[ "$INST64_ACT_METHOD" == 'BINARY' ]]; then
     bl64_arc_setup
   fi
 }
@@ -180,10 +189,10 @@ function inst64_cosign_prepare() {
 #   0: verification ok
 #   >0: verification failed
 #######################################
-function inst64_cosign_verify() {
+function inst64_act_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  "$INST64_COSIGN_CLI_PATH" version
+  "$INST64_ACT_CLI_PATH" --version
 }
 
 #######################################
@@ -195,20 +204,18 @@ function inst64_cosign_verify() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
-function inst64_cosign_initialize() {
+function inst64_act_initialize() {
   bl64_dbg_app_show_function
-  if bl64_lib_flag_is_enabled "$INST64_COSIGN_SYSTEM_WIDE"; then
+  if bl64_lib_flag_is_enabled "$INST64_ACT_SYSTEM_WIDE"; then
     bl64_check_privilege_root ||
       return $?
   fi
   bl64_os_check_compatibility \
-      "${BL64_OS_OL}-9" \
-      "${BL64_OS_UB}-22" \
-      "${BL64_OS_ALP}-3" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_COSIGN_METHOD' \
-      "$INST64_COSIGN_METHOD" \
+    "${BL64_OS_UB}-22" &&
+    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_ACT_METHOD' \
+      "$INST64_ACT_METHOD" \
       'BINARY'
 }
 
@@ -216,14 +223,14 @@ function inst64_cosign_initialize() {
 # Main
 #
 
-declare inst64_cosign_installer_description='Install application: Sigstore cosign'
+declare inst64_act_installer_description='Install application: Act'
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start "$inst64_cosign_installer_description"
+bl64_msg_show_batch_start "$inst64_act_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
-inst64_cosign_initialize &&
-  inst64_cosign_prepare &&
-  inst64_cosign_install &&
-  inst64_cosign_verify
-bl64_msg_show_batch_finish $? "$inst64_cosign_installer_description"
+inst64_act_initialize &&
+  inst64_act_prepare &&
+  inst64_act_install &&
+  inst64_act_verify
+bl64_msg_show_batch_finish $? "$inst64_act_installer_description"
