fix: replace deprecated repo key

diff --git a/src/install-mysqlcli b/src/install-mysqlcli
--- a/src/install-mysqlcli
+++ b/src/install-mysqlcli
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 2.1.0
+# Template: 2.2.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.0.0
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,6 +29,21 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source=lib/bl64/bashlib64.bash
+source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -40,14 +55,6 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
 # Installation method
 export INST64_MYSQLCLI_METHOD="${INST64_MYSQLCLI_METHOD:-EXTERNAL}"
 export INST64_MYSQLCLI_PLATFORM_YUM="${INST64_MYSQLCLI_PLATFORM_YUM:-x86_64}"
@@ -55,10 +62,11 @@ export INST64_MYSQLCLI_VERSION="${INST64_MYSQLCLI_VERSION:-8}"
 
 export INST64_MYSQLCLI_REPOSITORY_NAME='mysql-tools-community'
 export INST64_MYSQLCLI_SOURCE_YUM='http://repo.mysql.com/yum/mysql-tools-community/el'
-export INST64_MYSQLCLI_REPOSITORY_KEY_YUM='https://repo.mysql.com/RPM-GPG-KEY-mysql-2022'
+bl64_dbg_app_show_comment 'deprecated: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022'
+export INST64_MYSQLCLI_REPOSITORY_KEY_YUM='https://repo.mysql.com/RPM-GPG-KEY-mysql-2023'
 export INST64_MYSQLCLI_PACKAGES=''
-export INST64_MYSQLCLI_NAME='mysqlsh'
-export INST64_MYSQLCLI_PATH=''
+export INST64_MYSQLCLI_CLI_NAME='mysqlsh'
+export INST64_MYSQLCLI_CLI_PATH=''
 
 #
 # Functions
@@ -85,7 +93,7 @@ function inst64_mysqlcli_add_repository() {
 function inst64_mysqlcli_install_external_packages() {
   bl64_dbg_app_show_function
 
-  INST64_MYSQLCLI_PATH="/usr/bin/${INST64_MYSQLCLI_NAME}"
+  INST64_MYSQLCLI_CLI_PATH="/usr/bin/${INST64_MYSQLCLI_CLI_NAME}"
 
   bl64_msg_show_task 'deploy packages'
   # shellcheck disable=SC2086
@@ -164,7 +172,7 @@ function inst64_mysqlcli_prepare() {
 function inst64_mysqlcli_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  "$INST64_MYSQLCLI_PATH" --version
+  "$INST64_MYSQLCLI_CLI_PATH" --version
 }
 
 #######################################
