refact: migrate to lib-bl64

diff --git a/src/install-btop b/src/install-btop
--- a/src/install-btop
+++ b/src/install-btop
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-native-2.4.0
+# Template: install-bl64-native-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,13 +17,14 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
@@ -34,193 +35,193 @@ source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
 # Installation method
-declare INST64_BTOP_METHOD="${INST64_BTOP_METHOD:-NATIVE}"
-# Enable development packages?
-declare INST64_BTOP_DEVELOPMENT="${INST64_BTOP_DEVELOPMENT:-$BL64_VAR_OFF}"
+declare INST64_BTOP_METHOD="${INST64_BTOP_METHOD:-AUTO}"
+# Installation destination
+declare INST64_BTOP_TARGET="${INST64_BTOP_TARGET:-}"
+# Hardware architecture
 declare INST64_BTOP_PLATFORM="${INST64_BTOP_PLATFORM:-}"
+# Application version
+declare INST64_BTOP_VERSION="${INST64_BTOP_VERSION:-latest}"
+# Enable development packages?
+declare INST64_BTOP_DEVELOPMENT="${INST64_BTOP_DEVELOPMENT:-NO}"
 
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='btop'
-declare INST64_CLI_PATH=''
+# App information
+INST64_APP_NAME='btop'
+INST64_APP_ID='BTOP'
+INST64_APP_FULL_NAME='BTop'
+# CLI information
+INST64_CLI_NAME='btop'
+
+INST64_GH_REPO_NAME='btop'
+INST64_GH_REPO_OWNER='aristocratos'
+INST64_PKG_MAIN_PREFIX='btop-'
+INST64_PKG_MAIN_SUFFIX='.tbz'
+INST64_CPU_LINUX_AMD64_MUSL='x86_64-linux-musl'
 
 #
 # Functions
 #
 
-function inst64_install_os_packages() {
+function inst64_install_binary() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'deploy packages'
-  # shellcheck disable=SC2086
-  bl64_pkg_deploy $INST64_PKG_MAIN
+  local app_work_path="btop/bin/${INST64_CLI_NAME}"
+
+  inst64_lib_task_binary_download &&
+    bl64_rxtx_github_get_asset \
+      "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME" "$INST64_BTOP_VERSION" "$INST64_PKG_MAIN" \
+      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" &&
+    bl64_arc_open_tar "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" "${INST64_WORK_PATH_STAGING}" ||
+    return $?
+
+  inst64_lib_task_deploy
+  bl64_fs_dir_create "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" "$INST64_BTOP_TARGET" &&
+    bl64_fs_path_copy "$INST64_CLI_MODE" "$INST64_TARGET_MODE" "$INST64_TARGET_OWNER" "$INST64_TARGET_GROUP" \
+      "$INST64_BTOP_TARGET" "${INST64_WORK_PATH_STAGING}/${app_work_path}" ||
+    return $?
+
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    inst64_lib_base_create_path
+  fi
+}
+
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_BTOP_METHOD" == 'NATIVE' ]]; then
+    inst64_install_native
+  elif [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    inst64_install_binary
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    INST64_WORK_PATH_CLI="${INST64_BTOP_TARGET}/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    # shellcheck disable=SC2086
+    bl64_fs_symlink_create "${INST64_WORK_PATH_CLI}" "${INST64_CLI_PATH}/${INST64_CLI_NAME}" "$BL64_VAR_ON"
+  fi
+}
+
+function inst64_verify() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
+  if [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    inst64_lib_app_register_version
+  fi
+}
+
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'BINARY' \
+    'NATIVE' ||
+    return $?
+  if [[ "$INST64_BTOP_METHOD" == 'AUTO' ]]; then
+    INST64_BTOP_METHOD='NATIVE'
+  fi
+}
+
 function inst64_select_platform() {
   bl64_dbg_app_show_function
   if [[ "$INST64_BTOP_METHOD" == 'NATIVE' ]]; then
-    [[ -z "$INST64_BTOP_PLATFORM" ]] && INST64_BTOP_PLATFORM='AUTO'
+    INST64_CLI_PATH='/usr/bin'
+  elif [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    if [[ -z "$INST64_BTOP_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_BTOP_PLATFORM="$INST64_CPU_LINUX_AMD64_MUSL"
+      else
+        INST64_BTOP_PLATFORM=''
+      fi
+    fi
+    inst64_lib_platform_check_cpu
   fi
-  [[ -z "$INST64_BTOP_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_BTOP_METHOD" == 'NATIVE' ]]; then
-    inst64_install_os_packages
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_select_packages() {
   bl64_dbg_app_show_function
   if [[ "$INST64_BTOP_METHOD" == 'NATIVE' ]]; then
-    INST64_PKG_MAIN='btop'
     bl64_lib_flag_is_enabled "$INST64_BTOP_DEVELOPMENT" &&
-      INST64_PKG_MAIN="${INST64_PKG_MAIN}"
-    INST64_CLI_PATH="/usr/bin/${INST64_CLI_NAME}"
+      INST64_PKG_DEV=''
+    INST64_PKG_MAIN='btop'
+    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
+  elif [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_BTOP_VERSION" == 'latest' ]]; then
+      INST64_BTOP_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
+        return $?
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_BTOP_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
   fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_BTOP_METHOD" == 'NATIVE' ]]; then
-    bl64_pkg_setup
-  fi
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_CLI_PATH" --version
-}
-
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_BTOP_METHOD' \
-    "$INST64_BTOP_METHOD" \
-    'NATIVE' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
   if [[ "$INST64_BTOP_METHOD" == 'NATIVE' ]]; then
     bl64_check_privilege_root &&
-      bl64_os_check_compatibility \
-        "${BL64_OS_MCOS}" \
-        "${BL64_OS_UB}" \
-        "${BL64_OS_FD}" \
-        "${BL64_OS_OL}" ||
+      bl64_os_check_flavor \
+        "$BL64_OS_FLAVOR_ALPINE" \
+        "$BL64_OS_FLAVOR_DEBIAN" \
+        "$BL64_OS_FLAVOR_FEDORA" \
+        "$BL64_OS_FLAVOR_MACOS" \
+        "$BL64_OS_FLAVOR_REDHAT" \
+        "$BL64_OS_FLAVOR_SUSE" &&
+      bl64_pkg_setup ||
+      return $?
+  elif [[ "$INST64_BTOP_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_flavor \
+      "$BL64_OS_FLAVOR_ALPINE" \
+      "$BL64_OS_FLAVOR_DEBIAN" \
+      "$BL64_OS_FLAVOR_FEDORA" \
+      "$BL64_OS_FLAVOR_REDHAT" \
+      "$BL64_OS_FLAVOR_SUSE" &&
+      bl64_arc_setup ||
       return $?
   fi
+
   inst64_select_platform &&
-    inst64_select_packages ||
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
-  bl64_msg_show_setup 'Install application: BTop' \
-    'INST64_SYSTEM_WIDE' 'INST64_BTOP_METHOD' \
-    'INST64_CLI_PATH'
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.0.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -228,5 +229,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
