feat: add alpine3 support

diff --git a/src/install-python b/src/install-python
--- a/src/install-python
+++ b/src/install-python
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 1.1.0
+# Template: 2.0.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.1.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -37,6 +37,8 @@ export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
 # Base path for 3rd party applications
 export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
+# Location for temporary files
+export INST64_TMP="${INST64_TMP:-/tmp}"
 
 # shellcheck source=SCRIPTDIR/../lib/bashlib64.bash
 source "${INST64_BASHLIB64}/bashlib64.bash" ||
@@ -46,14 +48,31 @@ source "${INST64_BASHLIB64}/bashlib64.bash" ||
 # Globals
 #
 
+# Installation method
+export INST64_PYTHON_METHOD="${INST64_PYTHON_METHOD:-NATIVE}"
 # Enable development packages?
-export INST64_PYTHON_FLAG_DEVELOPMENT="${INST64_PYTHON_FLAG_DEVELOPMENT:-$BL64_VAR_OFF}"
-# Use OS native package?
-export INST64_PYTHON_FLAG_NATIVE="${INST64_PYTHON_FLAG_NATIVE:-$BL64_VAR_ON}"
+export INST64_PYTHON_DEVELOPMENT="${INST64_PYTHON_DEVELOPMENT:-$BL64_VAR_OFF}"
+
+export INST64_PYTHON_PACKAGES=''
+export INST64_PYTHON_CLI_NAME='python3'
 
 #
 # Functions
 #
+
+function inst64_python_install_os_packages() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'deploy packages'
+  # shellcheck disable=SC2086
+  bl64_pkg_deploy $INST64_PYTHON_PACKAGES ||
+    return $?
+  if bl64_os_match "${BL64_OS_ALP}-3"; then
+    bl64_msg_show_warning 'pipx native package not available. Using PIP method as root for system wide'
+    pip3 install pipx ||
+      return $?
+  fi
+  return 0
+}
 
 #######################################
 # Install application packages
@@ -68,22 +87,77 @@ export INST64_PYTHON_FLAG_NATIVE="${INST64_PYTHON_FLAG_NATIVE:-$BL64_VAR_ON}"
 #######################################
 function inst64_python_install() {
   bl64_dbg_app_show_function
-  local packages=''
-
-  if bl64_os_match "${BL64_OS_UB}-22"; then
-    packages='python3 python3.9 python3-pip python3-venv pipx'
-    [[ "$INST64_PYTHON_FLAG_DEVELOPMENT" == "$BL64_VAR_ON" ]] &&
-      packages="${packages} python3-dev build-essential"
+  inst64_python_select_packages || return $?
+  if [[ "$INST64_PYTHON_METHOD" == 'NATIVE' ]]; then
+    inst64_python_install_os_packages
   fi
+}
 
-  bl64_msg_show_task 'deploy packages'
-  # shellcheck disable=SC2086
-  bl64_pkg_deploy $packages ||
-    return $?
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_cleanup_full
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_python_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_PYTHON_METHOD" == 'NATIVE' ]]; then
+    if bl64_os_match "${BL64_OS_UB}-22"; then
+      INST64_PYTHON_PACKAGES='python3 python3-pip python3-venv pipx'
+      [[ "$INST64_PYTHON_DEVELOPMENT" == "$BL64_VAR_ON" ]] &&
+        INST64_PYTHON_PACKAGES="${INST64_PYTHON_PACKAGES} python3-dev build-essential"
+    elif bl64_os_match "${BL64_OS_ALP}-3"; then
+      INST64_PYTHON_PACKAGES='python3 py3-pip py3-virtualenv'
+      [[ "$INST64_PYTHON_DEVELOPMENT" == "$BL64_VAR_ON" ]] &&
+        INST64_PYTHON_PACKAGES="${INST64_PYTHON_PACKAGES} python3-dev py3-setuptools"
+    fi
+  fi
+  [[ -z "$INST64_PYTHON_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_python_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  bl64_pkg_setup
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_python_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  bl64_msg_show_subtask 'python3'
+  "$INST64_PYTHON_CLI_NAME" --version &&
+    bl64_msg_show_subtask 'pip' &&
+    pip3 --version &&
+    bl64_msg_show_subtask 'pipx' &&
+  pipx --version
 }
 
 #######################################
@@ -95,18 +169,17 @@ function inst64_python_install() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_python_initialize() {
   bl64_dbg_app_show_function
-
-  [[ "$INST64_PYTHON_FLAG_NATIVE" != "$BL64_VAR_ON" ]] &&
-    bl64_msg_show_error 'installer supports OS native packages only' &&
-    return 1
-
-  bl64_os_check_version "${BL64_OS_UB}-22" &&
+  bl64_os_check_version \
+    "${BL64_OS_UB}-22" \
+    "${BL64_OS_ALP}-3" &&
     bl64_check_privilege_root &&
-    bl64_pkg_setup
+    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_PYTHON_METHOD' \
+      "$INST64_PYTHON_METHOD" \
+      'NATIVE'
 }
 
 #
@@ -114,15 +187,13 @@ function inst64_python_initialize() {
 #
 
 declare inst64_python_installer_description='Install application: Python'
-declare -i inst64_python_status=0
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_python_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_python_initialize &&
-  inst64_python_install
-inst64_python_status=$?
-
-bl64_msg_show_batch_finish "$inst64_python_status" "$inst64_python_installer_description"
-exit $inst64_python_status
+  inst64_python_prepare &&
+  inst64_python_install &&
+  inst64_python_verify
+bl64_msg_show_batch_finish $? "$inst64_python_installer_description"
