feat: promote 3.14.0 (#57)
## [3.14.0]

### Added

- Installer
  - Gomplate
  - FZF
  - HTTPie
  - EZA
  - DUF
  - GPing

### Changed

- KubeConform
  - Updated OS compatibility
- KubeLinter
  - Updated OS compatibility
- ShellCheck
  - Updated OS compatibility

diff --git a/src/install-shellcheck b/src/install-shellcheck
--- a/src/install-shellcheck
+++ b/src/install-shellcheck
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
-# Template: 2.1.0
+# Template: 2.2.0
+# Snippet: install-os-package-2.5.0
+# Snippet: install-github-release-3.2.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 2.2.0
+# Version: 2.3.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,6 +31,23 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -40,31 +59,22 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-# Installation method
-export INST64_SHELLCHECK_METHOD="${INST64_SHELLCHECK_METHOD:-NATIVE}"
-# Enable development packages?
-export INST64_SHELLCHECK_DEVELOPMENT="${INST64_SHELLCHECK_DEVELOPMENT:-$BL64_VAR_OFF}"
-
 export INST64_SHELLCHECK_PLATFORM="${INST64_SHELLCHECK_PLATFORM:-linux.x86_64}"
 export INST64_SHELLCHECK_TARGET="${INST64_SHELLCHECK_TARGET:-${INST64_OPT_ROOT}/shellcheck}"
 export INST64_SHELLCHECK_VERSION="${INST64_SHELLCHECK_VERSION:-latest}"
 # Install system wide? Requires root privilege
 export INST64_SHELLCHECK_SYSTEM_WIDE="${INST64_SHELLCHECK_SYSTEM_WIDE:-YES}"
+# Installation method
+export INST64_SHELLCHECK_METHOD="${INST64_SHELLCHECK_METHOD:-NATIVE}"
+# Enable development packages?
+export INST64_SHELLCHECK_DEVELOPMENT="${INST64_SHELLCHECK_DEVELOPMENT:-$BL64_VAR_OFF}"
+
+export INST64_SHELLCHECK_REPO_NAME='shellcheck'
+export INST64_SHELLCHECK_REPO_OWNER='koalaman'
 
 export INST64_SHELLCHECK_PACKAGES=''
 export INST64_SHELLCHECK_CLI_NAME='shellcheck'
 export INST64_SHELLCHECK_CLI_PATH=''
-
-export INST64_SHELLCHECK_REPO_NAME='shellcheck'
-export INST64_SHELLCHECK_REPO_OWNER='koalaman'
 
 #
 # Functions
@@ -97,10 +107,12 @@ function inst64_shellcheck_install_binary_release() {
     bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_SHELLCHECK_TARGET" "${work_path}/${INST64_SHELLCHECK_CLI_NAME}-${INST64_SHELLCHECK_VERSION}/${app_cli_source}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_SHELLCHECK_CLI_PATH})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_SHELLCHECK_TARGET}/${app_cli_source}" "$INST64_SHELLCHECK_CLI_PATH" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_SHELLCHECK_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_SHELLCHECK_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_SHELLCHECK_TARGET}/${app_cli_source}" "$INST64_SHELLCHECK_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
@@ -155,6 +167,8 @@ function inst64_shellcheck_select_packages() {
     if bl64_os_match "${BL64_OS_ALP}"; then
       INST64_SHELLCHECK_PACKAGES='shellcheck'
     elif bl64_os_match "${BL64_OS_UB}"; then
+      INST64_SHELLCHECK_PACKAGES='shellcheck'
+    elif bl64_os_match "${BL64_OS_OL}"; then
       INST64_SHELLCHECK_PACKAGES='shellcheck'
     fi
   elif [[ "$INST64_SHELLCHECK_METHOD" == 'BINARY' ]]; then
@@ -222,18 +236,27 @@ function inst64_shellcheck_verify() {
 function inst64_shellcheck_initialize() {
   bl64_dbg_app_show_function
 
-  if bl64_lib_flag_is_enabled "$INST64_SHELLCHECK_SYSTEM_WIDE" || [[ "$INST64_SHELLCHECK_METHOD" == 'NATIVE' ]]; then
-    bl64_check_privilege_root ||
-      return $?
-  fi
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_SHELLCHECK_METHOD' \
+    "$INST64_SHELLCHECK_METHOD" \
+    'NATIVE' \
+    'BINARY' ||
+    return $?
 
-  bl64_os_check_compatibility \
-    "${BL64_OS_ALP}-3" \
-    "${BL64_OS_UB}-22" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_SHELLCHECK_METHOD' \
-      "$INST64_SHELLCHECK_METHOD" \
-      'NATIVE' \
-      'BINARY'
+  if [[ "$INST64_SHELLCHECK_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_SHELLCHECK_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "$BL64_OS_ALP" \
+      "$BL64_OS_UB" \
+      "$BL64_OS_OL"
+  elif [[ "$INST64_SHELLCHECK_METHOD" == 'NATIVE' ]]; then
+    bl64_os_check_compatibility \
+      "${BL64_OS_ALP}-3" \
+      "${BL64_OS_UB}-22" \
+      "${BL64_OS_OL}-9"
+  fi
 }
 
 #
