feat: added multi os support (#85)

diff --git a/src/install-kind b/src/install-kind
--- a/src/install-kind
+++ b/src/install-kind
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
-# Template: 2.1.0
+# Template: 2.3.0
+# Snippet: install-github-release-3.2.4
+# Snippet: select-platform-1.0.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.1.0
+# Version: 1.2.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,6 +31,23 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -40,15 +59,7 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-export INST64_KIND_PLATFORM="${INST64_KIND_PLATFORM:-linux-amd64}"
+export INST64_KIND_PLATFORM="${INST64_KIND_PLATFORM:-}"
 export INST64_KIND_TARGET="${INST64_KIND_TARGET:-${INST64_OPT_ROOT}/kind}"
 export INST64_KIND_VERSION="${INST64_KIND_VERSION:-latest}"
 # Install system wide? Requires root privilege
@@ -89,16 +100,40 @@ function inst64_kind_install_binary_release() {
 
   bl64_msg_show_task 'deploy application'
   bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_KIND_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_KIND_TARGET" "${work_path}/${app_cli_source}" ||
+    bl64_fs_path_copy "$app_cli_mode" "$BL64_VAR_DEFAULT" "$app_target_owner" "$app_target_owner" "$INST64_KIND_TARGET" "${work_path}/${app_cli_source}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_KIND_CLI_PATH})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_KIND_TARGET}/${app_cli_source}" "$INST64_KIND_CLI_PATH" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_KIND_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_KIND_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_KIND_TARGET}/${app_cli_source}" "$INST64_KIND_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_kind_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_KIND_METHOD" == 'BINARY' ]]; then
+      [[ -z "$INST64_KIND_PLATFORM" ]] && INST64_KIND_PLATFORM='linux-amd64'
+  fi
+  [[ -z "$INST64_KIND_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -115,7 +150,9 @@ function inst64_kind_install_binary_release() {
 #######################################
 function inst64_kind_install() {
   bl64_dbg_app_show_function
-  inst64_kind_select_packages || return $?
+  inst64_kind_select_platform &&
+    inst64_kind_select_packages ||
+    return $?
   if [[ "$INST64_KIND_METHOD" == 'BINARY' ]]; then
     inst64_kind_install_binary_release
   fi
@@ -163,7 +200,10 @@ function inst64_kind_select_packages() {
 function inst64_kind_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_arc_setup
+  inst64_kind_select_packages || return $?
+  if [[ "$INST64_KIND_METHOD" == 'BINARY' ]]; then
+    bl64_arc_setup
+  fi
 }
 
 #######################################
@@ -196,16 +236,29 @@ function inst64_kind_verify() {
 #######################################
 function inst64_kind_initialize() {
   bl64_dbg_app_show_function
-  if bl64_lib_flag_is_enabled "$INST64_KIND_SYSTEM_WIDE"; then
-    bl64_check_privilege_root ||
-      return $?
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_KIND_METHOD' \
+    "$INST64_KIND_METHOD" \
+    'BINARY' ||
+    return $?
+
+  if [[ "$INST64_KIND_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_KIND_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_ALM}" \
+      "${BL64_OS_ALP}" \
+      "${BL64_OS_AMZ}" \
+      "${BL64_OS_CNT}" \
+      "${BL64_OS_DEB}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_RCK}" \
+      "${BL64_OS_RHEL}" \
+      "${BL64_OS_SLES}" \
+      "${BL64_OS_UB}"
   fi
-  bl64_os_check_compatibility \
-    "${BL64_OS_UB}-22" \
-    "${BL64_OS_OL}-9" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_KIND_METHOD' \
-      "$INST64_KIND_METHOD" \
-      'BINARY'
 }
 
 #
