real: promote 6.2.0 (#138)

diff --git a/src/install-kubepug b/src/install-kubepug
--- a/src/install-kubepug
+++ b/src/install-kubepug
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
-# Template: legacy
-# Template: 2.0.0
+# Template: install-bl64-krew-1.0.0
+#   Skeleton: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -18,171 +18,110 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
+# shellcheck disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-k8s.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-declare INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
 # Installation method
 declare INST64_KUBEPUG_METHOD="${INST64_KUBEPUG_METHOD:-KREW}"
+# Application version
+declare INST64_KUBEPUG_VERSION="${INST64_KUBEPUG_VERSION:-latest}"
 
-declare INST64_KUBEPUG_KREW_BIN="${HOME}/.krew/bin/kubectl-krew"
-declare INST64_KUBEPUG_K8S_KUBECONFIG="${INST64_KUBEPUG_K8S_KUBECONFIG:-$BL64_VAR_DEFAULT}"
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='deprecations'
+# App information
+INST64_APP_NAME='kubepug'
+INST64_APP_ID='KUBEPUG'
+INST64_APP_FULL_NAME='Kubepug - Kubernetes PreUpGrade Checker'
 
+INST64_CLI_NAME='kubectl-deprecations'
+
+INST64_PKG_MAIN='deprecations'
 
 #
 # Functions
 #
 
-function inst64_install_krew_package() {
+function inst64_prepare() {
   bl64_dbg_app_show_function
-
-  bl64_msg_show_task 'deploy application to local kubectl'
-  # shellcheck disable=SC2086
-  bl64_k8s_run_kubectl_plugin \
-    "$INST64_KUBEPUG_K8S_KUBECONFIG" \
-    krew install \
-    $INST64_PKG_MAIN
+  inst64_lib_step_prepare || return 0
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
 function inst64_install() {
   bl64_dbg_app_show_function
-  inst64_select_packages || return $?
+  inst64_lib_step_install || return 0
   if [[ "$INST64_KUBEPUG_METHOD" == 'KREW' ]]; then
-    inst64_install_krew_package
+    inst64_lib_k8s_install_krew
   fi
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
+function inst64_setup() {
   bl64_dbg_app_show_function
-  if [[ "$INST64_KUBEPUG_METHOD" == 'KREW' ]]; then
-    INST64_PKG_MAIN='deprecations'
+  inst64_lib_step_setup || return 0
+}
+
+function inst64_verify() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" version
+}
+
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'KREW' ||
+    return $?
+  if [[ "$INST64_KUBEPUG_METHOD" == 'AUTO' ]]; then
+    INST64_KUBEPUG_METHOD='KREW'
   fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
   return 0
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_prepare() {
+function inst64_select_packages() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  bl64_k8s_setup
+  return 0
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  bl64_k8s_run_kubectl_plugin "$INST64_KUBEPUG_K8S_KUBECONFIG" \
-    "$INST64_CLI_NAME" version
-}
-
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_os_check_compatibility \
-    "${BL64_OS_OL}-9" &&
-    bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_KUBEPUG_METHOD' \
-      "$INST64_KUBEPUG_METHOD" \
-      'KREW' &&
-    bl64_check_privilege_not_root &&
-    bl64_check_command "$INST64_KUBEPUG_KREW_BIN"
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: KubePug' \
-    'INST64_KUBEPUG_METHOD' 'INST64_SYSTEM_WIDE' 
+  inst64_select_method &&
+    inst64_lib_base_initialize ||
+    return $?
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.1.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -190,5 +129,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
