feat: promote 3.3.0 (#40)
## [3.3.0]

### Changed

- Enabled support for Ubuntu-22, Alpine-3, Oraclelinux-9:
  - Cosign
  - Crane
  - Dockle
  - Hadolint
  - Lazydocker

diff --git a/src/install-cosign b/src/install-cosign
--- a/src/install-cosign
+++ b/src/install-cosign
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 1.1.0
+# Template: 2.0.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.0.0
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -53,10 +53,47 @@ source "${INST64_BASHLIB64}/bashlib64.bash" ||
 export INST64_COSIGN_PLATFORM="${INST64_COSIGN_PLATFORM:-linux-amd64}"
 export INST64_COSIGN_TARGET="${INST64_COSIGN_TARGET:-${INST64_OPT_ROOT}/cosign}"
 export INST64_COSIGN_VERSION="${INST64_COSIGN_VERSION:-latest}"
+# Installation method
+export INST64_COSIGN_METHOD="${INST64_COSIGN_METHOD:-BINARY}"
+
+export INST64_COSIGN_REPO_NAME='cosign'
+export INST64_COSIGN_REPO_OWNER='sigstore'
+
+export INST64_COSIGN_PACKAGES=''
+export INST64_COSIGN_CLI_NAME='cosign'
 
 #
 # Functions
 #
+
+function inst64_cosign_install_binary_release() {
+  bl64_dbg_app_show_function
+  local work_path=''
+  local app_target_mode='0755'
+  local app_target_owner='root'
+  local app_cli_mode='0755'
+  local app_cli_source="${INST64_COSIGN_CLI_NAME}-${INST64_COSIGN_PLATFORM}"
+
+  bl64_msg_show_task 'download application'
+  work_path="$(bl64_fs_create_tmpdir)" || return $?
+  bl64_rxtx_github_get_asset \
+    "$INST64_COSIGN_REPO_OWNER" "$INST64_COSIGN_REPO_NAME" "$INST64_COSIGN_VERSION" "$INST64_COSIGN_PACKAGES" "${work_path}/${INST64_COSIGN_PACKAGES}" ||
+    return $?
+
+  bl64_msg_show_task 'deploy application'
+  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_COSIGN_TARGET" &&
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_COSIGN_TARGET" "${work_path}/${app_cli_source}" ||
+    return $?
+
+  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
+  # shellcheck disable=SC2086
+  bl64_fs_create_symlink "${INST64_COSIGN_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_COSIGN_CLI_NAME}" "$BL64_VAR_ON" ||
+    return $?
+
+  bl64_msg_show_task 'cleanup temporary files'
+  bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
 
 #######################################
 # Install application packages
@@ -71,40 +108,71 @@ export INST64_COSIGN_VERSION="${INST64_COSIGN_VERSION:-latest}"
 #######################################
 function inst64_cosign_install() {
   bl64_dbg_app_show_function
-  local repo_owner='sigstore'
-  local repo_name='cosign'
-  local package_prefix='cosign'
-  local package_name=''
-  local work_path=''
-  local app_target_mode='0755'
-  local app_target_owner='root'
-  local app_cli_mode='0755'
-  local app_cli='cosign'
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  if [[ "$INST64_COSIGN_VERSION" == 'latest' ]]; then
-    INST64_COSIGN_VERSION="$(bl64_vcs_github_release_get_latest "$repo_owner" "$repo_name")" ||
-      return $?
+  inst64_cosign_select_packages || return $?
+  if [[ "$INST64_COSIGN_METHOD" == 'BINARY' ]]; then
+    inst64_cosign_install_binary_release
   fi
-  package_name="${package_prefix}-${INST64_COSIGN_PLATFORM}"
+}
 
-  bl64_rxtx_github_get_asset "$repo_owner" "$repo_name" "$INST64_COSIGN_VERSION" "$package_name" "${work_path}/${app_cli}" ||
-    return $?
-
-  bl64_msg_show_task 'deploy application'
-  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_COSIGN_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_COSIGN_TARGET" "${work_path}/${app_cli}" ||
-    return $?
-
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_run_ln $BL64_FS_SET_LN_SYMBOLIC "${INST64_COSIGN_TARGET}/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" ||
-    return $?
-
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_cosign_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_COSIGN_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_COSIGN_VERSION" == 'latest' ]]; then
+      INST64_COSIGN_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_COSIGN_REPO_OWNER" "$INST64_COSIGN_REPO_NAME")" ||
+        return $?
+    fi
+    package_prefix='cosign'
+    INST64_COSIGN_PACKAGES="${package_prefix}-${INST64_COSIGN_PLATFORM}${package_sufix}"
+  fi
+  [[ -z "$INST64_COSIGN_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_cosign_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  bl64_arc_setup
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_cosign_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "${INST64_LOCAL_BIN}/${INST64_COSIGN_CLI_NAME}" version
 }
 
 #######################################
@@ -120,9 +188,13 @@ function inst64_cosign_install() {
 #######################################
 function inst64_cosign_initialize() {
   bl64_dbg_app_show_function
-  bl64_arc_setup &&
-    bl64_os_check_version \
-      "${BL64_OS_OL}-9" &&
+  bl64_os_check_version \
+      "${BL64_OS_OL}-9" \
+      "${BL64_OS_UB}-22" \
+      "${BL64_OS_ALP}-3" &&
+    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_COSIGN_METHOD' \
+      "$INST64_COSIGN_METHOD" \
+      'BINARY' &&
     bl64_check_privilege_root
 }
 
@@ -131,15 +203,13 @@ function inst64_cosign_initialize() {
 #
 
 declare inst64_cosign_installer_description='Install application: Sigstore cosign'
-declare -i inst64_cosign_status=0
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_cosign_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_cosign_initialize &&
-  inst64_cosign_install
-inst64_cosign_status=$?
-
-bl64_msg_show_batch_finish "$inst64_cosign_status" "$inst64_cosign_installer_description"
-exit $inst64_cosign_status
+  inst64_cosign_prepare &&
+  inst64_cosign_install &&
+  inst64_cosign_verify
+bl64_msg_show_batch_finish $? "$inst64_cosign_installer_description"
