refact: update os list

diff --git a/src/install-krew b/src/install-krew
--- a/src/install-krew
+++ b/src/install-krew
@@ -1,11 +1,14 @@
 #!/usr/bin/env bash
-# Template: 1.2.0
+# Template: 2.3.0
+# Snippet: install-custom-package-4.2.0
+# Snippet: select-platform-1.0.0
+# Snippet: setup-environment-2.0.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.2.0
+# Version: 2.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,10 +32,23 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -42,51 +58,99 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-export INST64_KREW_REPO_NAME='krew'
-export INST64_KREW_REPO_OWNER='kubernetes-sigs'
-
-#
-# Globals
-#
-
-export INST64_KREW_PLATFORM="${INST64_KREW_PLATFORM:-linux_amd64}"
+export INST64_KREW_PLATFORM="${INST64_KREW_PLATFORM:-}"
+export INST64_KREW_TARGET="${INST64_KREW_TARGET:-${INST64_OPT_ROOT}/krew}"
 export INST64_KREW_VERSION="${INST64_KREW_VERSION:-latest}"
 # Installation method
 export INST64_KREW_METHOD="${INST64_KREW_METHOD:-CUSTOM}"
+
+export INST64_KREW_ENV='kubectl-krew.env'
+export INST64_KREW_REPO_NAME='krew'
+export INST64_KREW_REPO_OWNER='kubernetes-sigs'
+export INST64_KREW_INSTALLER=''
+export INST64_KREW_PACKAGES=''
+export INST64_KREW_CLI_NAME='kubectl-krew'
+export INST64_KREW_CLI_PATH=''
 
 #
 # Functions
 #
 
+#######################################
+# Perform post installation setup
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Setup progress
+# Returns:
+#   0: setup completed ok
+#   >0: unable to setup
+#######################################
+function inst64_krew_setup() {
+  bl64_dbg_app_show_function
+  local mode='0644'
+
+  bl64_msg_show_task 'setup application environment'
+  INST64_KREW_ENV="${HOME}/.local/bin/${INST64_KREW_ENV}"
+  bl64_msg_show_subtask "create shell env file (${INST64_KREW_ENV})"
+  # shellcheck disable=SC2016
+  printf '#!/usr/bin/env sh
+#
+# Krew
+#
+# * Define application environment variables
+#
+
+KREW_ROOT="$HOME/.krew"
+export KREW_ROOT
+
+PATH="$PATH:$KREW_ROOT/bin"
+' >"$INST64_KREW_ENV" &&
+    bl64_fs_run_chmod "$mode" "$INST64_KREW_ENV"
+}
+
 function inst64_krew_install_custom_package() {
   bl64_dbg_app_show_function
-  local package_prefix='krew-'
-  local package_sufix='.tar.gz'
-  local package_name=''
   local work_path=''
+
+  INST64_KREW_CLI_PATH="${HOME}/.krew/bin/${INST64_KREW_CLI_NAME}"
 
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
-  if [[ "$INST64_KREW_VERSION" == 'latest' ]]; then
-    INST64_KREW_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_KREW_REPO_OWNER" "$INST64_KREW_REPO_NAME")" ||
-      return $?
-  fi
-  package_name="${package_prefix}${INST64_KREW_PLATFORM}${package_sufix}"
-
-  bl64_rxtx_github_get_asset "$INST64_KREW_REPO_OWNER" "$INST64_KREW_REPO_NAME" "$INST64_KREW_VERSION" "$package_name" "${work_path}/${package_name}" &&
-    bl64_arc_open_tar "${work_path}/${package_name}" "${work_path}" ||
+  bl64_rxtx_github_get_asset \
+    "$INST64_KREW_REPO_OWNER" "$INST64_KREW_REPO_NAME" "$INST64_KREW_VERSION" "$INST64_KREW_PACKAGES" "${work_path}/${INST64_KREW_PACKAGES}" &&
+    bl64_arc_open_tar "${work_path}/${INST64_KREW_PACKAGES}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
-  "${work_path}/${package_prefix}${INST64_KREW_PLATFORM}" install krew ||
+  "${work_path}/${INST64_KREW_INSTALLER}" install krew ||
     return $?
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_krew_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    [[ -z "$INST64_KREW_PLATFORM" ]] && INST64_KREW_PLATFORM='linux_amd64'
+  fi
+  [[ -z "$INST64_KREW_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -109,6 +173,76 @@ function inst64_krew_install() {
 }
 
 #######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_krew_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    if [[ "$INST64_KREW_VERSION" == 'latest' ]]; then
+      INST64_KREW_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_KREW_REPO_OWNER" "$INST64_KREW_REPO_NAME")" ||
+        return $?
+    fi
+    package_prefix='krew-'
+    package_sufix='.tar.gz'
+    INST64_KREW_PACKAGES="${package_prefix}${INST64_KREW_PLATFORM}${package_sufix}"
+    INST64_KREW_INSTALLER="${package_prefix}${INST64_KREW_PLATFORM}"
+  fi
+  [[ -z "$INST64_KREW_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  return 0
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_krew_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  inst64_krew_select_platform &&
+    inst64_krew_select_packages ||
+    return $?
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
+    bl64_arc_setup
+  fi
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_krew_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  # shellcheck disable=SC1090
+  source "$INST64_KREW_ENV" &&
+  "$INST64_KREW_CLI_PATH" version
+}
+
+#######################################
 # Initialize environment
 #
 # Arguments:
@@ -117,18 +251,32 @@ function inst64_krew_install() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_krew_initialize() {
   bl64_dbg_app_show_function
-  bl64_os_check_compatibility \
-    "${BL64_OS_UB}-22" \
-    "${BL64_OS_OL}-9" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_KREW_METHOD' \
-      "$INST64_KREW_METHOD" \
-      'CUSTOM' &&
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_KREW_METHOD' \
+    "$INST64_KREW_METHOD" \
+    'CUSTOM' ||
+    return $?
+
+  if [[ "$INST64_KREW_METHOD" == 'CUSTOM' ]]; then
     bl64_check_privilege_not_root &&
-    bl64_arc_setup
+      bl64_arc_setup ||
+      return $?
+    bl64_os_check_compatibility \
+      "${BL64_OS_ALM}" \
+      "${BL64_OS_ALP}" \
+      "${BL64_OS_AMZ}" \
+      "${BL64_OS_CNT}" \
+      "${BL64_OS_DEB}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_RCK}" \
+      "${BL64_OS_RHEL}" \
+      "${BL64_OS_SLES}" \
+      "${BL64_OS_UB}"
+  fi
 }
 
 #
@@ -142,5 +290,8 @@ bl64_msg_show_batch_start "$inst64_krew_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_krew_initialize &&
-  inst64_krew_install
+  inst64_krew_prepare &&
+  inst64_krew_install &&
+  inst64_krew_setup &&
+  inst64_krew_verify
 bl64_msg_show_batch_finish $? "$inst64_krew_installer_description"
