feat: add local install

diff --git a/src/install-bashlib64 b/src/install-bashlib64
--- a/src/install-bashlib64
+++ b/src/install-bashlib64
@@ -5,17 +5,14 @@
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/bashlib64
-# Version: 2.1.0
+# Version: 3.0.0
 #
 #######################################
-# Copyright [2023] [serdigital64@gmail.com]
+# Copyright SerDigital64 - https://github.com/serdigital64
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#     http://www.apache.org/licenses/LICENSE-2.0
-#
+# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@@ -24,32 +21,33 @@
 #######################################
 
 #
-# Imports
-#
-
-# Enable debugging? Set to YES to enable
-export INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for 3rd party applications
-export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
-
-#
 # Globals
 #
 
-# Installation method
-export INST64_BASHLIB64_METHOD="${INST64_BASHLIB64_METHOD:-BINARY}"
-# Source repository
-export INST64_BASHLIB64_SOURCE="${INST64_BASHLIB64_SOURCE:-https://github.com/automation64/bashlib64}"
-# Target installation directory
-export INST64_BASHLIB64_TARGET="${INST64_BASHLIB64_TARGET:-${INST64_OPT_ROOT}/bl64}"
-# Target application version
-export INST64_BASHLIB64_VERSION="${INST64_BASHLIB64_VERSION:-latest}"
+# Home root
+declare INST64_HOME="${HOME}/at64"
 
-export INST64_BASHLIB64_DOWNLOAD_TOOL='none'
-export INST64_BASHLIB64_GH_API='https://api.github.com/repos/automation64/bashlib64/releases/latest'
-export INST64_BASHLIB64_PACKAGES=''
-export INST64_BASHLIB64_TARGET_MODE_DIR='0755'
-export INST64_BASHLIB64_TARGET_MODE_FILE='0644'
+# Enable debugging? Set to YES to enable
+declare INST64_DEBUG="${INST64_DEBUG:-}"
+# Base path for 3rd party applications
+declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
+# Install system wide? Requires root privilege
+declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
+
+# Installation method
+declare INST64_BASHLIB64_METHOD="${INST64_BASHLIB64_METHOD:-BINARY}"
+# Source repository
+declare INST64_BASHLIB64_SOURCE="${INST64_BASHLIB64_SOURCE:-https://github.com/automation64/bashlib64}"
+# Target installation directory
+declare INST64_BASHLIB64_TARGET="${INST64_BASHLIB64_TARGET:-}"
+# Target application version
+declare INST64_BASHLIB64_VERSION="${INST64_BASHLIB64_VERSION:-latest}"
+
+declare INST64_BASHLIB64_DOWNLOAD_TOOL='none'
+declare INST64_BASHLIB64_GH_API='https://api.github.com/repos/automation64/bashlib64/releases/latest'
+declare INST64_BASHLIB64_PACKAGES=''
+declare INST64_BASHLIB64_TARGET_MODE_DIR='0755'
+declare INST64_BASHLIB64_TARGET_MODE_FILE='0644'
 
 #
 # Functions
@@ -215,6 +213,13 @@ function inst64_bashlib64_verify() {
 #   >: failed to initialize
 #######################################
 function inst64_bashlib64_initialize() {
+  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
+    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
+  fi
+  if [[ -z "$INST64_OPT_ROOT" ]]; then
+    [[ "$INST64_SYSTEM_WIDE" == 'NO' ]] && INST64_OPT_ROOT="$INST64_HOME" || INST64_OPT_ROOT='/opt'
+  fi
+  INST64_BASHLIB64_TARGET="${INST64_BASHLIB64_TARGET:-${INST64_OPT_ROOT}/bl64}"
   [[ "$INST64_BASHLIB64_METHOD" != 'BINARY' ]] &&
     echo 'Error: unsupported installation method' &&
     return 1
@@ -224,10 +229,14 @@ function inst64_bashlib64_initialize() {
   elif command -v 'wget' >/dev/null 2>&1; then
     INST64_BASHLIB64_DOWNLOAD_TOOL='wget'
   else
-    echo 'Error: no donwload tool found (curl, wget)'
+    echo 'Error: no download tool found (curl, wget)'
     return 1
   fi
 
+  if ! command -v 'tar' >/dev/null 2>&1; then
+    echo 'Error: no archive tool found (tar)'
+    return 1
+  fi
 }
 
 #
diff --git a/src/install-installer64 b/src/install-installer64
--- a/src/install-installer64
+++ b/src/install-installer64
@@ -1,21 +1,11 @@
 #!/usr/bin/env bash
 # Template: 1.3.0
 #######################################
-# Installer64 / Package installer
-#
-# Author: SerDigital64 (https://github.com/serdigital64)
-# Repository: https://github.com/automation64/installer64
-# Version: 2.2.0
-#
-#######################################
-# Copyright [2023] [serdigital64@gmail.com]
+# Copyright SerDigital64 - https://github.com/serdigital64
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#     http://www.apache.org/licenses/LICENSE-2.0
-#
+# You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
@@ -24,34 +14,35 @@
 #######################################
 
 #
-# Imports
-#
-
-# Enable debugging? Set to YES to enable
-export INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for 3rd party applications
-export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
-
-#
 # Globals
 #
 
+# Home root
+declare INST64_HOME="${HOME}/at64"
+
+# Enable debugging? Set to YES to enable
+declare INST64_DEBUG="${INST64_DEBUG:-}"
+# Base path for 3rd party applications
+declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
+# Install system wide? Requires root privilege
+declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-NO}"
+
 # Installation method
-export INST64_INSTALLER64_METHOD="${INST64_INSTALLER64_METHOD:-BINARY}"
+declare INST64_INSTALLER64_METHOD="${INST64_INSTALLER64_METHOD:-BINARY}"
 # Source repository
-export INST64_INSTALLER64_SOURCE="${INST64_INSTALLER64_SOURCE:-https://github.com/automation64/installer64}"
+declare INST64_INSTALLER64_SOURCE="${INST64_INSTALLER64_SOURCE:-https://github.com/automation64/installer64}"
 # Target installation directory
-export INST64_INSTALLER64_TARGET="${INST64_INSTALLER64_TARGET:-${INST64_OPT_ROOT}/installer64}"
+declare INST64_INSTALLER64_TARGET="${INST64_INSTALLER64_TARGET:-}"
 # Target application version
-export INST64_INSTALLER64_VERSION="${INST64_INSTALLER64_VERSION:-latest}"
+declare INST64_INSTALLER64_VERSION="${INST64_INSTALLER64_VERSION:-latest}"
 
-export INST64_INSTALLER64_DOWNLOAD_TOOL='none'
-export INST64_INSTALLER64_GH_API='https://api.github.com/repos/automation64/installer64/releases/latest'
-export INST64_INSTALLER64_PACKAGES=''
-export INST64_INSTALLER64_TARGET_MODE_DIR='0755'
-export INST64_INSTALLER64_TARGET_MODE_FILE='0755'
+declare INST64_INSTALLER64_DOWNLOAD_TOOL='none'
+declare INST64_INSTALLER64_GH_API='https://api.github.com/repos/automation64/installer64/releases/latest'
+declare INST64_INSTALLER64_PACKAGES=''
+declare INST64_INSTALLER64_TARGET_MODE_DIR='0755'
+declare INST64_INSTALLER64_TARGET_MODE_FILE='0755'
 
-export INST64_INSTALLER64_VERSION_FILE="${INST64_INSTALLER64_TARGET}/version"
+declare INST64_INSTALLER64_VERSION_FILE=''
 
 #
 # Functions
@@ -141,7 +132,7 @@ function inst64_installer64_install() {
   inst64_installer64_select_packages || return $?
   if [[ "$INST64_INSTALLER64_METHOD" == 'BINARY' ]]; then
     inst64_installer64_install_binary_release &&
-    "${INST64_INSTALLER64_TARGET}/install-bashlib64"
+      "${INST64_INSTALLER64_TARGET}/install-bashlib64"
   fi
 }
 
@@ -205,7 +196,7 @@ function inst64_installer64_verify() {
   echo 'Task: verify deployment'
   [[ -x "${INST64_INSTALLER64_TARGET}/install-installer64" ]] &&
     [[ -x "${INST64_INSTALLER64_TARGET}/install-bashlib64" ]] &&
-    echo "$INST64_INSTALLER64_VERSION" > "$INST64_INSTALLER64_VERSION_FILE"
+    echo "$INST64_INSTALLER64_VERSION" >"$INST64_INSTALLER64_VERSION_FILE"
 }
 
 #######################################
@@ -220,6 +211,16 @@ function inst64_installer64_verify() {
 #   >: failed to initialize
 #######################################
 function inst64_installer64_initialize() {
+  if [[ "$INST64_SYSTEM_WIDE" == 'YES' ]]; then
+    INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
+  else
+    INST64_OPT_ROOT="${INST64_OPT_ROOT:-$INST64_HOME}"
+    if [[ ! -d "$INST64_OPT_ROOT" ]]; then
+      mkdir "$INST64_OPT_ROOT" ||
+        return $?
+    fi
+  fi
+  INST64_INSTALLER64_TARGET="${INST64_INSTALLER64_TARGET:-${INST64_OPT_ROOT}/inst64}"
   [[ "$INST64_INSTALLER64_METHOD" != 'BINARY' ]] &&
     echo 'Error: unsupported installation method' &&
     return 1
@@ -229,10 +230,15 @@ function inst64_installer64_initialize() {
   elif command -v 'wget' >/dev/null 2>&1; then
     INST64_INSTALLER64_DOWNLOAD_TOOL='wget'
   else
-    echo 'Error: no donwload tool found (curl, wget)'
+    echo 'Error: no download tool found (curl, wget)'
     return 1
   fi
 
+  if ! command -v 'tar' >/dev/null 2>&1; then
+    echo 'Error: no archive tool found (tar)'
+    return 1
+  fi
+  INST64_INSTALLER64_VERSION_FILE="${INST64_INSTALLER64_TARGET}/version"
 }
 
 #
