feat: Add Fedora support (#83)

diff --git a/src/install-mkdocs b/src/install-mkdocs
--- a/src/install-mkdocs
+++ b/src/install-mkdocs
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
-# Template: 2.0.0
+# Template: 2.3.0
+# Snippet: install-python-3.2.2
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 2.1.1
+# Version: 2.2.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,6 +30,20 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-py.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -40,20 +55,15 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=SCRIPTDIR/../lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
+# X_GLOBALS_PLACEHOLDER_X
+export INST64_MKDOCS_VERSION="${INST64_MKDOCS_VERSION:-latest}"
 # Installation method
 export INST64_MKDOCS_METHOD="${INST64_MKDOCS_METHOD:-PIP}"
-export INST64_MKDOCS_VERSION="${INST64_MKDOCS_VERSION:-latest}"
-export INST64_MKDOCS_PIPX_BIN='/usr/bin/pipx'
+
+export INST64_MKDOCS_PIPX_BIN="${INST64_MKDOCS_PIPX_BIN:-pipx}"
 export INST64_MKDOCS_PACKAGES=''
 export INST64_MKDOCS_CLI_NAME='mkdocs'
+export INST64_MKDOCS_CLI_PATH=''
 
 #
 # Functions
@@ -61,15 +71,27 @@ export INST64_MKDOCS_CLI_NAME='mkdocs'
 
 function inst64_mkdocs_install_with_pip() {
   bl64_dbg_app_show_function
-  # shellcheck disable=SC2086
-  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
-    bl64_py_pip_usr_install $INST64_MKDOCS_PACKAGES
+
+  bl64_msg_show_task 'deploy application'
+  INST64_MKDOCS_CLI_PATH="${HOME}/.local/bin/${INST64_MKDOCS_CLI_NAME}"
+  if bl64_os_match "${BL64_OS_ALP}"; then
+    # shellcheck disable=SC2086
+    bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
+      bl64_py_pip_usr_install $INST64_MKDOCS_PACKAGES
+  else
+    # shellcheck disable=SC2086
+    bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
+      bl64_py_pip_usr_deploy $INST64_MKDOCS_PACKAGES
+  fi
 }
 
 function inst64_mkdocs_install_with_pipx() {
   bl64_dbg_app_show_function
+
+  bl64_msg_show_task 'deploy application'
+  INST64_MKDOCS_CLI_PATH="${INST64_MKDOCS_CLI_NAME}"
   # shellcheck disable=SC2086
-  pipx install $INST64_MKDOCS_PACKAGES
+  "$INST64_MKDOCS_PIPX_BIN" install $INST64_MKDOCS_PACKAGES
 }
 
 #######################################
@@ -85,8 +107,6 @@ function inst64_mkdocs_install_with_pipx() {
 #######################################
 function inst64_mkdocs_install() {
   bl64_dbg_app_show_function
-  inst64_mkdocs_select_packages || return $?
-  bl64_msg_show_task 'deploy application'
   if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' ]]; then
     inst64_mkdocs_install_with_pipx
   elif [[ "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
@@ -107,6 +127,7 @@ function inst64_mkdocs_install() {
 #######################################
 function inst64_mkdocs_select_packages() {
   bl64_dbg_app_show_function
+  local version_legacy='X_LEGACY_VERSION_X'
   local version_target=''
 
   if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' || "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
@@ -115,7 +136,8 @@ function inst64_mkdocs_select_packages() {
     else
       version_target="==${INST64_MKDOCS_VERSION}.*"
     fi
-    INST64_MKDOCS_PACKAGES="mkdocs${version_target}"
+    INST64_MKDOCS_PACKAGES+=" packages"
+    INST64_MKDOCS_PACKAGES+=" mkdocs${version_target}"
     INST64_MKDOCS_PACKAGES+=' Markdown'
     INST64_MKDOCS_PACKAGES+=' mdx-truly-sane-lists'
     INST64_MKDOCS_PACKAGES+=' mkdocs-autorefs'
@@ -148,7 +170,10 @@ function inst64_mkdocs_select_packages() {
 function inst64_mkdocs_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_py_setup
+  inst64_mkdocs_select_packages || return $?
+  if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' || "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
+    bl64_py_setup
+  fi
 }
 
 #######################################
@@ -165,9 +190,7 @@ function inst64_mkdocs_prepare() {
 function inst64_mkdocs_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  if [[ "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
-    "${HOME}/.local/bin/${INST64_MKDOCS_CLI_NAME}" --version
-  fi
+  "$INST64_MKDOCS_CLI_PATH" --version
 }
 
 #######################################
@@ -183,13 +206,22 @@ function inst64_mkdocs_verify() {
 #######################################
 function inst64_mkdocs_initialize() {
   bl64_dbg_app_show_function
-  bl64_os_check_compatibility \
-    "${BL64_OS_ALP}-3" \
-    "${BL64_OS_UB}-22" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_MKDOCS_METHOD' \
-      "$INST64_MKDOCS_METHOD" \
-      'PIP' 'PIPX' &&
-    bl64_check_privilege_not_root
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_MKDOCS_METHOD' \
+    "$INST64_MKDOCS_METHOD" \
+    'PIP' 'PIPX' ||
+    return $?
+
+  if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' || "$INST64_MKDOCS_METHOD" == 'PIP' ]]; then
+    if [[ "$INST64_MKDOCS_METHOD" == 'PIPX' ]]; then
+      bl64_bsh_command_is_executable "$INST64_MKDOCS_PIPX_BIN" ||
+        return $?
+    fi
+    bl64_check_privilege_not_root &&
+      bl64_os_check_compatibility \
+        "${BL64_OS_ALP}" \
+        "${BL64_OS_FD}" \
+        "${BL64_OS_UB}-22"
+  fi
 }
 
 #
