feat: promote 3.7.0 (#45)
## [3.7.0]

### Added

- Installers:
  - Minikube
  - Kube-Linter
  - Helm Chart Tester

### Changed

- Helm
  - Enabled support for Alpine3

diff --git a/src/install-helm b/src/install-helm
--- a/src/install-helm
+++ b/src/install-helm
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 1.2.0
+# Template: 2.0.1
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.2.0
+# Version: 1.3.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -47,57 +47,50 @@ source "${INST64_BASHLIB64}/bashlib64.bash" ||
 #
 
 export INST64_HELM_PLATFORM="${INST64_HELM_PLATFORM:-linux-amd64}"
-export INST64_HELM_SOURCE="${INST64_HELM_SOURCE:-https://get.helm.sh}"
 export INST64_HELM_TARGET="${INST64_HELM_TARGET:-${INST64_OPT_ROOT}/helm}"
 export INST64_HELM_VERSION="${INST64_HELM_VERSION:-latest}"
 # Installation method
 export INST64_HELM_METHOD="${INST64_HELM_METHOD:-BINARY}"
+export INST64_HELM_SOURCE="${INST64_HELM_SOURCE:-https://get.helm.sh}"
 
 export INST64_HELM_REPO_NAME='helm'
 export INST64_HELM_REPO_OWNER='helm'
+export INST64_HELM_PACKAGES=''
+export INST64_HELM_CLI_NAME='helm'
+
+#
+# Functions
+#
 
 function inst64_helm_install_binary_release() {
   bl64_dbg_app_show_function
-  local package_prefix='helm'
-  local package_sufix='.tar.gz'
-  local package_name=''
-  local package_url="$INST64_HELM_SOURCE"
   local work_path=''
   local app_target_mode='0755'
   local app_target_owner='root'
   local app_cli_mode='0755'
-  local app_cli='helm'
+  local app_cli_source="${INST64_HELM_CLI_NAME}"
 
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
-  if [[ "$INST64_HELM_VERSION" == 'latest' ]]; then
-    INST64_HELM_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_HELM_REPO_OWNER" "$INST64_HELM_REPO_NAME")" ||
-      return $?
-  fi
-  package_name="${package_prefix}-${INST64_HELM_VERSION}-${INST64_HELM_PLATFORM}${package_sufix}"
-
-  bl64_rxtx_web_get_file "${package_url}/${package_name}" "${work_path}/${package_name}" &&
-    bl64_arc_open_tar "${work_path}/${package_name}" "${work_path}" ||
+  bl64_rxtx_web_get_file \
+    "${INST64_HELM_PACKAGE_URL}/${INST64_HELM_PACKAGES}" "${work_path}/${INST64_HELM_PACKAGES}" &&
+    bl64_arc_open_tar "${work_path}/${INST64_HELM_PACKAGES}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
   bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" &&
-    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" "${work_path}/${INST64_HELM_PLATFORM}/${app_cli}" ||
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_HELM_TARGET" "${work_path}/${INST64_HELM_PLATFORM}/${app_cli_source}" ||
     return $?
 
   bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
   # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_HELM_TARGET}/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" "$BL64_VAR_ON" ||
+  bl64_fs_create_symlink "${INST64_HELM_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_HELM_CLI_NAME}" "$BL64_VAR_ON" ||
     return $?
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
   return 0
 }
-
-#
-# Functions
-#
 
 #######################################
 # Install application packages
@@ -112,8 +105,74 @@ function inst64_helm_install_binary_release() {
 #######################################
 function inst64_helm_install() {
   bl64_dbg_app_show_function
+  inst64_helm_select_packages || return $?
   if [[ "$INST64_HELM_METHOD" == 'BINARY' ]]; then
     inst64_helm_install_binary_release
+  fi
+}
+
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_helm_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_HELM_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_HELM_VERSION" == 'latest' ]]; then
+      INST64_HELM_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_HELM_REPO_OWNER" "$INST64_HELM_REPO_NAME")" ||
+        return $?
+    fi
+    package_prefix='helm-'
+    package_sufix='.tar.gz'
+    INST64_HELM_PACKAGES="${package_prefix}${INST64_HELM_VERSION}-${INST64_HELM_PLATFORM}${package_sufix}"
+    INST64_HELM_PACKAGE_URL="$INST64_HELM_SOURCE"
+  fi
+  [[ -z "$INST64_HELM_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  return 0
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_helm_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  bl64_arc_setup
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_helm_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  if [[ "$INST64_HELM_METHOD" == 'BINARY' ]]; then
+    "${INST64_LOCAL_BIN}/${INST64_HELM_CLI_NAME}" version
   fi
 }
 
@@ -126,15 +185,14 @@ function inst64_helm_install() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_helm_initialize() {
   bl64_dbg_app_show_function
-
-  bl64_arc_setup &&
-    bl64_os_check_version \
-      "${BL64_OS_UB}-22" \
-      "${BL64_OS_OL}-9" &&
+  bl64_os_check_version \
+    "${BL64_OS_ALP}-3" \
+    "${BL64_OS_UB}-22" \
+    "${BL64_OS_OL}-9" &&
     bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_HELM_METHOD' \
       "$INST64_HELM_METHOD" \
       'BINARY' &&
@@ -152,6 +210,7 @@ bl64_msg_show_batch_start "$inst64_helm_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_helm_initialize &&
-  inst64_helm_install
-
+  inst64_helm_prepare &&
+  inst64_helm_install &&
+  inst64_helm_verify
 bl64_msg_show_batch_finish $? "$inst64_helm_installer_description"
