real: promote 6.0.14 (#136)

diff --git a/src/install-nvm b/src/install-nvm
--- a/src/install-nvm
+++ b/src/install-nvm
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
-# Template: legacy
-# Template: install-git-2.4.0
-#   Skeleton: installer-base-2.4.0
+# Template: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -19,230 +17,155 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_GIT_SERVER="${INST64_GIT_SERVER:-https://github.com/nvm-sh}"
-declare INST64_GIT_REPO="${INST64_GIT_REPO:-nvm.git}"
-declare INST64_NVM_TARGET=''
-declare INST64_GIT_BRANCH="${INST64_GIT_BRANCH:-master}"
 # Installation method
-declare INST64_NVM_METHOD="${INST64_NVM_METHOD:-GIT}"
+declare INST64_NVM_METHOD="${INST64_NVM_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_NVM_TARGET="${INST64_NVM_TARGET:-}"
+# Hardware architecture
+declare INST64_NVM_PLATFORM='ALL'
+# Application version
+declare INST64_NVM_VERSION="${INST64_NVM_VERSION:-latest}"
 
-declare INST64_APP_INSTALLER=''
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='nvm.sh'
-declare INST64_CLI_PATH=''
+INST64_APP_NAME='nvm'
+INST64_APP_ID='NVM'
+INST64_APP_FULL_NAME='NVM - Node Version Manager'
+INST64_CLI_NAME='nvm.sh'
+
+INST64_GIT_SERVER='https://github.com/nvm-sh'
+INST64_GIT_REPO='nvm.git'
+INST64_GIT_BRANCH='master'
+
+INST64_ROOT_PATH_DEFAULT_USER="$HOME"
+INST64_TARGET_PATH_DEFAULT_USER='.nvm'
 
 #
 # Functions
 #
 
-function inst64_install_git_repo() {
+function inst64_install_custom() {
   bl64_dbg_app_show_function
-  local app_target_mode='0755'
-  local app_target_owner="$BL64_IAM_SYSTEM_USER"
-  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
-  local app_cli_source="${INST64_CLI_NAME}"
 
-  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    app_target_owner="$BL64_VAR_DEFAULT"
-    app_target_group="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  bl64_rxtx_git_get_dir \
-    "${INST64_GIT_SERVER}/${INST64_GIT_REPO}" \
-    '.' \
-    "$INST64_NVM_TARGET" \
-    "$BL64_VAR_ON" \
-    "$INST64_GIT_BRANCH" ||
+  inst64_lib_task_download
+  inst64_lib_staging_create &&
+    inst64_lib_git_get_dir ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  if [[ -n "$INST64_APP_INSTALLER" ]]; then
-    "$INST64_APP_INSTALLER" ||
-      return $?
-  fi
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_fs_path_permission_set "$app_target_mode" "$app_target_mode" "$app_target_owner" "$app_target_group" "$BL64_VAR_ON" \
-      "$INST64_NVM_TARGET" ||
-      return $?
-  fi
+  inst64_lib_task_deploy
+  inst64_lib_target_normalize &&
+    inst64_lib_cli_normalize ||
+    return $?
 
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_msg_show_task "publish application to searchable path (${INST64_CLI_PATH})"
-    # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${INST64_NVM_TARGET}/${app_cli_source}" "$INST64_CLI_PATH" "$BL64_VAR_ON" ||
-      return $?
-  fi
-
-  return 0
+  inst64_lib_task_cleanup
+  inst64_lib_staging_remove
 }
 
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_NVM_METHOD" == 'GIT' ]]; then
-    inst64_install_git_repo
-  fi
-}
-
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
-function inst64_select_packages() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_NVM_METHOD" == 'GIT' ]]; then
-    INST64_PKG_MAIN='NONE'
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_CLI_NAME}"
-    else
-      INST64_CLI_PATH="${INST64_NVM_TARGET}/${INST64_CLI_NAME}"
-    fi
-  fi
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
-}
-
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
 function inst64_prepare() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_NVM_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_base_create_path
+  fi
 }
 
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_NVM_METHOD" == 'CUSTOM' ]]; then
+    inst64_install_custom
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_NVM_METHOD" == 'CUSTOM' ]]; then
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
+  fi
+}
+
 function inst64_verify() {
   bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
+  inst64_lib_step_verify || return 0
   [[ -s "$INST64_CLI_PATH" ]]
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'CUSTOM' ||
+    return $?
+  if [[ "$INST64_NVM_METHOD" == 'AUTO' ]]; then
+    INST64_NVM_METHOD='CUSTOM'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  return 0
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  return 0
+}
+
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    INST64_NVM_TARGET="${INST64_NVM_TARGET:-${INST64_OPT_ROOT}/nvm}"
-  else
-    INST64_NVM_TARGET="${INST64_NVM_TARGET:-${HOME}/.nvm}"
-  fi
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_NVM_METHOD' \
-    "$INST64_NVM_METHOD" \
-    'GIT' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method &&
+    inst64_lib_method_initialize ||
     return $?
 
-  if [[ "$INST64_NVM_METHOD" == 'GIT' ]]; then
+  if [[ "$INST64_NVM_METHOD" == 'CUSTOM' ]]; then
     if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
       bl64_check_privilege_root ||
         return $?
     fi
+    bl64_arc_setup ||
+      return $?
   fi
-  inst64_select_packages ||
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
 
-  bl64_msg_show_setup 'Install application: Node Version Manager (NVM)' \
-    'INST64_SYSTEM_WIDE' 'INST64_NVM_METHOD' \
-    'INST64_GIT_SERVER' \
-    'INST64_GIT_REPO' \
-    'INST64_GIT_BRANCH' \
-    'INST64_NVM_TARGET' \
-    'INST64_CLI_PATH'
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.0.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -250,5 +173,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
diff --git a/src/lib-bl64 b/src/lib-bl64
--- a/src/lib-bl64
+++ b/src/lib-bl64
@@ -41,16 +41,12 @@
   declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
   # Replace if already installed?
   declare INST64_REPLACE_INSTALLED="${INST64_REPLACE_INSTALLED:-NO}"
+  # Refresh package manager before installation and cleanup after?
+  declare INST64_REFRESH_PACKAGE_MANAGER="${INST64_REFRESH_PACKAGE_MANAGER:-YES}"
 
   #
   # Global definitions
   #
-
-  # Inst64 Library version
-  declare INST64_LIB_VERSION_BL64='1.0.0'
-
-  # User wide home path
-  declare INST64_HOME="${HOME}/at64"
 
   # App information
   declare INST64_APP_NAME=''
@@ -61,18 +57,19 @@
   # Method definitions
   #
 
+  # Base target configuration
+  declare INST64_ROOT_PATH_DEFAULT_SYSTEM=''
+  declare INST64_ROOT_PATH_DEFAULT_USER=''
+
   # Target configuration
-  declare INST64_TARGET_DEFAULT=''
+  declare INST64_TARGET_PATH_DEFAULT=''
+  declare INST64_TARGET_PATH_DEFAULT_SYSTEM=''
+  declare INST64_TARGET_PATH_DEFAULT_USER=''
   declare INST64_TARGET_OWNER="$BL64_IAM_SYSTEM_USER"
   declare INST64_TARGET_GROUP="$BL64_IAM_SYSTEM_GROUP"
   declare INST64_TARGET_MODE='0755'
   declare INST64_TARGET_MODE_DIR='0755'
   declare INST64_TARGET_MODE_FILE='0644'
-  declare INST64_TARGET_REQUESTED='NO'
-
-  # Install progress status
-  declare INST64_STATUS_FLAG='CONTINUE'
-  declare INST64_STATUS_PATH=''
 
   # Work paths
   declare INST64_WORK_PATH_SOURCE=''
@@ -119,10 +116,31 @@
 
   # OS package manager information
   declare INST64_OS_REPO_NAME=''
-  declare INST64_OS_SOURCE_YUM='X_REPO_URL_X'
-  declare INST64_OS_SOURCE_APT='X_REPO_URL_X'
-  declare INST64_OS_REPOSITORY_KEY_YUM='X_KEY_URL_X'
-  declare INST64_OS_REPOSITORY_KEY_APT='X_KEY_URL_X'
+  declare INST64_OS_SOURCE_YUM=''
+  declare INST64_OS_SOURCE_APT=''
+  declare INST64_OS_REPO_KEY_YUM=''
+  declare INST64_OS_REPO_KEY_APT=''
+
+  #
+  # Internal variables
+  #
+
+  # Inst64 Library version
+  declare INST64_LIB_VERSION_BL64='1.0.0'
+
+  # User wide home path
+  declare INST64_HOME="${HOME}/at64"
+
+  # Install progress status
+  declare INST64_STATUS_FLAG='CONTINUE'
+  declare INST64_STATUS_PATH=''
+
+  # Target management
+  declare INST64_TARGET_REQUESTED='NO'
+
+  # External commands
+  declare INST64_COMMAND_PIPX=''
+  declare INST64_COMMAND_NPM=''
 }
 
 #
@@ -134,8 +152,26 @@
 #######################################
 function inst64_lib_base_set_system_wide() {
   bl64_dbg_app_show_function
+  local method="INST64_${INST64_APP_ID}_METHOD"
   if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d '/opt/bl64' || -d '/opt/inst64' ]] && INST64_SYSTEM_WIDE='YES' || INST64_SYSTEM_WIDE='NO'
+    case "${!method}" in
+    'PIP' | 'PIPX')
+      INST64_SYSTEM_WIDE='NO'
+      ;;
+    'NPM')
+      INST64_SYSTEM_WIDE='NO'
+      ;;
+    'NATIVE')
+      INST64_SYSTEM_WIDE='YES'
+      ;;
+    *)
+      if [[ -d '/opt/bl64' || -d '/opt/inst64' ]]; then
+        INST64_SYSTEM_WIDE='YES'
+      else
+        INST64_SYSTEM_WIDE='NO'
+      fi
+      ;;
+    esac
   fi
 }
 
@@ -146,9 +182,17 @@ function inst64_lib_base_set_path() {
   bl64_dbg_app_show_function
   if [[ -z "$INST64_OPT_ROOT" ]]; then
     if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_OPT_ROOT='/opt'
+      if [[ -n "$INST64_ROOT_PATH_DEFAULT_SYSTEM" ]]; then
+        INST64_OPT_ROOT="$INST64_ROOT_PATH_DEFAULT_SYSTEM"
+      else
+        INST64_OPT_ROOT='/opt'
+      fi
     else
-      INST64_OPT_ROOT="$INST64_HOME"
+      if [[ -n "$INST64_ROOT_PATH_DEFAULT_USER" ]]; then
+        INST64_OPT_ROOT="$INST64_ROOT_PATH_DEFAULT_USER"
+      else
+        INST64_OPT_ROOT="$INST64_HOME"
+      fi
     fi
   fi
 }
@@ -162,7 +206,16 @@ function inst64_lib_target_set_path() {
   local target_basename="$INST64_APP_NAME"
 
   if [[ -z "${!target}" ]]; then
-    [[ -n "$INST64_TARGET_DEFAULT" ]] && target_basename="$INST64_TARGET_DEFAULT"
+    if [[ -n "$INST64_TARGET_PATH_DEFAULT" ]]; then
+      target_basename="$INST64_TARGET_PATH_DEFAULT"
+    else
+      if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+        [[ -n "$INST64_TARGET_PATH_DEFAULT_SYSTEM" ]] && target_basename="$INST64_TARGET_PATH_DEFAULT_SYSTEM"
+      else
+        [[ -n "$INST64_TARGET_PATH_DEFAULT_USER" ]] && target_basename="$INST64_TARGET_PATH_DEFAULT_USER"
+      fi
+    fi
+
     printf \
       -v "INST64_${INST64_APP_ID}_TARGET" \
       '%s/%s' \
@@ -195,19 +248,28 @@ function inst64_lib_cli_set_path() {
   local method="INST64_${INST64_APP_ID}_METHOD"
 
   [[ -n "$INST64_CLI_PATH" ]] && return 0
-  if [[ "${!method}" == 'PIPX' ]]; then
+  # shellcheck disable=SC2249
+  case "${!method}" in
+  'NPM')
+    INST64_CLI_PATH="${HOME}/node_modules/.bin"
+    ;;
+  'PIPX')
     INST64_CLI_PATH="${HOME}/.local/bin"
-  elif [[ "${!method}" == 'PIP' ]]; then
+    ;;
+  'PIP')
     INST64_CLI_PATH="${BL64_PY_PATH_PIP_USR_BIN}"
-  elif [[ "${!method}" == 'NATIVE' ]]; then
+    ;;
+  'NATIVE')
     INST64_CLI_PATH='/usr/bin'
-  elif [[ "${!method}" == 'BINARY' || "${!method}" == 'CUSTOM' ]]; then
+    ;;
+  'BINARY' | 'CUSTOM')
     if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
       INST64_CLI_PATH="${INST64_LOCAL_BIN}"
     else
       INST64_CLI_PATH="${INST64_USER_BIN}"
     fi
-  fi
+    ;;
+  esac
 }
 
 #######################################
@@ -255,21 +317,29 @@ function inst64_lib_message_show_parameters() {
   local var_suffix=''
   local var_name=''
 
+  parameter_list+=' BL64_OS_DISTRO'
+
   method_variable_suffix+=" ${INST64_APP_ID}_METHOD"
   method_variable_suffix+=" ${INST64_APP_ID}_PLATFORM"
   method_variable_suffix+=" ${INST64_APP_ID}_TARGET"
   method_variable_suffix+=" ${INST64_APP_ID}_VERSION"
-  method_variable_suffix+=" SYSTEM_WIDE"
   method_variable_suffix+=" CLI_NAME"
   method_variable_suffix+=" CLI_PATH"
   method_variable_suffix+=" GH_REPO_NAME"
   method_variable_suffix+=" GH_REPO_OWNER"
-  method_variable_suffix+=" PKG_MAIN"
-  method_variable_suffix+=" PKG_DEV"
   method_variable_suffix+=" GIT_BRANCH"
   method_variable_suffix+=" GIT_REPO"
   method_variable_suffix+=" GIT_SERVER"
+  method_variable_suffix+=" PKG_DEV"
+  method_variable_suffix+=" PKG_MAIN"
   method_variable_suffix+=" OS_REPO_NAME"
+  method_variable_suffix+=" OS_REPO_KEY_YUM"
+  method_variable_suffix+=" OS_REPO_KEY_APT"
+  method_variable_suffix+=" OS_SOURCE_APT"
+  method_variable_suffix+=" OS_SOURCE_YUM"
+  method_variable_suffix+=" REPLACE_INSTALLED"
+  method_variable_suffix+=" REFRESH_PACKAGE_MANAGER"
+  method_variable_suffix+=" SYSTEM_WIDE"
   method_variable_suffix+=" WEB_REPO_PATH"
   method_variable_suffix+=" WEB_REPO_URL"
 
@@ -330,7 +400,7 @@ function inst64_lib_base_initialize() {
 
   bl64_dbg_app_show_comments 'Set default value for INST64_CLI_NAME'
   INST64_WORK_PATH_SOURCE="$INST64_CLI_NAME"
-  # shellcheck disable=SC2015
+
   inst64_lib_base_set_system_wide &&
     inst64_lib_base_set_path &&
     inst64_lib_target_set_owner &&
@@ -339,6 +409,53 @@ function inst64_lib_base_initialize() {
 
   inst64_lib_message_show_error 'installer initialization failed'
   return $BL64_LIB_ERROR_TASK_FAILED
+}
+
+function inst64_lib_method_initialize() {
+  bl64_dbg_app_show_function
+  local method="INST64_${INST64_APP_ID}_METHOD"
+  # shellcheck disable=SC2249
+  case "${!method}" in
+  'PIP')
+    bl64_check_privilege_not_root &&
+      bl64_py_setup
+    ;;
+  'NATIVE')
+    bl64_check_privilege_root &&
+      bl64_cryp_setup &&
+      bl64_pkg_setup
+    ;;
+  'BINARY')
+    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_arc_setup
+    ;;
+  'PIPX')
+    bl64_check_privilege_not_root &&
+      bl64_py_setup ||
+      return $?
+
+    INST64_COMMAND_PIPX="$(bl64_bsh_command_locate 'pipx' "$HOME/.local/bin")"
+    if [[ -z "$INST64_COMMAND_PIPX" ]]; then
+      bl64_msg_show_error 'pipx command not found. Please install pipx and try again'
+      return 1
+    fi
+    return 0
+    ;;
+  'NPM')
+    bl64_check_privilege_not_root ||
+      return $?
+
+    INST64_COMMAND_NPM="$(bl64_bsh_command_locate 'npm' "$HOME/.local/bin")"
+    if [[ -z "$INST64_COMMAND_NPM" ]]; then
+      bl64_msg_show_error 'npm command not found. Please install npm and try again'
+      return 1
+    fi
+    return 0
+    ;;
+  esac
 }
 
 function inst64_lib_step_prepare() {
@@ -439,16 +556,18 @@ function inst64_lib_python_install_pipx() {
 
 function inst64_lib_command_run_pipx() {
   bl64_dbg_app_show_function "$@"
-  local command_pipx=''
-
-  command_pipx="$(bl64_bsh_command_locate 'pipx' "$HOME/.local/bin")"
-  [[ -z "$command_pipx" ]] &&
-    bl64_msg_show_error 'pipx command not found. Please install pipx and try again' &&
-    return 1
-
   bl64_dbg_app_trace_start
   # shellcheck disable=SC2086
-  "$command_pipx" \
+  "$INST64_COMMAND_PIPX" \
+    "$@"
+  bl64_dbg_app_trace_stop
+}
+
+function inst64_lib_command_run_npm() {
+  bl64_dbg_app_show_function "$@"
+  bl64_dbg_app_trace_start
+  # shellcheck disable=SC2086
+  "$INST64_COMMAND_NPM" \
     "$@"
   bl64_dbg_app_trace_stop
 }
@@ -626,4 +745,54 @@ function inst64_lib_web_get_file() {
     "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
     'YES' \
     "$INST64_CLI_MODE"
+}
+
+function inst64_lib_pkg_install() {
+  bl64_dbg_app_show_function
+  # shellcheck disable=SC2086
+  if bl64_lib_flag_is_enabled "$INST64_REFRESH_PACKAGE_MANAGER"; then
+    bl64_pkg_deploy $INST64_PKG_MAIN
+  else
+    bl64_pkg_install $INST64_PKG_MAIN
+  fi
+}
+
+function inst64_lib_pkg_repo_add() {
+  bl64_dbg_app_show_function
+  local repository_url="${1:-}"
+  local repository_key="${2:-}"
+  local repository_apt_suite="${3:-}"
+  local repository_apt_component="${4:-}"
+
+  bl64_msg_show_task 'Add external package repository'
+  bl64_pkg_repository_add "$INST64_OS_REPO_NAME" \
+    "$repository_url" "$repository_key" \
+    "$repository_apt_suite" "$repository_apt_component" ||
+    return $?
+
+  if ! bl64_lib_flag_is_enabled "$INST64_REFRESH_PACKAGE_MANAGER"; then
+    bl64_pkg_prepare
+  fi
+}
+
+function inst64_lib_python_install_npm() {
+  bl64_dbg_app_show_function
+
+  bl64_msg_show_task 'deploy application'
+  cd "$HOME" || return $?
+  if [[ -n "$INST64_PKG_PRE" ]]; then
+    # shellcheck disable=SC2086
+    inst64_lib_command_run_npm install $INST64_PKG_PRE $INST64_PKG_MAIN ||
+      return $?
+  else
+    # shellcheck disable=SC2086
+    inst64_lib_command_run_npm install $INST64_PKG_MAIN ||
+      return $?
+  fi
+  if [[ -n "$INST64_PKG_POST" ]]; then
+    # shellcheck disable=SC2086
+    inst64_lib_command_run_npm inject $INST64_PKG_POST ||
+      return $?
+  fi
+  return 0
 }
