feat: promote 3.22.0 (#65)

diff --git a/src/install-hadolint b/src/install-hadolint
--- a/src/install-hadolint
+++ b/src/install-hadolint
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
-# Template: 2.0.0
+# Template: 2.2.0
+# Snippet: install-github-release-3.2.1
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.4.0
+# Version: 1.5.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,10 +30,23 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -42,25 +56,19 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-export INST64_HADOLINT_PLATFORM="${INST64_HADOLINT_PLATFORM:-Linux-x86_64}"
+export INST64_HADOLINT_PLATFORM="${INST64_HADOLINT_PLATFORM:-}"
 export INST64_HADOLINT_TARGET="${INST64_HADOLINT_TARGET:-${INST64_OPT_ROOT}/hadolint}"
 export INST64_HADOLINT_VERSION="${INST64_HADOLINT_VERSION:-latest}"
+# Install system wide? Requires root privilege
+export INST64_HADOLINT_SYSTEM_WIDE="${INST64_HADOLINT_SYSTEM_WIDE:-YES}"
 # Installation method
 export INST64_HADOLINT_METHOD="${INST64_HADOLINT_METHOD:-BINARY}"
 
 export INST64_HADOLINT_REPO_NAME='hadolint'
 export INST64_HADOLINT_REPO_OWNER='hadolint'
-
 export INST64_HADOLINT_PACKAGES=''
 export INST64_HADOLINT_CLI_NAME='hadolint'
+export INST64_HADOLINT_CLI_PATH=''
 
 #
 # Functions
@@ -74,6 +82,13 @@ function inst64_hadolint_install_binary_release() {
   local app_cli_mode='0755'
   local app_cli_source="${INST64_HADOLINT_CLI_NAME}-${INST64_HADOLINT_PLATFORM}"
 
+  if bl64_lib_flag_is_enabled "$INST64_HADOLINT_SYSTEM_WIDE"; then
+    INST64_HADOLINT_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_HADOLINT_CLI_NAME}"
+  else
+    INST64_HADOLINT_CLI_PATH="${INST64_HADOLINT_TARGET}/${INST64_HADOLINT_CLI_NAME}"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
+
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" || return $?
   bl64_rxtx_github_get_asset \
@@ -85,13 +100,42 @@ function inst64_hadolint_install_binary_release() {
     bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_HADOLINT_TARGET" "${work_path}/${app_cli_source}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${INST64_HADOLINT_TARGET}/${app_cli_source}" "${INST64_LOCAL_BIN}/${INST64_HADOLINT_CLI_NAME}" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_HADOLINT_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_HADOLINT_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_HADOLINT_TARGET}/${app_cli_source}" "$INST64_HADOLINT_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  else
+    bl64_msg_show_task "publish generic application name (${INST64_HADOLINT_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_HADOLINT_TARGET}/${app_cli_source}" "$INST64_HADOLINT_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_hadolint_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_HADOLINT_METHOD" == 'BINARY' ]]; then
+    [[ -z "$INST64_HADOLINT_PLATFORM" ]] && INST64_HADOLINT_PLATFORM='Linux-x86_64'
+  fi
+  [[ -z "$INST64_HADOLINT_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -108,7 +152,9 @@ function inst64_hadolint_install_binary_release() {
 #######################################
 function inst64_hadolint_install() {
   bl64_dbg_app_show_function
-  inst64_hadolint_select_packages || return $?
+  inst64_hadolint_select_platform &&
+    inst64_hadolint_select_packages ||
+    return $?
   if [[ "$INST64_HADOLINT_METHOD" == 'BINARY' ]]; then
     inst64_hadolint_install_binary_release
   fi
@@ -135,6 +181,7 @@ function inst64_hadolint_select_packages() {
         return $?
     fi
     package_prefix='hadolint'
+    package_sufix=''
     INST64_HADOLINT_PACKAGES="${package_prefix}-${INST64_HADOLINT_PLATFORM}${package_sufix}"
   fi
   [[ -z "$INST64_HADOLINT_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
@@ -155,7 +202,9 @@ function inst64_hadolint_select_packages() {
 function inst64_hadolint_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_arc_setup
+  if [[ "$INST64_HADOLINT_METHOD" == 'BINARY' ]]; then
+    bl64_arc_setup
+  fi
 }
 
 #######################################
@@ -172,7 +221,7 @@ function inst64_hadolint_prepare() {
 function inst64_hadolint_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  "${INST64_LOCAL_BIN}/${INST64_HADOLINT_CLI_NAME}" --version
+  "$INST64_HADOLINT_CLI_PATH" --version
 }
 
 #######################################
@@ -184,25 +233,33 @@ function inst64_hadolint_verify() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_hadolint_initialize() {
   bl64_dbg_app_show_function
-  bl64_os_check_compatibility \
-      "${BL64_OS_OL}-9" \
-      "${BL64_OS_UB}-22" \
-      "${BL64_OS_ALP}-3" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_HADOLINT_METHOD' \
-      "$INST64_HADOLINT_METHOD" \
-      'BINARY' &&
-    bl64_check_privilege_root
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_HADOLINT_METHOD' \
+    "$INST64_HADOLINT_METHOD" \
+    'BINARY' ||
+    return $?
+
+  if [[ "$INST64_HADOLINT_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_HADOLINT_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_UB}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_ALP}"
+  fi
 }
 
 #
 # Main
 #
 
-declare inst64_hadolint_installer_description='Install application: Hadolint'
+declare inst64_hadolint_installer_description='Install application: HadoLint'
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_hadolint_installer_description"
diff --git a/src/install-nodejs b/src/install-nodejs
--- a/src/install-nodejs
+++ b/src/install-nodejs
@@ -1,11 +1,12 @@
 #!/usr/bin/env bash
-# Template: 2.0.1
+# Template: 2.2.0
+# Snippet: install-custom-package-4.2.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.1.0
+# Version: 1.2.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,6 +30,21 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -40,18 +56,12 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
-
-export INST64_NODEJS_PLATFORM="${INST64_NODEJS_PLATFORM:-linux-x64}"
+export INST64_NODEJS_PLATFORM="${INST64_NODEJS_PLATFORM:-}"
 export INST64_NODEJS_SOURCE="${INST64_NODEJS_SOURCE:-https://nodejs.org/dist}"
 export INST64_NODEJS_TARGET="${INST64_NODEJS_TARGET:-${INST64_OPT_ROOT}/nodejs}"
 export INST64_NODEJS_VERSION="${INST64_NODEJS_VERSION:-20.10.0}"
+# Install system wide? Requires root privilege
+export INST64_NODEJS_SYSTEM_WIDE="${INST64_NODEJS_SYSTEM_WIDE:-YES}"
 # Installation method
 export INST64_NODEJS_METHOD="${INST64_NODEJS_METHOD:-CUSTOM}"
 
@@ -61,6 +71,7 @@ export INST64_NODEJS_PACKAGES=''
 export INST64_NODEJS_CLI_NAME_NODE='node'
 export INST64_NODEJS_CLI_NAME_NPM='npm'
 export INST64_NODEJS_CLI_NAME_NPX='npx'
+export INST64_NODEJS_CLI_PATH=''
 
 #
 # Functions
@@ -74,9 +85,17 @@ function inst64_nodejs_install_custom_package() {
   local app_cli_source="${INST64_NODEJS_PACKAGES%.tar.gz}/bin"
   local app_component=''
 
+  if bl64_lib_flag_is_enabled "$INST64_NODEJS_SYSTEM_WIDE"; then
+    INST64_NODEJS_CLI_PATH="${INST64_LOCAL_BIN}"
+  else
+    INST64_NODEJS_CLI_PATH="${INST64_NODEJS_TARGET}/bin"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
+
   bl64_msg_show_task 'download application'
   work_path="$(bl64_fs_create_tmpdir)" &&
-    bl64_rxtx_web_get_file "${INST64_NODEJS_PACKAGE_URL}/${INST64_NODEJS_PACKAGES}" "${work_path}/${INST64_NODEJS_PACKAGES}" ||
+    bl64_rxtx_web_get_file \
+      "${INST64_NODEJS_PACKAGE_URL}/${INST64_NODEJS_PACKAGES}" "${work_path}/${INST64_NODEJS_PACKAGES}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
@@ -84,15 +103,48 @@ function inst64_nodejs_install_custom_package() {
     bl64_arc_open_tar "${work_path}/${INST64_NODEJS_PACKAGES}" "${INST64_NODEJS_TARGET}" ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
-    bl64_fs_create_symlink \
-      "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_LOCAL_BIN}/${app_component}" "$BL64_VAR_ON" ||
+  if bl64_lib_flag_is_enabled "$INST64_NODEJS_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_NODEJS_CLI_PATH})"
+    for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
+      bl64_fs_create_symlink \
+        "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
+        return $?
+    done
+  else
+    bl64_msg_show_task "publish generic application name (${INST64_NODEJS_CLI_PATH})"
+    bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_NODEJS_CLI_PATH" ||
       return $?
-  done
+    for app_component in "$INST64_NODEJS_CLI_NAME_NODE" "$INST64_NODEJS_CLI_NAME_NPM" "$INST64_NODEJS_CLI_NAME_NPX"; do
+      bl64_fs_create_symlink \
+        "${INST64_NODEJS_TARGET}/${app_cli_source}/$app_component" "${INST64_NODEJS_CLI_PATH}/${app_component}" "$BL64_VAR_ON" ||
+        return $?
+    done
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_nodejs_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
+    [[ -z "$INST64_NODEJS_PLATFORM" ]] && INST64_NODEJS_PLATFORM='linux-x64'
+  fi
+  [[ -z "$INST64_NODEJS_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
   return 0
 }
 
@@ -109,7 +161,9 @@ function inst64_nodejs_install_custom_package() {
 #######################################
 function inst64_nodejs_install() {
   bl64_dbg_app_show_function
-  inst64_nodejs_select_packages || return $?
+  inst64_nodejs_select_platform &&
+    inst64_nodejs_select_packages ||
+    return $?
   if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
     inst64_nodejs_install_custom_package
   fi
@@ -135,6 +189,7 @@ function inst64_nodejs_select_packages() {
     package_sufix='.tar.gz'
     INST64_NODEJS_PACKAGES="${package_prefix}v${INST64_NODEJS_VERSION}-${INST64_NODEJS_PLATFORM}${package_sufix}"
     INST64_NODEJS_PACKAGE_URL="${INST64_NODEJS_SOURCE}/v${INST64_NODEJS_VERSION}"
+    [[ -z "$INST64_NODEJS_PACKAGE_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
   fi
   [[ -z "$INST64_NODEJS_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
@@ -154,7 +209,9 @@ function inst64_nodejs_select_packages() {
 function inst64_nodejs_prepare() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'prepare deployment'
-  bl64_arc_setup
+  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
+    bl64_arc_setup
+  fi
 }
 
 #######################################
@@ -171,11 +228,9 @@ function inst64_nodejs_prepare() {
 function inst64_nodejs_verify() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'verify deployment'
-  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
-    "${INST64_LOCAL_BIN}/${INST64_NODEJS_CLI_NAME_NODE}" --version &&
-      "${INST64_LOCAL_BIN}/${INST64_NODEJS_CLI_NAME_NPM}" --version &&
-      "${INST64_LOCAL_BIN}/${INST64_NODEJS_CLI_NAME_NPX}" --version
-  fi
+  "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NODE}" --version &&
+    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPM}" --version &&
+    "${INST64_NODEJS_CLI_PATH}/${INST64_NODEJS_CLI_NAME_NPX}" --version
 }
 
 #######################################
@@ -191,12 +246,21 @@ function inst64_nodejs_verify() {
 #######################################
 function inst64_nodejs_initialize() {
   bl64_dbg_app_show_function
-  bl64_os_check_compatibility \
-    "${BL64_OS_UB}-22" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_NODEJS_METHOD' \
-      "$INST64_NODEJS_METHOD" \
-      'CUSTOM' &&
-    bl64_check_privilege_root
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_NODEJS_METHOD' \
+    "$INST64_NODEJS_METHOD" \
+    'CUSTOM' ||
+    return $?
+
+  if [[ "$INST64_NODEJS_METHOD" == 'CUSTOM' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_NODEJS_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_UB}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_FD}"
+  fi
 }
 
 #
diff --git a/src/install-trivy b/src/install-trivy
--- a/src/install-trivy
+++ b/src/install-trivy
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
-# Template: 1.1.0
+# Template: 2.3.0
+# Snippet: install-github-release-3.2.1
+# Snippet: install-external-package-3.3.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.0.0
+# Version: 1.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,10 +31,25 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-export INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
 # Base path for local applications
 export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 # Local applications binaries location
@@ -42,17 +59,118 @@ export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
 # Location for temporary files
 export INST64_TMP="${INST64_TMP:-/tmp}"
 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+export INST64_TRIVY_PLATFORM="${INST64_TRIVY_PLATFORM:-}"
+export INST64_TRIVY_TARGET="${INST64_TRIVY_TARGET:-${INST64_OPT_ROOT}/trivy}"
+export INST64_TRIVY_VERSION="${INST64_TRIVY_VERSION:-latest}"
+# Install system wide? Requires root privilege
+export INST64_TRIVY_SYSTEM_WIDE="${INST64_TRIVY_SYSTEM_WIDE:-YES}"
+# Installation method
+export INST64_TRIVY_METHOD="${INST64_TRIVY_METHOD:-BINARY}"
+# Enable development packages?
+export INST64_TRIVY_DEVELOPMENT="${INST64_TRIVY_DEVELOPMENT:-$BL64_VAR_OFF}"
 
-#
-# Globals
-#
+export INST64_TRIVY_REPOSITORY_NAME='trivy'
+export INST64_TRIVY_SOURCE_YUM='https://aquasecurity.github.io/trivy-repo/rpm/releases/9'
+export INST64_TRIVY_REPOSITORY_KEY_YUM='https://aquasecurity.github.io/trivy-repo/rpm/public.key'
+
+export INST64_TRIVY_REPO_NAME='trivy'
+export INST64_TRIVY_REPO_OWNER='aquasecurity'
+export INST64_TRIVY_PACKAGES=''
+export INST64_TRIVY_CLI_NAME='trivy'
+export INST64_TRIVY_CLI_PATH=''
 
 #
 # Functions
 #
+
+function inst64_trivy_add_repository() {
+  bl64_dbg_app_show_function
+  local repository_url=''
+  local repository_key=''
+  local repository_extra_1=''
+  local repository_extra_2=''
+
+  if bl64_os_match "${BL64_OS_OL}"; then
+    repository_url="${INST64_TRIVY_SOURCE_YUM}/${INST64_TRIVY_PLATFORM}"
+    repository_key="$INST64_TRIVY_REPOSITORY_KEY_YUM"
+  fi
+
+  bl64_msg_show_task 'Add external package repository'
+  bl64_pkg_repository_add "$INST64_TRIVY_REPOSITORY_NAME" \
+    "$repository_url" "$repository_key" \
+    "$repository_extra_1" "$repository_extra_2"
+}
+
+function inst64_trivy_install_external_packages() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'deploy packages'
+  INST64_TRIVY_CLI_PATH="/usr/bin/${INST64_TRIVY_CLI_NAME}"
+  # shellcheck disable=SC2086
+  bl64_pkg_deploy $INST64_TRIVY_PACKAGES
+}
+
+function inst64_trivy_install_binary_release() {
+  bl64_dbg_app_show_function
+  local work_path=''
+  local app_target_mode='0755'
+  local app_target_owner='root'
+  local app_cli_mode='0755'
+  local app_cli_source="${INST64_TRIVY_CLI_NAME}"
+
+  if bl64_lib_flag_is_enabled "$INST64_TRIVY_SYSTEM_WIDE"; then
+    INST64_TRIVY_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_TRIVY_CLI_NAME}"
+  else
+    INST64_TRIVY_CLI_PATH="${INST64_TRIVY_TARGET}/${INST64_TRIVY_CLI_NAME}"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
+
+  bl64_msg_show_task 'download application'
+  work_path="$(bl64_fs_create_tmpdir)" || return $?
+  bl64_rxtx_github_get_asset \
+    "$INST64_TRIVY_REPO_OWNER" "$INST64_TRIVY_REPO_NAME" "$INST64_TRIVY_VERSION" "$INST64_TRIVY_PACKAGES" "${work_path}/${INST64_TRIVY_PACKAGES}" &&
+    bl64_arc_open_tar "${work_path}/${INST64_TRIVY_PACKAGES}" "${work_path}" ||
+    return $?
+
+  bl64_msg_show_task 'deploy application'
+  bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_TRIVY_TARGET" &&
+    bl64_fs_copy_files "$app_cli_mode" "$app_target_owner" "$app_target_owner" "$INST64_TRIVY_TARGET" "${work_path}/${app_cli_source}" ||
+    return $?
+
+  if bl64_lib_flag_is_enabled "$INST64_TRIVY_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_TRIVY_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_TRIVY_TARGET}/${INST64_TRIVY_CLI_NAME}" "$INST64_TRIVY_CLI_PATH" "$BL64_VAR_ON" ||
+      return $?
+  fi
+
+  bl64_msg_show_task 'cleanup temporary files'
+  bl64_fs_rm_tmpdir "$work_path"
+  return 0
+}
+
+#######################################
+# Selects platform ID
+#
+# * Platform ID format is defined by the package provider
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Platform ID
+# Returns:
+#   0: selection completed ok
+#   >0: unable to selection
+#######################################
+function inst64_trivy_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_TRIVY_METHOD" == 'BINARY' ]]; then
+    [[ -z "$INST64_TRIVY_PLATFORM" ]] && INST64_TRIVY_PLATFORM='Linux-64bit'
+  elif [[ "$INST64_TRIVY_METHOD" == 'EXTERNAL' ]]; then
+    [[ -z "$INST64_TRIVY_PLATFORM" ]] && INST64_TRIVY_PLATFORM='x86_64'
+  fi
+  [[ -z "$INST64_TRIVY_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
+  return 0
+}
 
 #######################################
 # Install application packages
@@ -67,16 +185,85 @@ source "${INST64_BASHLIB64}/bashlib64.bash" ||
 #######################################
 function inst64_trivy_install() {
   bl64_dbg_app_show_function
-  if bl64_os_match "${BL64_OS_OL}-9"; then
-    inst64_trivy_install_rhel9
+  if [[ "$INST64_TRIVY_METHOD" == 'BINARY' ]]; then
+    inst64_trivy_install_binary_release
+  elif [[ "$INST64_TRIVY_METHOD" == 'EXTERNAL' ]]; then
+    inst64_trivy_install_external_packages
   fi
-  # shellcheck disable=SC2181
-  (($? != 0)) && return 1
+}
 
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_cleanup_full
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_trivy_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_TRIVY_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_TRIVY_VERSION" == 'latest' ]]; then
+      INST64_TRIVY_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_TRIVY_REPO_OWNER" "$INST64_TRIVY_REPO_NAME")" ||
+        return $?
+    fi
+    package_prefix='trivy_'
+    package_sufix='.tar.gz'
+    INST64_TRIVY_PACKAGES="${package_prefix}${INST64_TRIVY_VERSION#v}_${INST64_TRIVY_PLATFORM}${package_sufix}"
+  elif [[ "$INST64_TRIVY_METHOD" == 'EXTERNAL' ]]; then
+    if bl64_os_match "${BL64_OS_OL}"; then
+      INST64_TRIVY_PACKAGES='trivy'
+    fi
+  fi
+  [[ -z "$INST64_TRIVY_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
   return 0
+}
 
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_trivy_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  inst64_trivy_select_platform &&
+    inst64_trivy_select_packages ||
+    return $?
+  if [[ "$INST64_TRIVY_METHOD" == 'BINARY' ]]; then
+    bl64_arc_setup
+  elif [[ "$INST64_TRIVY_METHOD" == 'EXTERNAL' ]]; then
+    bl64_pkg_setup &&
+      inst64_trivy_add_repository
+  fi
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_trivy_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "$INST64_TRIVY_CLI_PATH" --version
 }
 
 #######################################
@@ -88,29 +275,31 @@ function inst64_trivy_install() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_trivy_initialize() {
   bl64_dbg_app_show_function
-  bl64_os_check_version "${BL64_OS_OL}-9" &&
-    bl64_check_privilege_root &&
-    bl64_pkg_setup
-}
-
-function inst64_trivy_install_rhel9() {
-  local repository_name='trivy'
-  local repository_platform='x86_64'
-  local repository_url="https://aquasecurity.github.io/trivy-repo/rpm/releases/9/${repository_platform}"
-  local repository_key='https://aquasecurity.github.io/trivy-repo/rpm/public.key'
-  local packages='trivy'
-
-  bl64_msg_show_task 'Add YUM package repository'
-  bl64_pkg_repository_add "$repository_name" "$repository_url" "$repository_key" ||
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_TRIVY_METHOD' \
+    "$INST64_TRIVY_METHOD" \
+    'BINARY' \
+    'EXTERNAL' ||
     return $?
 
-  bl64_msg_show_task 'deploy packages'
-  # shellcheck disable=SC2086
-  bl64_pkg_deploy $packages
+  if [[ "$INST64_TRIVY_METHOD" == 'BINARY' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_TRIVY_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
+    bl64_os_check_compatibility \
+      "${BL64_OS_UB}" \
+      "${BL64_OS_OL}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_ALP}"
+  elif [[ "$INST64_TRIVY_METHOD" == 'EXTERNAL' ]]; then
+    bl64_check_privilege_root &&
+      bl64_os_check_compatibility \
+        "${BL64_OS_OL}-9"
+  fi
 }
 
 #
@@ -118,15 +307,13 @@ function inst64_trivy_install_rhel9() {
 #
 
 declare inst64_trivy_installer_description='Install application: Trivy'
-declare -i inst64_trivy_status=0
 
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$inst64_trivy_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_trivy_initialize &&
-  inst64_trivy_install
-inst64_trivy_status=$?
-
-bl64_msg_show_batch_finish "$inst64_trivy_status" "$inst64_trivy_installer_description"
-exit $inst64_trivy_status
+  inst64_trivy_prepare &&
+  inst64_trivy_install &&
+  inst64_trivy_verify
+bl64_msg_show_batch_finish $? "$inst64_trivy_installer_description"
