real: promote 6.8.0 (#148)

diff --git a/src/install-auth0cli b/src/install-auth0cli
--- a/src/install-auth0cli
+++ b/src/install-auth0cli
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-bl64-native-1.0.0
-#   Skeleton: install-bl64-custom-1.1.0
+# Template: install-bl64-binary-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -22,103 +21,136 @@
 declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 [[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
   { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
 source "${BL64_SCRIPT_PATH}/lib-bl64" ||
-  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
+  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
 
 #
 # Globals
 #
 
 # Installation method
-declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-NATIVE}"
+declare INST64_AUTH0CLI_METHOD="${INST64_AUTH0CLI_METHOD:-BINARY}"
+# Installation destination
+declare INST64_AUTH0CLI_TARGET="${INST64_AUTH0CLI_TARGET:-}"
+# Hardware architecture
+declare INST64_AUTH0CLI_PLATFORM="${INST64_AUTH0CLI_PLATFORM:-}"
 # Application version
-declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
-# Enable development packages?
-declare INST64_X_APP_NAME_CAPS_X_DEVELOPMENT="${INST64_X_APP_NAME_CAPS_X_DEVELOPMENT:-NO}"
+declare INST64_AUTH0CLI_VERSION="${INST64_AUTH0CLI_VERSION:-latest}"
 
-# App information
-INST64_APP_NAME='X_APP_NAME_X'
-INST64_APP_ID='X_APP_NAME_CAPS_X'
-INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
-INST64_CLI_NAME='X_CLI_NAME_X'
+INST64_APP_NAME='auth0cli'
+INST64_APP_ID='AUTH0CLI'
+INST64_APP_FULL_NAME='Auth0 CLI - Auth0 Command Line Interface'
+INST64_CLI_NAME='auth0'
+
+INST64_GH_REPO_NAME='auth0-cli'
+INST64_GH_REPO_OWNER='auth0'
+INST64_PKG_MAIN_PREFIX='auth0-cli_'
+INST64_PKG_MAIN_SUFFIX='.tar.gz'
+INST64_CPU_DARWIN_ARM64='Darwin_arm64'
+INST64_CPU_LINUX_AMD64='Linux_x86_64'
 
 #
 # Functions
 #
 
-function inst64_install_native() {
+function inst64_install_binary() {
   bl64_dbg_app_show_function
-  inst64_lib_pkg_install
+
+  inst64_lib_task_download
+  inst64_lib_staging_create &&
+    inst64_lib_gh_get_asset &&
+    inst64_lib_staging_open_tar ||
+    return $?
+
+  inst64_lib_task_deploy
+  inst64_lib_target_create &&
+    inst64_lib_target_populate ||
+    return $?
+
+  inst64_lib_task_cleanup
+  inst64_lib_staging_remove
 }
 
 function inst64_prepare() {
   bl64_dbg_app_show_function
   inst64_lib_step_prepare || return 0
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'BINARY' ]]; then
+    inst64_lib_base_create_path
+  fi
 }
 
 function inst64_install() {
   bl64_dbg_app_show_function
   inst64_lib_step_install || return 0
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NATIVE' ]]; then
-    inst64_install_native
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'BINARY' ]]; then
+    inst64_install_binary
   fi
 }
 
 function inst64_setup() {
   bl64_dbg_app_show_function
   inst64_lib_step_setup || return 0
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'BINARY' ]]; then
+    inst64_lib_task_publish
+    inst64_lib_cli_promote
+  fi
 }
 
 function inst64_verify() {
   bl64_dbg_app_show_function
   inst64_lib_step_verify || return 0
-  # X_VERIFY_PLACEHOLDER_X
-  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version || return $?
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'BINARY' ]]; then
+    inst64_lib_app_register_version
+  fi
 }
 
 function inst64_select_method() {
   bl64_dbg_app_show_function
   inst64_lib_app_check_method \
     'AUTO' \
-    'NATIVE' ||
+    'BINARY' ||
     return $?
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'AUTO' ]]; then
-    # X_METHOD_AUTO_PLACEHOLDER_X
-    INST64_X_APP_NAME_CAPS_X_METHOD='NATIVE'
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'AUTO' ]]; then
+    INST64_AUTH0CLI_METHOD='BINARY'
   fi
 }
 
 function inst64_select_platform() {
   bl64_dbg_app_show_function
-  return 0
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'BINARY' ]]; then
+    if [[ -z "$INST64_AUTH0CLI_PLATFORM" ]]; then
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_AUTH0CLI_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_AUTH0CLI_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      fi
+    fi
+    inst64_lib_platform_check_cpu
+  fi
 }
 
 function inst64_select_packages() {
   bl64_dbg_app_show_function
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NATIVE' ]]; then
-    # shellcheck disable=SC2249
-    case "$BL64_OS_FLAVOR" in
-    "$BL64_OS_FLAVOR_X_FLAVOR_X")
-      bl64_lib_flag_is_enabled "$INST64_X_APP_NAME_CAPS_X_DEVELOPMENT" &&
-        INST64_PKG_DEV='X_OS_DEV_PACKAGE_LIST_X'
-      INST64_PKG_MAIN='X_OS_PACKAGE_LIST_X'
-      ;;
-    esac
-    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
+  if [[ "$INST64_AUTH0CLI_METHOD" == 'BINARY' ]]; then
+    if [[ "$INST64_AUTH0CLI_VERSION" == 'latest' ]]; then
+      INST64_AUTH0CLI_VERSION="$(bl64_vcs_github_release_get_latest "$INST64_GH_REPO_OWNER" "$INST64_GH_REPO_NAME")" ||
+        return $?
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_AUTH0CLI_VERSION#v}_${INST64_AUTH0CLI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
   fi
   inst64_lib_package_check_definition
 }
@@ -128,12 +160,6 @@ function inst64_initialize() {
   inst64_select_method &&
     inst64_lib_base_initialize ||
     return $?
-
-  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'NATIVE' ]]; then
-    bl64_os_check_flavor \
-        "$BL64_OS_FLAVOR_ALPINE" ||
-      return $?
-  fi
 
   inst64_select_platform &&
     inst64_select_packages &&
