real: promote 6.0.9 (#131)

diff --git a/src/install-awscli b/src/install-awscli
--- a/src/install-awscli
+++ b/src/install-awscli
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: install-custom-2.4.0
+# Template: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,300 +17,194 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck source-path=lib/bl64 disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
-declare INST64_AWSCLI_PLATFORM="${INST64_AWSCLI_PLATFORM:-}"
-declare INST64_AWSCLI_SOURCE="${INST64_AWSCLI_SOURCE:-https://awscli.amazonaws.com}"
-declare INST64_AWSCLI_TARGET="${INST64_AWSCLI_TARGET:-}"
-declare INST64_AWSCLI_VERSION="${INST64_AWSCLI_VERSION:-}"
 # Installation method
 declare INST64_AWSCLI_METHOD="${INST64_AWSCLI_METHOD:-CUSTOM}"
+# Installation destination
+declare INST64_AWSCLI_TARGET="${INST64_AWSCLI_TARGET:-}"
+# Hardware architecture
+declare INST64_AWSCLI_PLATFORM="${INST64_AWSCLI_PLATFORM:-}"
+# Application version
+declare INST64_AWSCLI_VERSION="${INST64_AWSCLI_VERSION:-latest}"
 
-declare INST64_WEB_REPO_URL=''
-declare INST64_APP_INSTALLER='aws/install'
-declare INST64_PKG_MAIN=''
-declare INST64_CLI_NAME='aws'
-declare INST64_CLI_PATH=''
+# App information
+INST64_APP_NAME='awscli'
+INST64_APP_ID='AWSCLI'
+INST64_APP_FULL_NAME='AWS CLI'
+# CLI information
+INST64_CLI_NAME='aws'
+INST64_CPU_LINUX_AMD64='linux-x86_64'
+INST64_WEB_REPO_URL='https://awscli.amazonaws.com'
+INST64_APP_INSTALLER='aws/install'
 
 #
 # Functions
 #
 
-function inst64_install_custom_package_linux() {
-  bl64_dbg_app_show_function "$@"
-  local work_path="$1"
-  local app_target_mode='0755'
-  local app_target_owner="$BL64_IAM_SYSTEM_USER"
-  local app_target_group="$BL64_IAM_SYSTEM_GROUP"
-  local app_cli_source="bin/${INST64_CLI_NAME}"
-  local app_cli_source2="bin/aws_completer"
-
-  if ! bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    app_target_owner="$BL64_VAR_DEFAULT"
-    app_target_group="$BL64_VAR_DEFAULT"
-  fi
-
-  bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" &&
-    bl64_rxtx_web_get_file \
-      "${INST64_WEB_REPO_URL}" "${work_path}/${INST64_PKG_MAIN}" &&
-    bl64_arc_open_zip "${work_path}/${INST64_PKG_MAIN}" "${work_path}" ||
+function inst64_install_custom_linux() {
+  bl64_dbg_app_show_function
+  bl64_arc_open_zip "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" "${INST64_WORK_PATH_STAGING}" ||
     return $?
 
-  bl64_msg_show_task 'deploy application'
-  bl64_fs_dir_create "$app_target_mode" "$app_target_owner" "$app_target_group" "$INST64_AWSCLI_TARGET" &&
-    bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
-    "${work_path}/$INST64_APP_INSTALLER" \
+  inst64_lib_task_deploy
+  bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
+    "${INST64_WORK_PATH_STAGING}/$INST64_APP_INSTALLER" \
       --bin-dir "${INST64_AWSCLI_TARGET}/bin" \
       --install-dir "${INST64_AWSCLI_TARGET}/versions" \
-      --update ||
-    return $?
-  if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-    bl64_msg_show_task "publish application to searchable path (${INST64_CLI_PATH})"
-    # shellcheck disable=SC2086
-    bl64_fs_symlink_create "${INST64_AWSCLI_TARGET}/${app_cli_source}" "$INST64_CLI_PATH" "$BL64_VAR_ON" &&
-      bl64_fs_symlink_create "${INST64_AWSCLI_TARGET}/${app_cli_source2}" "${INST64_LOCAL_BIN}/aws_completer" "$BL64_VAR_ON" ||
-      return $?
-  fi
+      --update
 }
 
-function inst64_install_custom_package_macos() {
-  bl64_dbg_app_show_function "$@"
-  local work_path="$1"
-
-  bl64_msg_show_task 'download application'
-  bl64_rxtx_web_get_file \
-    "${INST64_WEB_REPO_URL}" "${work_path}/${INST64_PKG_MAIN}" ||
-    return $?
-
-  bl64_msg_show_task 'deploy application'
-  installer -pkg "${work_path}/${INST64_PKG_MAIN}" -target /
-}
-
-function inst64_install_custom_package() {
+function inst64_install_custom_macos() {
   bl64_dbg_app_show_function
-  local work_path=''
-  work_path="$(bl64_fs_create_tmpdir)" ||
+  inst64_lib_task_deploy
+  installer \
+    -pkg "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" \
+    -target /
+}
+
+function inst64_install_custom() {
+  bl64_dbg_app_show_function
+  inst64_lib_task_binary_download &&
+    bl64_rxtx_web_get_file \
+      "${INST64_WEB_REPO_URL}" \
+      "${INST64_WORK_PATH_STAGING}/${INST64_PKG_MAIN}" ||
     return $?
   if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
-    inst64_install_custom_package_linux "$work_path"
+    inst64_install_custom_linux
   elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
-    inst64_install_custom_package_macos "$work_path"
+    inst64_install_custom_macos
   fi
-  bl64_msg_show_task 'cleanup temporary files'
-  bl64_fs_rm_tmpdir "$work_path"
-  return 0
+  inst64_lib_task_binary_cleanup
 }
 
-#######################################
-# Selects platform ID
-#
-# * Platform ID format is defined by the package provider
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Platform ID
-# Returns:
-#   0: selection completed ok
-#   >0: unable to selection
-#######################################
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+}
+
+function inst64_install() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
+    inst64_install_custom
+  fi
+}
+
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
+    INST64_WORK_PATH_CLI="${INST64_AWSCLI_TARGET}/bin/${INST64_CLI_NAME}"
+    inst64_lib_task_publish
+    # shellcheck disable=SC2086
+    bl64_fs_symlink_create "${INST64_WORK_PATH_CLI}" "${INST64_CLI_PATH}/${INST64_CLI_NAME}" "$BL64_VAR_ON"
+  fi
+}
+
+function inst64_verify() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
+}
+
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'CUSTOM' ||
+    return $?
+  if [[ "$INST64_AWSCLI_METHOD" == 'AUTO' ]]; then
+    INST64_AWSCLI_METHOD='CUSTOM'
+  fi
+}
+
 function inst64_select_platform() {
   bl64_dbg_app_show_function
   if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
     if [[ -z "$INST64_AWSCLI_PLATFORM" ]]; then
-      # shellcheck disable=SC2249
-      case "$BL64_OS_MACHINE" in
-      "$BL64_OS_MACHINE_ARM64") INST64_AWSCLI_PLATFORM='not-used' ;;
-      "$BL64_OS_MACHINE_AMD64") INST64_AWSCLI_PLATFORM='linux-x86_64' ;;
-      esac
+      if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_ARM64" ]]; then
+        INST64_AWSCLI_PLATFORM="$INST64_CPU_DARWIN_ARM64"
+      elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+        INST64_AWSCLI_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      fi
+      INST64_CLI_PATH='/usr/local/bin'
     fi
-  fi
-  [[ -z "$INST64_AWSCLI_PLATFORM" ]] && bl64_msg_show_error 'unable to determine platform id' && return 1
-  return 0
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
-function inst64_install() {
-  bl64_dbg_app_show_function
-  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
-    inst64_install_custom_package
+    inst64_lib_platform_check_cpu
   fi
 }
 
-#######################################
-# Select installation packages and related information
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package name list
-# Returns:
-#   0: selection ok
-#   >0: selection failed
-#######################################
 function inst64_select_packages() {
   bl64_dbg_app_show_function
-  local package_prefix=''
-  local package_suffix=''
   if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
     if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" ]]; then
-      package_prefix='awscli-exe-'
-      package_suffix='.zip'
-      INST64_PKG_MAIN="${package_prefix}${INST64_AWSCLI_PLATFORM}${package_suffix}"
-      INST64_WEB_REPO_URL="${INST64_AWSCLI_SOURCE}/${INST64_PKG_MAIN}"
+      INST64_PKG_MAIN_PREFIX='awscli-exe-'
+      INST64_PKG_MAIN_SUFFIX='.zip'
+      INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_AWSCLI_PLATFORM}${INST64_PKG_MAIN_SUFFIX}"
     elif [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_MACOS" ]]; then
-      package_prefix='AWSCLIV2'
-      package_suffix='.pkg'
-      INST64_PKG_MAIN="${package_prefix}${package_suffix}"
+      INST64_PKG_MAIN_PREFIX='AWSCLIV2'
+      INST64_PKG_MAIN_SUFFIX='.pkg'
+      INST64_PKG_MAIN="${INST64_PKG_MAIN_PREFIX}${INST64_PKG_MAIN_SUFFIX}"
     fi
-    INST64_WEB_REPO_URL="${INST64_AWSCLI_SOURCE}/${INST64_PKG_MAIN}"
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      INST64_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_CLI_NAME}"
-    fi
+    INST64_WEB_REPO_URL+="/${INST64_PKG_MAIN}"
   fi
-  [[ -z "$INST64_WEB_REPO_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
-  [[ -z "$INST64_PKG_MAIN" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
-  return 0
+  inst64_lib_package_check_definition
 }
 
-#######################################
-# Prepare installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Preparation progress and errors
-# Returns:
-#   0: preparation ok
-#   >0: preparation failed
-#######################################
-function inst64_prepare() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'prepare deployment'
-  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
-    bl64_arc_setup
-  fi
-}
-
-#######################################
-# Verify installation
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Verification progress and errors
-# Returns:
-#   0: verification ok
-#   >0: verification failed
-#######################################
-function inst64_verify() {
-  bl64_dbg_app_show_function
-  bl64_msg_show_task 'verify deployment'
-  "$INST64_CLI_PATH" --version
-}
-
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: initialization failed
-#######################################
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  INST64_AWSCLI_TARGET="${INST64_AWSCLI_TARGET:-${INST64_OPT_ROOT}/awscli}"
-  bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_AWSCLI_METHOD' \
-    "$INST64_AWSCLI_METHOD" \
-    'CUSTOM' ||
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
     return $?
 
   if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      bl64_check_privilege_root ||
-        return $?
-    fi
-    bl64_os_check_compatibility \
-      "${BL64_OS_MCOS}" \
-      "${BL64_OS_UB}" \
-      "${BL64_OS_FD}" \
-      "${BL64_OS_OL}" ||
+    bl64_check_privilege_root &&
+      bl64_os_check_flavor \
+        "$BL64_OS_FLAVOR_DEBIAN" \
+        "$BL64_OS_FLAVOR_FEDORA" \
+        "$BL64_OS_FLAVOR_REDHAT" \
+        "$BL64_OS_FLAVOR_MACOS" &&
+      bl64_arc_setup ||
       return $?
   fi
+
   inst64_select_platform &&
-    inst64_select_packages ||
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
     return $?
-  bl64_msg_show_setup 'Install application: AWS CLI' \
-    'INST64_AWSCLI_METHOD' 'INST64_SYSTEM_WIDE' \
-    'INST64_AWSCLI_PLATFORM' \
-    'INST64_AWSCLI_SOURCE' \
-    'INST64_AWSCLI_TARGET' \
-    'INST64_AWSCLI_VERSION' \
-    'INST64_CLI_PATH'
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.6.3'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
@@ -318,5 +212,6 @@ bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 inst64_initialize &&
   inst64_prepare &&
   inst64_install &&
+  inst64_setup &&
   inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
