feat: add aws_complete

diff --git a/src/install-awscli b/src/install-awscli
--- a/src/install-awscli
+++ b/src/install-awscli
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Template: 1.2.0
+# Template: 2.2.0
 #######################################
 # Installer64 / Package installer
 #
 # Author: SerDigital64 (https://github.com/serdigital64)
 # Repository: https://github.com/automation64/installer64
-# Version: 1.3.0
+# Version: 1.4.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -29,6 +29,21 @@
 
 # BashLib64 location
 export INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+
+#
+# Globals
+#
+
 # Enable debugging? Set to YES to enable
 export INST64_DEBUG="${INST64_DEBUG:-}"
 # Base path for local applications
@@ -37,20 +52,23 @@ export INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
 export INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
 # Base path for 3rd party applications
 export INST64_OPT_ROOT="${INST64_OPT_ROOT:-/opt}"
-
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
-
-#
-# Globals
-#
+# Location for temporary files
+export INST64_TMP="${INST64_TMP:-/tmp}"
 
 export INST64_AWSCLI_PLATFORM="${INST64_AWSCLI_PLATFORM:-linux-x86_64}"
 export INST64_AWSCLI_SOURCE="${INST64_AWSCLI_SOURCE:-https://awscli.amazonaws.com}"
 export INST64_AWSCLI_TARGET="${INST64_AWSCLI_TARGET:-${INST64_OPT_ROOT}/awscli}"
+export INST64_AWSCLI_VERSION="${INST64_AWSCLI_VERSION:-}"
+# Install system wide? Requires root privilege
+export INST64_AWSCLI_SYSTEM_WIDE="${INST64_AWSCLI_SYSTEM_WIDE:-YES}"
 # Installation method
 export INST64_AWSCLI_METHOD="${INST64_AWSCLI_METHOD:-CUSTOM}"
+
+export INST64_AWSCLI_PACKAGE_URL=''
+export INST64_AWSCLI_INSTALLER='aws/install'
+export INST64_AWSCLI_PACKAGES=''
+export INST64_AWSCLI_CLI_NAME='aws'
+export INST64_AWSCLI_CLI_PATH=''
 
 #
 # Functions
@@ -58,37 +76,40 @@ export INST64_AWSCLI_METHOD="${INST64_AWSCLI_METHOD:-CUSTOM}"
 
 function inst64_awscli_install_custom_package() {
   bl64_dbg_app_show_function
-  local package_prefix='awscli-exe-'
-  local package_sufix='.zip'
-  local package_name="${package_prefix}${INST64_AWSCLI_PLATFORM}${package_sufix}"
-  local package_url="$INST64_AWSCLI_SOURCE"
   local work_path=''
   local app_target_mode='0755'
   local app_target_owner='root'
-  local app_cli='aws'
-  local app_installer='aws/install'
-  local app_bin="${INST64_AWSCLI_TARGET}/bin"
-  local app_versions="${INST64_AWSCLI_TARGET}/versions"
+
+  if bl64_lib_flag_is_enabled "$INST64_AWSCLI_SYSTEM_WIDE"; then
+    INST64_AWSCLI_CLI_PATH="${INST64_LOCAL_BIN}/${INST64_AWSCLI_CLI_NAME}"
+  else
+    INST64_AWSCLI_CLI_PATH="${INST64_AWSCLI_TARGET}/${INST64_AWSCLI_CLI_NAME}"
+    app_target_owner="$BL64_VAR_DEFAULT"
+  fi
 
   bl64_msg_show_task 'download application'
-  work_path="$(bl64_fs_create_tmpdir)" || return $?
-  bl64_rxtx_web_get_file "${package_url}/${package_name}" "${work_path}/${package_name}" &&
-    bl64_arc_open_zip "${work_path}/${package_name}" "${work_path}" ||
+  work_path="$(bl64_fs_create_tmpdir)" &&
+    bl64_rxtx_web_get_file \
+      "${INST64_AWSCLI_PACKAGE_URL}" "${work_path}/${INST64_AWSCLI_PACKAGES}" &&
+    bl64_arc_open_zip "${work_path}/${INST64_AWSCLI_PACKAGES}" "${work_path}" ||
     return $?
 
   bl64_msg_show_task 'deploy application'
   bl64_fs_create_dir "$app_target_mode" "$app_target_owner" "$app_target_owner" "$INST64_AWSCLI_TARGET" &&
     bl64_fs_set_umask "$BL64_FS_UMASK_RW_USER_RO_ALL" &&
-    "${work_path}/$app_installer" \
-      --bin-dir "$app_bin" \
-      --install-dir "$app_versions" \
+    "${work_path}/$INST64_AWSCLI_INSTALLER" \
+      --bin-dir "${INST64_AWSCLI_TARGET}/bin" \
+      --install-dir "${INST64_AWSCLI_TARGET}/versions" \
       --update ||
     return $?
 
-  bl64_msg_show_task "publish application to searchable path (${INST64_LOCAL_BIN})"
-  # shellcheck disable=SC2086
-  bl64_fs_create_symlink "${app_bin}/${app_cli}" "${INST64_LOCAL_BIN}/${app_cli}" "$BL64_VAR_ON" ||
-    return $?
+  if bl64_lib_flag_is_enabled "$INST64_AWSCLI_SYSTEM_WIDE"; then
+    bl64_msg_show_task "publish application to searchable path (${INST64_AWSCLI_CLI_PATH})"
+    # shellcheck disable=SC2086
+    bl64_fs_create_symlink "${INST64_AWSCLI_TARGET}/bin/${INST64_AWSCLI_CLI_NAME}" "$INST64_AWSCLI_CLI_PATH" "$BL64_VAR_ON" &&
+      bl64_fs_create_symlink "${INST64_AWSCLI_TARGET}/bin/aws_completer" "${INST64_LOCAL_BIN}/aws_completer" "$BL64_VAR_ON" ||
+      return $?
+  fi
 
   bl64_msg_show_task 'cleanup temporary files'
   bl64_fs_rm_tmpdir "$work_path"
@@ -108,9 +129,72 @@ function inst64_awscli_install_custom_package() {
 #######################################
 function inst64_awscli_install() {
   bl64_dbg_app_show_function
+  inst64_awscli_select_packages || return $?
   if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
     inst64_awscli_install_custom_package
   fi
+}
+
+#######################################
+# Select installation packages and related information
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Package name list
+# Returns:
+#   0: selection ok
+#   >0: selection failed
+#######################################
+function inst64_awscli_select_packages() {
+  bl64_dbg_app_show_function
+  local package_prefix=''
+  local package_sufix=''
+  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
+    package_prefix='awscli-exe-'
+    package_sufix='.zip'
+    INST64_AWSCLI_PACKAGES="${package_prefix}${INST64_AWSCLI_PLATFORM}${package_sufix}"
+    INST64_AWSCLI_PACKAGE_URL="${INST64_AWSCLI_SOURCE}/${INST64_AWSCLI_PACKAGES}"
+  fi
+  [[ -z "$INST64_AWSCLI_PACKAGE_URL" ]] && bl64_msg_show_error 'unable to determine package download URL' && return 1
+  [[ -z "$INST64_AWSCLI_PACKAGES" ]] && bl64_msg_show_error 'unable to determine package name' && return 1
+  return 0
+}
+
+#######################################
+# Prepare installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Preparation progress and errors
+# Returns:
+#   0: preparation ok
+#   >0: preparation failed
+#######################################
+function inst64_awscli_prepare() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'prepare deployment'
+  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
+    bl64_arc_setup
+  fi
+}
+
+#######################################
+# Verify installation
+#
+# Arguments:
+#   None. Parameters are imported from Globals
+# Outputs:
+#   Verification progress and errors
+# Returns:
+#   0: verification ok
+#   >0: verification failed
+#######################################
+function inst64_awscli_verify() {
+  bl64_dbg_app_show_function
+  bl64_msg_show_task 'verify deployment'
+  "$INST64_AWSCLI_CLI_PATH" --version
 }
 
 #######################################
@@ -122,19 +206,25 @@ function inst64_awscli_install() {
 #   Initializacion progress messages
 # Returns:
 #   0: initialization ok
-#   >: failed to initialize
+#   >: initialization failed
 #######################################
 function inst64_awscli_initialize() {
   bl64_dbg_app_show_function
+  bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_AWSCLI_METHOD' \
+    "$INST64_AWSCLI_METHOD" \
+    'CUSTOM' ||
+    return $?
 
-  bl64_arc_setup &&
+  if [[ "$INST64_AWSCLI_METHOD" == 'CUSTOM' ]]; then
+    if bl64_lib_flag_is_enabled "$INST64_AWSCLI_SYSTEM_WIDE"; then
+      bl64_check_privilege_root ||
+        return $?
+    fi
     bl64_os_check_compatibility \
-      "${BL64_OS_UB}-22" \
-      "${BL64_OS_OL}-9" &&
-    bl64_fmt_check_value_in_list 'invalid installation method for the parameter INST64_AWSCLI_METHOD' \
-      "$INST64_AWSCLI_METHOD" \
-      'CUSTOM' &&
-    bl64_check_privilege_root
+      "${BL64_OS_UB}" \
+      "${BL64_OS_FD}" \
+      "${BL64_OS_OL}"
+  fi
 }
 
 #
@@ -148,6 +238,7 @@ bl64_msg_show_batch_start "$inst64_awscli_installer_description"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_awscli_initialize &&
-  inst64_awscli_install
-
+  inst64_awscli_prepare &&
+  inst64_awscli_install &&
+  inst64_awscli_verify
 bl64_msg_show_batch_finish $? "$inst64_awscli_installer_description"
