refact: upgrade to lib-bl64

diff --git a/src/install-azurecli b/src/install-azurecli
--- a/src/install-azurecli
+++ b/src/install-azurecli
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Template: 1.2.0
+# Template: install-bl64-native-1.0.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -17,159 +17,192 @@
 # Imports
 #
 
-# Home root
-declare INST64_HOME="${HOME}/at64"
 # BashLib64 location
-declare INST64_BASHLIB64="${INST64_BASHLIB64:-}"
-[[ -d "$INST64_HOME" ]] && INST64_BASHLIB64="${INST64_BASHLIB64:-${INST64_HOME}/bl64}" || INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}" 
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${INST64_BASHLIB64}/bashlib64.bash" ||
-  { echo 'Error: BashLib64 not found. Please run the install-bashlib64 script and retry.' && exit 1; }
+declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
+[[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
+# shellcheck source-path=lib/bl64 disable=SC2015
+source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-cryp.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-pkg.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
+  { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
+# shellcheck source-path=src disable=SC2015
+source "${BL64_SCRIPT_PATH}/lib-bl64" ||
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
-# Enable debugging? Set to YES to enable
-declare INST64_DEBUG="${INST64_DEBUG:-}"
-# Installer64 location
-declare INST64_INSTALLER_ROOT="${INST64_INSTALLER_ROOT:-/opt/installer64}"
-# Base path for local applications
-declare INST64_LOCAL_ROOT="${INST64_LOCAL_ROOT:-/usr/local}"
-# Local applications binaries location
-declare INST64_LOCAL_BIN="${INST64_LOCAL_BIN:-${INST64_LOCAL_ROOT}/bin}"
-# User applications binaries location
-declare INST64_USER_BIN="${INST64_USER_BIN:-${HOME}/.local/bin}"
-# Location for temporary files
-declare INST64_TMP="${INST64_TMP:-/tmp}"
-# Base path for 3rd party applications
-declare INST64_OPT_ROOT="${INST64_OPT_ROOT:-}"
-# Install system wide? Requires root privilege
-declare INST64_SYSTEM_WIDE="${INST64_SYSTEM_WIDE:-}"
-
 # Installation method
-declare INST64_AZURECLI_METHOD="${INST64_AZURECLI_METHOD:-EXTERNAL}"
+declare INST64_AZURECLI_METHOD="${INST64_AZURECLI_METHOD:-NATIVE}"
+# Installation destination
+declare INST64_AZURECLI_TARGET=''
+# Hardware architecture
+declare INST64_AZURECLI_PLATFORM=''
+# Application version
+declare INST64_AZURECLI_VERSION="${INST64_AZURECLI_VERSION:-latest}"
+# Enable development packages?
+declare INST64_AZURECLI_DEVELOPMENT="${INST64_AZURECLI_DEVELOPMENT:-NO}"
 
-declare INST64_OS_REPO_NAME='azure-cli'
-declare INST64_OS_REPO_SOURCE_RHEL='https://packages.microsoft.com/config/rhel'
-declare INST64_OS_REPO_SOURCE_DEB='https://packages.microsoft.com/repos/azure-cli'
-declare INST64_OS_REPO_KEY_DEB='https://packages.microsoft.com/keys/microsoft.asc'
+# App information
+INST64_APP_NAME='azurecli'
+INST64_APP_ID='AZURECLI'
+INST64_APP_FULL_NAME='Azure CLI'
+INST64_CLI_NAME='az'
+
+INST64_OS_REPO_NAME='microsoft'
+INST64_OS_SOURCE_YUM='https://packages.microsoft.com/yumrepos/azure-cli'
+INST64_OS_SOURCE_APT='https://packages.microsoft.com/repos/azure-cli'
+INST64_OS_REPOSITORY_KEY_YUM='https://packages.microsoft.com/keys/microsoft.asc'
+INST64_OS_REPOSITORY_KEY_APT='https://packages.microsoft.com/keys/microsoft.asc'
+INST64_CPU_LINUX_AMD64='x86_64'
 
 #
 # Functions
 #
 
-function inst64_select_packages() {
-  bl64_dbg_app_show_function
-  local packages=''
-  if bl64_os_is_distro "${BL64_OS_OL}"; then
-    packages='azure-cli'
-  elif bl64_os_is_distro "${BL64_OS_UB}"; then
-    packages='azure-cli'
-  fi
-  [[ -n "$packages" ]] && echo "$packages"
-}
-
-function inst64_add_repository() {
+function inst64_prepare_repository() {
   bl64_dbg_app_show_function
   local repository_url=''
   local repository_key=''
-  local repository_extra_1=''
-  local repository_extra_2=''
-  local repository_key_file='/etc/apt/keyrings/microsoft.gpg'
+  local repository_apt_suite=''
+  local repository_apt_component=''
+
+  if bl64_os_is_flavor "$BL64_OS_FLAVOR_DEBIAN"; then
+    repository_url="${INST64_OS_SOURCE_APT}"
+    repository_key="$INST64_OS_REPOSITORY_KEY_APT"
+    repository_apt_suite="$VERSION_CODENAME"
+    repository_apt_component='main'
+  elif bl64_os_is_flavor "$BL64_OS_FLAVOR_FEDORA" || bl64_os_is_flavor "$BL64_OS_FLAVOR_REDHAT"; then
+    repository_url="${INST64_OS_SOURCE_YUM}"
+    repository_key="$INST64_OS_REPOSITORY_KEY_YUM"
+    bl64_pkg_run_rpm --import "$repository_key"
+  fi
 
   bl64_msg_show_task 'Add external package repository'
-  if bl64_os_is_distro "${BL64_OS_OL}"; then
-    repository_url="${INST64_OS_REPO_SOURCE_RHEL}/9.0/packages-microsoft-prod.rpm"
-    bl64_pkg_deploy "$repository_url"
-  elif bl64_os_is_distro "${BL64_OS_UB}"; then
-    repository_url="$INST64_OS_REPO_SOURCE_DEB"
-    repository_key="$INST64_OS_REPO_KEY_DEB"
-    repository_extra_2='main'
-    bl64_pkg_deploy 'gnupg' 'lsb-release' &&
-      bl64_rxtx_run_curl -sLS "$repository_key" |
-      gpg --dearmor | "$BL64_OS_CMD_TEE" "$repository_key_file" >/dev/null &&
-      bl64_fs_run_chmod go+r "$repository_key_file" &&
-      repository_extra_1="$(lsb_release -cs)" &&
-      echo "deb [signed-by=${repository_key_file}] ${repository_url} ${repository_extra_1} ${repository_extra_2}" |
-      "$BL64_OS_CMD_TEE" "/etc/apt/sources.list.d/${INST64_OS_REPO_NAME}.list" >/dev/null
+  bl64_pkg_repository_add "$INST64_OS_REPO_NAME" \
+    "$repository_url" "$repository_key" \
+    "$repository_apt_suite" "$repository_apt_component"
+}
+
+function inst64_install_native() {
+  bl64_dbg_app_show_function
+  # shellcheck disable=SC2086
+  bl64_pkg_deploy $INST64_PKG_MAIN
+}
+
+function inst64_prepare() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_prepare || return 0
+  if [[ "$INST64_AZURECLI_METHOD" == 'NATIVE' ]]; then
+    inst64_prepare_repository
   fi
 }
 
-function inst64_install_external_packages() {
-  bl64_dbg_app_show_function
-  local packages=''
-
-  inst64_add_repository ||
-    return $?
-
-  bl64_msg_show_task 'deploy packages'
-  packages="$(inst64_select_packages)" ||
-    return $?
-  # shellcheck disable=SC2086
-  bl64_pkg_deploy $packages
-}
-
-#######################################
-# Install application packages
-#
-# Arguments:
-#   None. Parameters are imported from Globals
-# Outputs:
-#   Package installer progress and errors
-# Returns:
-#   0: package installed ok
-#   >0: unable to install package
-#######################################
 function inst64_install() {
   bl64_dbg_app_show_function
-  if [[ "$INST64_AZURECLI_METHOD" == 'EXTERNAL' ]]; then
-    inst64_install_external_packages
+  inst64_lib_step_install || return 0
+  if [[ "$INST64_AZURECLI_METHOD" == 'NATIVE' ]]; then
+    inst64_install_native
   fi
 }
 
-#######################################
-# Initialize environment
-#
-# Arguments:
-#   None
-# Outputs:
-#   Initializacion progress messages
-# Returns:
-#   0: initialization ok
-#   >: failed to initialize
-#######################################
+function inst64_setup() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_setup || return 0
+}
+
+function inst64_verify() {
+  bl64_dbg_app_show_function
+  inst64_lib_step_verify || return 0
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" version
+}
+
+function inst64_select_method() {
+  bl64_dbg_app_show_function
+  inst64_lib_app_check_method \
+    'AUTO' \
+    'NATIVE' ||
+    return $?
+  if [[ "$INST64_AZURECLI_METHOD" == 'AUTO' ]]; then
+    INST64_AZURECLI_METHOD='NATIVE'
+  fi
+}
+
+function inst64_select_platform() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_AZURECLI_METHOD" == 'NATIVE' ]]; then
+    if [[ "$BL64_OS_TYPE" == "$BL64_OS_TYPE_LINUX" && "$BL64_OS_MACHINE" == "$BL64_OS_MACHINE_AMD64" ]]; then
+      if bl64_os_is_distro "${BL64_OS_OL}-9"; then
+        INST64_AZURECLI_PLATFORM="$INST64_CPU_LINUX_AMD64"
+      elif bl64_os_is_flavor "$BL64_OS_FLAVOR_DEBIAN"; then
+        INST64_AZURECLI_PLATFORM="$INST64_CPU_ALL_ALL"
+      fi
+    fi
+    inst64_lib_platform_check_cpu
+  fi
+}
+
+function inst64_select_packages() {
+  bl64_dbg_app_show_function
+  if [[ "$INST64_AZURECLI_METHOD" == 'NATIVE' ]]; then
+    bl64_lib_flag_is_enabled "$INST64_AZURECLI_DEVELOPMENT" &&
+      INST64_PKG_DEV=''
+    INST64_PKG_MAIN='azure-cli'
+    INST64_PKG_MAIN+=" ${INST64_PKG_DEV}"
+  fi
+  inst64_lib_package_check_definition
+}
+
 function inst64_initialize() {
   bl64_dbg_app_show_function
-  if [[ -z "$INST64_SYSTEM_WIDE" ]]; then
-    [[ -d "$INST64_HOME" ]] && INST64_SYSTEM_WIDE='NO' || INST64_SYSTEM_WIDE='YES'
-  fi
-  if [[ -z "$INST64_OPT_ROOT" ]]; then
-    bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE" && INST64_OPT_ROOT='/opt' || INST64_OPT_ROOT="$INST64_HOME"
-  fi
-  bl64_os_check_version \
-    "${BL64_OS_UB}-22" \
-    "${BL64_OS_OL}-9" &&
-    bl64_fmt_list_check_membership 'invalid installation method for the parameter INST64_AZURECLI_METHOD' \
-      "$INST64_AZURECLI_METHOD" \
-      'EXTERNAL' &&
+  inst64_lib_base_initialize &&
+    inst64_select_method ||
+    return $?
+
+  if [[ "$INST64_AZURECLI_METHOD" == 'NATIVE' ]]; then
     bl64_check_privilege_root &&
-    bl64_pkg_setup
-  # shellcheck disable=SC2181
-  (($? != 0)) && return $BL64_LIB_ERROR_TASK_FAILED
-  bl64_msg_show_setup 'Install application: Azure CLI' \
-    'INST64_AZURECLI_METHOD' 'INST64_SYSTEM_WIDE' 
+      bl64_os_check_flavor \
+        "$BL64_OS_FLAVOR_DEBIAN" \
+        "$BL64_OS_FLAVOR_FEDORA" \
+        "$BL64_OS_FLAVOR_REDHAT"
+    bl64_cryp_setup &&
+      bl64_pkg_setup ||
+      return $?
+  fi
+
+  inst64_select_platform &&
+    inst64_select_packages &&
+    inst64_lib_cli_set_path ||
+    return $?
+
+  inst64_lib_app_check_installed && return 0
+  inst64_lib_message_show_parameters
 }
 
 #
 # Main
 #
 
-bl64_lib_script_version_set '1.1.0'
+bl64_lib_script_version_set '2.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
 [[ -n "$INST64_DEBUG" ]] && bl64_dbg_all_enable
 inst64_initialize &&
-  inst64_install
+  inst64_prepare &&
+  inst64_install &&
+  inst64_setup &&
+  inst64_verify
 bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
