real: promote 6.3.0 (#140)

diff --git a/docs/skeletons/installer-bl64-fpak/install-1APP b/docs/skeletons/installer-bl64-fpak/install-1APP
--- a/docs/skeletons/installer-bl64-fpak/install-1APP
+++ b/docs/skeletons/installer-bl64-fpak/install-1APP
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-# Template: install-bl64-custom-1.1.0
+# Template: install-bl64-fpak-1.0.0
+#   Skeleton: install-bl64-custom-1.1.0
 #######################################
 # Copyright SerDigital64 - https://github.com/serdigital64
 #
@@ -21,105 +22,73 @@
 declare INST64_BASHLIB64="${INST64_BASHLIB64:-/opt/bl64}"
 [[ ! -d "$INST64_BASHLIB64" && -d "${HOME}/at64" ]] && INST64_BASHLIB64="${HOME}/at64"
 # shellcheck disable=SC2015
-source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
+source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-xsv.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-bsh.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-rxtx.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-api.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-vcs.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-txt.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-module-fmt.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-fs.bash" &&
-  source "${INST64_BASHLIB64}/bashlib64-module-arc.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-rnd.bash" &&
+  source "${INST64_BASHLIB64}/bashlib64-module-iam.bash" &&
   source "${INST64_BASHLIB64}/bashlib64-core.bash" ||
   { echo "Fatal: unable to load BashLib64 libraries (${INST64_BASHLIB64})." && exit 1; }
 source "${BL64_SCRIPT_PATH}/lib-bl64" ||
-  { echo "Fatal: unable to load Installer64 libraries (${BL64_SCRIPT_PATH}/lib-bl64)" && exit 1; }
+  { echo 'Fatal: unable to load Installer64 libraries.' && exit 1; }
 
 #
 # Globals
 #
 
 # Installation method
-declare INST64_NIKTO_METHOD="${INST64_NIKTO_METHOD:-CUSTOM}"
-# Installation destination
-declare INST64_NIKTO_TARGET="${INST64_NIKTO_TARGET:-}"
-# Hardware architecture
-declare INST64_NIKTO_PLATFORM="${INST64_NIKTO_PLATFORM:-}"
+declare INST64_X_APP_NAME_CAPS_X_METHOD="${INST64_X_APP_NAME_CAPS_X_METHOD:-FPAK}"
 # Application version
-declare INST64_NIKTO_VERSION="${INST64_NIKTO_VERSION:-latest}"
+declare INST64_X_APP_NAME_CAPS_X_VERSION="${INST64_X_APP_NAME_CAPS_X_VERSION:-latest}"
 
-INST64_APP_NAME='nikto'
-INST64_APP_ID='NIKTO'
-INST64_APP_FULL_NAME='Nikto - Web Server Vulnerability Scanner'
-INST64_CLI_NAME='nikto.pl'
-INST64_CLI_SUBPATH='program'
+# App information
+INST64_APP_NAME='X_APP_NAME_X'
+INST64_APP_ID='X_APP_NAME_CAPS_X'
+INST64_APP_FULL_NAME='X_APP_FULL_NAME_X'
 
-INST64_GIT_SERVER='https://github.com/sullo'
-INST64_GIT_REPO='nikto.git'
-INST64_GIT_BRANCH='master'
+INST64_CLI_NAME='X_CLI_NAME_X'
+
+INST64_PKG_MAIN=''
+INST64_FPAK_REPO_NAME=''
 
 #
 # Functions
 #
 
-function inst64_install_custom() {
-  bl64_dbg_app_show_function
-
-  inst64_lib_task_download
-  inst64_lib_staging_create &&
-    inst64_lib_git_get_dir ||
-    return $?
-
-  inst64_lib_task_deploy
-  inst64_lib_target_normalize &&
-    inst64_lib_cli_normalize ||
-    return $?
-
-  inst64_lib_task_cleanup
-  inst64_lib_staging_remove
-}
-
 function inst64_prepare() {
   bl64_dbg_app_show_function
   inst64_lib_step_prepare || return 0
-  if [[ "$INST64_NIKTO_METHOD" == 'CUSTOM' ]]; then
-    inst64_lib_base_create_path
-  fi
 }
 
 function inst64_install() {
   bl64_dbg_app_show_function
   inst64_lib_step_install || return 0
-  if [[ "$INST64_NIKTO_METHOD" == 'CUSTOM' ]]; then
-    inst64_install_custom
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'FPAK' ]]; then
+    inst64_lib_flatpak_install
   fi
 }
 
 function inst64_setup() {
   bl64_dbg_app_show_function
   inst64_lib_step_setup || return 0
-  if [[ "$INST64_NIKTO_METHOD" == 'CUSTOM' ]]; then
-    inst64_lib_task_publish
-    inst64_lib_cli_promote
-  fi
 }
 
 function inst64_verify() {
   bl64_dbg_app_show_function
   inst64_lib_step_verify || return 0
-  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" -Version
+  "${INST64_CLI_PATH}/${INST64_CLI_NAME}" --version
 }
 
 function inst64_select_method() {
   bl64_dbg_app_show_function
   inst64_lib_app_check_method \
     'AUTO' \
-    'CUSTOM' ||
+    'FPAK' ||
     return $?
-  if [[ "$INST64_NIKTO_METHOD" == 'AUTO' ]]; then
-    INST64_NIKTO_METHOD='CUSTOM'
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'AUTO' ]]; then
+    INST64_X_APP_NAME_CAPS_X_METHOD='FPAK'
   fi
 }
 
@@ -130,7 +99,16 @@ function inst64_select_platform() {
 
 function inst64_select_packages() {
   bl64_dbg_app_show_function
-  return 0
+  local version_target=''
+  if [[ "$INST64_X_APP_NAME_CAPS_X_METHOD" == 'FPAK' ]]; then
+    if [[ "$INST64_X_APP_NAME_CAPS_X_VERSION" == 'latest' ]]; then
+      version_target=''
+    else
+      version_target="@${INST64_X_APP_NAME_CAPS_X_VERSION}"
+    fi
+    INST64_PKG_MAIN="${INST64_PKG_MAIN}${version_target}"
+  fi
+  inst64_lib_package_check_definition
 }
 
 function inst64_initialize() {
@@ -138,16 +116,6 @@ function inst64_initialize() {
   inst64_select_method &&
     inst64_lib_base_initialize ||
     return $?
-
-  if [[ "$INST64_NIKTO_METHOD" == 'CUSTOM' ]]; then
-    if bl64_lib_flag_is_enabled "$INST64_SYSTEM_WIDE"; then
-      bl64_check_privilege_root ||
-        return $?
-    fi
-    bl64_check_command_search_path 'perl' &&
-      bl64_arc_setup ||
-      return $?
-  fi
 
   inst64_select_platform &&
     inst64_select_packages &&
@@ -162,7 +130,7 @@ function inst64_initialize() {
 # Main
 #
 
-bl64_lib_script_version_set '2.0.1'
+bl64_lib_script_version_set '1.0.0'
 bl64_msg_all_enable_verbose
 bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
 
